/// Bentuk lembar kerja contoh **Flowmeter Ultrasonic** (kelompok Aliran, alat
/// ke-27 & ke-28).
///
/// DIGENERATE `docs/skrip/gen-contoh-lembar-kerja.php` di repo API — jangan
/// disunting tangan. Isinya salinan APA ADANYA respons
/// `GET /api/calibrations/lembar-kerja?equipment_id=…` untuk alat contoh
/// ter-seed `FM-TOT-DEMO-01` dan `FM-FLW-DEMO-01`.
///
/// ## Yang cuma ada di lembar ini
///
///  1. **Satu titik, DUA deret berdampingan.** `flow_uut_pembacaan` dan
///     `flow_std_pembacaan` tabelnya terpisah, dan deviasinya lahir dari
///     selisih BERPASANGAN keduanya. Tertukar atau tertimpa, yang terbit bukan
///     error melainkan deviasi NOL di setiap titik.
///  2. **Deret UUT yang BERSARANG** pada varian Flowrate: `pengulangan` itu
///     ulangan, `kolom` (`durasi_1..3`) itu durasi 20"/40"/60". Simpangan
///     bakunya dihitung atas ketiga durasi ulangan ITU — diratakan, komponen
///     budget ke-3 keluar jauh lebih besar dan tetap terlihat masuk akal.
///  3. **LIMA tabel ber-`tahap` sama** di bagian `hasil`, plus dua di bagian
///     `pipa`. Kunci barisnya dipisah `offset_kunci` (0 / 1000 / 2000 / 3000 /
///     4000 / 5000 / 5100); tanpa itu angka yang diketik di satu kotak muncul
///     di kotak lain, tanpa satu pun error.
///  4. **Geometri pipa yang MENENTUKAN ANGKA.** Diameter & ketebalan kosong
///     bikin `u_A` nol dan DUA komponen budget lenyap sekaligus.
///
/// Dropdown bersumber master (`master_alat`, `master_ruangan`,
/// `master_thermohygro`) sengaja kosong di sini — sama seperti berkas contoh
/// alat lain, mode mock memang nggak punya masternya.
library;

/// Bentuk lembar kerja contoh **Flow Meter Cairan (Totalizer)**.
///
/// Kode profil `flowmeter_totalizer`, satuan `L`, kertas `SIDIK-FM-CAL-0538.B_Rev.3`.
Map<String, dynamic> contohBentukLembarKerjaFlowmeterTotalizer({
  bool untukAdmin = false,
}) {
  return {
    'kode_dokumen': 'SIDIK-FM-CAL-0538.B_Rev.3',
    'kode_dokumen_varian': {
      'ufm': 'SIDIK-FM-CAL-0538_Rev.0',
      'gravimetri': 'SIDIK-FM-CAL-0538.B_Rev.3',
    },
    'kode_metode': 'SIDIK-IK-CAL-0528_Rev.4',
    'nomor_lingkup': 'LK-285-IDN',
    'judul': 'Calibration Work Sheet - Flow Meter Cairan (Totalizer)',
    'jumlah_pengulangan': 3,
    'satuan': 'L',
    'satuan_suhu': '°C',
    'semua_kolom_opsional': true,
    'catatan_pengisian': 'Isi MODE dan SATUAN alat lebih dulu — mode menentukan budgetnya 8 komponen, satuan menentukan faktor konversinya ke L. Satuan berbasis MASSA (kg, kg/h, kg/min) WAJIB disertai densitas fluida UUT; tanpa itu pembacaannya tidak bisa diubah ke L sama sekali dan titiknya tidak diterbitkan. Diameter luar & ketebalan pipa dibaca 3 kali — dari sebarannya komponen `Cross Section Area` lahir, jadi mengosongkannya MENGECILKAN U95.',
    'budget_ketidakpastian': {
      'tersedia': true,
      'sumber': '1.3 Master Olah Data Flowmeter_Ultrasonic Totalizer (1000-1900L) 2026.xlsm',
      'catatan': 'Delapan komponen PER TITIK, berlantai CMC `% of reading` dari lampiran LK-285-IDN no. 30. Belum memuat komponen "Pengulangan Pembacaan UUT" yang lahir di revisi Flowrate 20 Mei 2026 — ditiru apa adanya, lihat pertanyaan lab §3.',
    },
    'bagian': [
      {
        'kode': 'identitas_alat',
        'halaman': 1,
        'judul': 'Identitas Alat',
        'field': [
          {
            'kode': 'equipment_id',
            'label': 'Pilih Alat',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_alat',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.mode',
            'label': 'Mode',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'totalizer',
                'label': 'Totalizer',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
            'di_luar_kertas': true,
          },
          {
            'kode': 'equipment.nama_alat',
            'label': 'Nama Alat',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.satuan',
            'label': 'Satuan ( ) — Range/Capacity & Resolusi',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'L',
                'label': 'L',
              },
              {
                'nilai': 'm3',
                'label': 'm3',
              },
              {
                'nilai': 'usg',
                'label': 'usg',
              },
              {
                'nilai': 'ml',
                'label': 'ml',
              },
              {
                'nilai': 'kg',
                'label': 'kg',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.kapasitas',
            'label': 'Range/Capacity',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'L',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.resolusi',
            'label': 'Resolusi',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'L',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_model',
            'label': 'Type/Model',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_serial_number',
            'label': 'Serial Number',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_merk',
            'label': 'Merk/Manufacture',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_terima',
            'label': 'Tanggal Terima',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_kalibrasi',
            'label': 'Tanggal Kalibrasi',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_awal',
            'label': 'Suhu Ruangan — awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_akhir',
            'label': 'Suhu Ruangan — akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_awal',
            'label': 'Kelembapan — awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_akhir',
            'label': 'Kelembapan — akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'thermohygro_standard_id',
            'label': 'Thermohygro used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_thermohygro',
            'satuan': null,
            'pilihan': [
              {
                'nilai': '1',
                'label': 'TH-1',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '2',
                'label': 'TH-2',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '3',
                'label': 'TH-3',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '4',
                'label': 'TH-4',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '5',
                'label': 'TH-5',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '6',
                'label': 'TH-6',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '7',
                'label': 'TH-7',
                'grup': 'Thermohygro lab',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi',
            'label': 'Lokasi Kalibrasi',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'lab',
                'label': 'Inlab',
              },
              {
                'nilai': 'onsite',
                'label': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'room_id',
            'label': 'Ruangan (Inlab)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_ruangan',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'lab',
              ],
            },
          },
          {
            'kode': 'lokasi_nama',
            'label': 'Nama Tempat (Insitu)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'onsite',
              ],
            },
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.varian_metode',
            'label': 'Metode Kalibrasi',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'ufm',
                'label': 'Perbandingan langsung UFM (Krohne UFC300) — master BELUM divalidasi',
              },
              {
                'nilai': 'gravimetri',
                'label': 'Penimbangan statis gravimetri (ISO 4185)',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.kode_timbangan',
            'label': 'Timbangan Standar',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 1,
                'label': '1 — Dini Argeo DFWLB-3 (U95 0.52 kg)',
              },
              {
                'nilai': 2,
                'label': '2 — Sartorius 150GF (U95 0.033 kg)',
              },
              {
                'nilai': 3,
                'label': '3 — Mettler DJ Series / di kertas: Excellent (U95 0.00017 kg)',
              },
              {
                'nilai': 4,
                'label': '4 — Fujitsu FSR-A (U95 1.6E-5 kg)',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'spesifikasi_alat.flowmeter.varian_metode',
              'nilai': [
                'gravimetri',
              ],
            },
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.volume_pipa_l',
            'label': 'Volume Pipa dari Std. ke UUT (V)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'L',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'spesifikasi_alat.flowmeter.varian_metode',
              'nilai': [
                'gravimetri',
              ],
            },
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.material_pipa',
            'label': 'Material Pipa',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.jenis_fluida',
            'label': 'Jenis Fluida',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.path_configuration',
            'label': 'Path Configuration (Sensor Mounting Method)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'Z',
                'label': 'Z-Method',
              },
              {
                'nilai': 'V',
                'label': 'V-Method',
              },
              {
                'nilai': 'W',
                'label': 'W-Method',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.liner_material',
            'label': 'Liner — Material',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.liner_ketebalan_mm',
            'label': 'Liner — Ketebalan',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'mm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'pemilik',
        'halaman': 1,
        'judul': 'Identitas Customer',
        'field': [
          {
            'kode': 'pemilik_nama',
            'label': 'Nama',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'pemilik_alamat',
            'label': 'Alamat',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'usage_check',
        'halaman': 1,
        'judul': 'Standard',
        'baris': [
          {
            'label': 'Ultrasonic Flowmeter/Krohne/UFC300',
            'standard_id': 66,
            'serial_number': 'A18P045140',
            'no_sertifikat': 'A18P045140',
            'tertelusur_ke': 'LK-285-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Temperature Calibrator/Yokogawa/CA 150 Handy Cal',
            'standard_id': 13,
            'serial_number': '23P1005',
            'no_sertifikat': '23P1005',
            'tertelusur_ke': 'LK-285-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Thermocouple Type K',
            'standard_id': 49,
            'serial_number': 'TC-01,02',
            'no_sertifikat': 'TC-01,02',
            'tertelusur_ke': 'LK-064-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Digital Caliper/Tesa/Cal-IP67',
            'standard_id': 63,
            'serial_number': 'LPI-0368',
            'no_sertifikat': 'LPI-0368',
            'tertelusur_ke': 'LK-285-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Ultrasonic Thickness Gauge/TM-8812',
            'standard_id': 65,
            'serial_number': 'N889479',
            'no_sertifikat': 'N889479',
            'tertelusur_ke': null,
            'terdaftar': true,
          },
        ],
        'field': [
          {
            'kode': 'standar_dicek.*.dipakai',
            'label': 'Usage Check',
            'tipe': 'centang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'standar_dicek.*.keterangan',
            'label': 'Keterangan',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'pipa',
        'halaman': 2,
        'judul': 'Diameter & Ketebalan pipa',
        'field': <dynamic>[],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'pipa_diameter',
            'judul': 'Diameter pipa (mm)',
            'satuan': 'mm',
            'judul_nilai': 'Diameter Luar',
            'judul_pengulangan': 'Pembacaan',
            'titik_bisa_diubah': false,
            'pita_cetak': 1,
            'offset_kunci': 5000,
            'simpan_ke': 'spesifikasi_alat.flowmeter.diameter_pipa_mm',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Diameter Luar',
                'satuan': 'mm',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'mm',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'pipa_ketebalan',
            'judul': 'Ketebalan pipa (mm)',
            'satuan': 'mm',
            'judul_nilai': 'Ketebalan',
            'judul_pengulangan': 'Pembacaan',
            'titik_bisa_diubah': false,
            'pita_cetak': 1,
            'offset_kunci': 5100,
            'simpan_ke': 'spesifikasi_alat.flowmeter.ketebalan_pipa_mm',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Ketebalan',
                'satuan': 'mm',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'mm',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
        ],
      },
      {
        'kode': 'hasil',
        'halaman': 2,
        'judul': 'Measurement',
        'tampilan': 'kartu_per_set_point',
        'kartu_sejajar': false,
        'nominal_berbintang': false,
        'field': <dynamic>[],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'flow_uut_pembacaan',
            'judul': 'Reading of UUT',
            'satuan': 'L',
            'judul_nilai': 'Set Point',
            'judul_pengulangan': 'Repeat',
            'titik_bisa_diubah': true,
            'pita_cetak': 2,
            'offset_kunci': 0,
            'simpan_ke': 'measurements[].flow_uut_pembacaan',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Set Point 1',
                'satuan': 'L',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Set Point 2',
                'satuan': 'L',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Set Point 3',
                'satuan': 'L',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'L',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'flow_std_pembacaan',
            'judul': 'Standard Reading',
            'satuan': 'L',
            'judul_nilai': 'Set Point',
            'judul_pengulangan': 'Repeat',
            'titik_bisa_diubah': true,
            'pita_cetak': 3,
            'offset_kunci': 1000,
            'simpan_ke': 'measurements[].flow_std_pembacaan',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Set Point 1',
                'satuan': 'L',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Set Point 2',
                'satuan': 'L',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Set Point 3',
                'satuan': 'L',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'L',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
            'tampil_kalau': {
              'kode': 'spesifikasi_alat.flowmeter.varian_metode',
              'nilai': [
                'ufm',
              ],
            },
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'flow_berat_isi',
            'judul': 'Berat Isi (air tertimbang)',
            'satuan': 'kg',
            'judul_nilai': 'Set Point',
            'judul_pengulangan': 'Repeat',
            'titik_bisa_diubah': true,
            'pita_cetak': 3,
            'offset_kunci': 6000,
            'simpan_ke': 'measurements[].flow_berat_isi',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Set Point 1',
                'satuan': 'L',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Set Point 2',
                'satuan': 'L',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Set Point 3',
                'satuan': 'L',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'kg',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
            'tampil_kalau': {
              'kode': 'spesifikasi_alat.flowmeter.varian_metode',
              'nilai': [
                'gravimetri',
              ],
            },
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'flow_berat_kosong',
            'judul': 'Berat Wadah Kosong (tara)',
            'satuan': 'kg',
            'judul_nilai': 'Set Point',
            'judul_pengulangan': 'Repeat',
            'titik_bisa_diubah': true,
            'pita_cetak': 3,
            'offset_kunci': 7000,
            'simpan_ke': 'measurements[].flow_berat_kosong',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Set Point 1',
                'satuan': 'L',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Set Point 2',
                'satuan': 'L',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Set Point 3',
                'satuan': 'L',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'kg',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
            'tampil_kalau': {
              'kode': 'spesifikasi_alat.flowmeter.varian_metode',
              'nilai': [
                'gravimetri',
              ],
            },
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'flow_suhu_awal',
            'judul': 'Temperature Awal',
            'satuan': '°C',
            'judul_nilai': 'Set Point',
            'judul_pengulangan': 'Repeat',
            'titik_bisa_diubah': true,
            'pita_cetak': 4,
            'offset_kunci': 2000,
            'simpan_ke': 'measurements[].flow_suhu_awal',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Set Point 1',
                'satuan': 'L',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Set Point 2',
                'satuan': 'L',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Set Point 3',
                'satuan': 'L',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': '°C',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'flow_suhu_akhir',
            'judul': 'Temperature Akhir',
            'satuan': '°C',
            'judul_nilai': 'Set Point',
            'judul_pengulangan': 'Repeat',
            'titik_bisa_diubah': true,
            'pita_cetak': 4,
            'offset_kunci': 3000,
            'simpan_ke': 'measurements[].flow_suhu_akhir',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Set Point 1',
                'satuan': 'L',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Set Point 2',
                'satuan': 'L',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Set Point 3',
                'satuan': 'L',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': '°C',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'flow_densitas_uut',
            'judul': 'Densitas Fluida UUT (wajib kalau satuan berbasis massa)',
            'satuan': 'kg/L',
            'judul_nilai': 'Set Point',
            'judul_pengulangan': 'Repeat',
            'titik_bisa_diubah': true,
            'pita_cetak': 4,
            'offset_kunci': 4000,
            'simpan_ke': 'measurements[].flow_densitas_uut',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Set Point 1',
                'satuan': 'L',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Set Point 2',
                'satuan': 'L',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Set Point 3',
                'satuan': 'L',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'kg/L',
              },
            ],
            'pengulangan': [
              1,
            ],
            'tampil_kalau': {
              'kode': 'spesifikasi_alat.flowmeter.varian_metode',
              'nilai': [
                'ufm',
              ],
            },
            'di_luar_kertas': true,
          },
        ],
      },
      {
        'kode': 'di_luar_kertas',
        'halaman': 2,
        'judul': 'Di luar kertas — dipakai hitung',
        'di_luar_kertas': true,
        'catatan': 'Tidak ada di formulir kertas SIDIK-FM-CAL-0538, tapi dipakai olah data. Tetap diisi.',
        'field': [
          {
            'kode': 'spesifikasi_alat.rentang_ukur',
            'label': 'Rentang Ukur',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
            'di_luar_kertas': true,
          },
          {
            'kode': 'nomor_order',
            'label': 'Order Number',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
            'di_luar_kertas': true,
          },
        ],
      },
      {
        'kode': 'penutup',
        'halaman': 2,
        'judul': 'Catatan & Tanda Tangan',
        'field': [
          {
            'kode': 'catatan_teknisi',
            'label': 'Catatan',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'teknisi.nama',
            'label': 'Dikalibrasi Oleh',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'reviewer.nama',
            'label': 'Diperiksa Oleh',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
    ],
  };
}

/// Bentuk lembar kerja contoh **Flow Meter Cairan (Flowrate)**.
///
/// Kode profil `flowmeter_flowrate`, satuan `Lpm`, kertas `SIDIK-FM-CAL-0538.A_Rev.3`.
Map<String, dynamic> contohBentukLembarKerjaFlowmeterFlowrate({
  bool untukAdmin = false,
}) {
  return {
    'kode_dokumen': 'SIDIK-FM-CAL-0538.A_Rev.3',
    'kode_dokumen_varian': {
      'ufm': 'SIDIK-FM-CAL-0538_Rev.0',
      'gravimetri': 'SIDIK-FM-CAL-0538.A_Rev.3',
    },
    'kode_metode': 'SIDIK-IK-CAL-0528_Rev.4',
    'nomor_lingkup': 'LK-285-IDN',
    'judul': 'Calibration Work Sheet - Flow Meter Cairan (Flowrate)',
    'jumlah_pengulangan': 3,
    'satuan': 'Lpm',
    'satuan_suhu': '°C',
    'semua_kolom_opsional': true,
    'catatan_pengisian': 'Isi MODE dan SATUAN alat lebih dulu — mode menentukan budgetnya 9 komponen, satuan menentukan faktor konversinya ke Lpm. Satuan berbasis MASSA (kg, kg/h, kg/min) WAJIB disertai densitas fluida UUT; tanpa itu pembacaannya tidak bisa diubah ke Lpm sama sekali dan titiknya tidak diterbitkan. Diameter luar & ketebalan pipa dibaca 3 kali — dari sebarannya komponen `Cross Section Area` lahir, jadi mengosongkannya MENGECILKAN U95. Tiap ulangan diisi 3 durasi; simpangan bakunya dihitung atas ketiga durasi ulangan ITU, bukan antar-ulangan.',
    'budget_ketidakpastian': {
      'tersedia': true,
      'sumber': 'Master olda Ultrasonic Flowrate (100-300 lpm) 2026.xlsm',
      'catatan': 'Sembilan komponen PER TITIK, berlantai CMC `% of reading` dari lampiran LK-285-IDN no. 31. Komponen ke-9 "Pengulangan Pembacaan UUT" lahir dari revisi 20 Mei 2026 yang belum masuk workbook Totalizer — lihat pertanyaan lab §3.',
    },
    'bagian': [
      {
        'kode': 'identitas_alat',
        'halaman': 1,
        'judul': 'Identitas Alat',
        'field': [
          {
            'kode': 'equipment_id',
            'label': 'Pilih Alat',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_alat',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.mode',
            'label': 'Mode',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'flowrate',
                'label': 'Flowrate',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
            'di_luar_kertas': true,
          },
          {
            'kode': 'equipment.nama_alat',
            'label': 'Nama Alat',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.satuan',
            'label': 'Satuan ( ) — Range/Capacity & Resolusi',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'LPM',
                'label': 'LPM',
              },
              {
                'nilai': 'm3/h',
                'label': 'm3/h',
              },
              {
                'nilai': 'usg/min',
                'label': 'usg/min',
              },
              {
                'nilai': 'm3/min',
                'label': 'm3/min',
              },
              {
                'nilai': 'kg/h',
                'label': 'kg/h',
              },
              {
                'nilai': 'kg/min',
                'label': 'kg/min',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.kapasitas',
            'label': 'Range/Capacity',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'Lpm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.resolusi',
            'label': 'Resolusi',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'Lpm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_model',
            'label': 'Type/Model',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_serial_number',
            'label': 'Serial Number',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_merk',
            'label': 'Merk/Manufacture',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_terima',
            'label': 'Tanggal Terima',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_kalibrasi',
            'label': 'Tanggal Kalibrasi',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_awal',
            'label': 'Suhu Ruangan — awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_akhir',
            'label': 'Suhu Ruangan — akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_awal',
            'label': 'Kelembapan — awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_akhir',
            'label': 'Kelembapan — akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'thermohygro_standard_id',
            'label': 'Thermohygro used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_thermohygro',
            'satuan': null,
            'pilihan': [
              {
                'nilai': '1',
                'label': 'TH-1',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '2',
                'label': 'TH-2',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '3',
                'label': 'TH-3',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '4',
                'label': 'TH-4',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '5',
                'label': 'TH-5',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '6',
                'label': 'TH-6',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '7',
                'label': 'TH-7',
                'grup': 'Thermohygro lab',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi',
            'label': 'Lokasi Kalibrasi',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'lab',
                'label': 'Inlab',
              },
              {
                'nilai': 'onsite',
                'label': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'room_id',
            'label': 'Ruangan (Inlab)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_ruangan',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'lab',
              ],
            },
          },
          {
            'kode': 'lokasi_nama',
            'label': 'Nama Tempat (Insitu)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'onsite',
              ],
            },
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.varian_metode',
            'label': 'Metode Kalibrasi',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'ufm',
                'label': 'Perbandingan langsung UFM (Krohne UFC300) — master BELUM divalidasi',
              },
              {
                'nilai': 'gravimetri',
                'label': 'Penimbangan statis gravimetri (ISO 4185)',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.kode_timbangan',
            'label': 'Timbangan Standar',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 1,
                'label': '1 — Dini Argeo DFWLB-3 (U95 0.52 kg)',
              },
              {
                'nilai': 2,
                'label': '2 — Sartorius 150GF (U95 0.033 kg)',
              },
              {
                'nilai': 3,
                'label': '3 — Mettler DFWLB-3 / di kertas: Excellent (U95 0.00017 kg)',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'spesifikasi_alat.flowmeter.varian_metode',
              'nilai': [
                'gravimetri',
              ],
            },
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.volume_pipa_l',
            'label': 'Volume Pipa dari Std. ke UUT (V)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'L',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'spesifikasi_alat.flowmeter.varian_metode',
              'nilai': [
                'gravimetri',
              ],
            },
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.material_pipa',
            'label': 'Material Pipa',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.jenis_fluida',
            'label': 'Jenis Fluida',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.path_configuration',
            'label': 'Path Configuration (Sensor Mounting Method)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'Z',
                'label': 'Z-Method',
              },
              {
                'nilai': 'V',
                'label': 'V-Method',
              },
              {
                'nilai': 'W',
                'label': 'W-Method',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.liner_material',
            'label': 'Liner — Material',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.liner_ketebalan_mm',
            'label': 'Liner — Ketebalan',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'mm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'pemilik',
        'halaman': 1,
        'judul': 'Identitas Customer',
        'field': [
          {
            'kode': 'pemilik_nama',
            'label': 'Nama',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'pemilik_alamat',
            'label': 'Alamat',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'usage_check',
        'halaman': 1,
        'judul': 'Standard',
        'baris': [
          {
            'label': 'Ultrasonic Flowmeter/Krohne/UFC300',
            'standard_id': 66,
            'serial_number': 'A18P045140',
            'no_sertifikat': 'A18P045140',
            'tertelusur_ke': 'LK-285-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Temperature Calibrator/Yokogawa/CA 150 Handy Cal',
            'standard_id': 13,
            'serial_number': '23P1005',
            'no_sertifikat': '23P1005',
            'tertelusur_ke': 'LK-285-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Thermocouple Type K',
            'standard_id': 49,
            'serial_number': 'TC-01,02',
            'no_sertifikat': 'TC-01,02',
            'tertelusur_ke': 'LK-064-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Digital Caliper/Tesa/Cal-IP67',
            'standard_id': 63,
            'serial_number': 'LPI-0368',
            'no_sertifikat': 'LPI-0368',
            'tertelusur_ke': 'LK-285-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Ultrasonic Thickness Gauge/TM-8812',
            'standard_id': 65,
            'serial_number': 'N889479',
            'no_sertifikat': 'N889479',
            'tertelusur_ke': null,
            'terdaftar': true,
          },
        ],
        'field': [
          {
            'kode': 'standar_dicek.*.dipakai',
            'label': 'Usage Check',
            'tipe': 'centang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'standar_dicek.*.keterangan',
            'label': 'Keterangan',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'pipa',
        'halaman': 2,
        'judul': 'Diameter & Ketebalan pipa',
        'field': <dynamic>[],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'pipa_diameter',
            'judul': 'Diameter pipa (mm)',
            'satuan': 'mm',
            'judul_nilai': 'Diameter Luar',
            'judul_pengulangan': 'Pembacaan',
            'titik_bisa_diubah': false,
            'pita_cetak': 1,
            'offset_kunci': 5000,
            'simpan_ke': 'spesifikasi_alat.flowmeter.diameter_pipa_mm',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Diameter Luar',
                'satuan': 'mm',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'mm',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'pipa_ketebalan',
            'judul': 'Ketebalan pipa (mm)',
            'satuan': 'mm',
            'judul_nilai': 'Ketebalan',
            'judul_pengulangan': 'Pembacaan',
            'titik_bisa_diubah': false,
            'pita_cetak': 1,
            'offset_kunci': 5100,
            'simpan_ke': 'spesifikasi_alat.flowmeter.ketebalan_pipa_mm',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Ketebalan',
                'satuan': 'mm',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'mm',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
        ],
      },
      {
        'kode': 'hasil',
        'halaman': 2,
        'judul': 'Measurement',
        'tampilan': 'kartu_per_set_point',
        'kartu_sejajar': false,
        'nominal_berbintang': false,
        'field': <dynamic>[],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'flow_uut_pembacaan',
            'judul': 'Reading of UUT',
            'satuan': 'Lpm',
            'judul_nilai': 'Set Point',
            'judul_pengulangan': 'Repeat',
            'titik_bisa_diubah': true,
            'pita_cetak': 2,
            'offset_kunci': 0,
            'simpan_ke': 'measurements[].flow_uut_pembacaan',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Set Point 1',
                'satuan': 'Lpm',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Set Point 2',
                'satuan': 'Lpm',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Set Point 3',
                'satuan': 'Lpm',
              },
            ],
            'kolom': [
              {
                'kode': 'durasi_1',
                'label': '20"',
                'tipe': 'angka',
                'satuan': 'Lpm',
              },
              {
                'kode': 'durasi_2',
                'label': '40"',
                'tipe': 'angka',
                'satuan': 'Lpm',
              },
              {
                'kode': 'durasi_3',
                'label': '60"',
                'tipe': 'angka',
                'satuan': 'Lpm',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'flow_std_pembacaan',
            'judul': 'Standard Reading',
            'satuan': 'Lpm',
            'judul_nilai': 'Set Point',
            'judul_pengulangan': 'Repeat',
            'titik_bisa_diubah': true,
            'pita_cetak': 3,
            'offset_kunci': 1000,
            'simpan_ke': 'measurements[].flow_std_pembacaan',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Set Point 1',
                'satuan': 'Lpm',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Set Point 2',
                'satuan': 'Lpm',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Set Point 3',
                'satuan': 'Lpm',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'Lpm',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
            'tampil_kalau': {
              'kode': 'spesifikasi_alat.flowmeter.varian_metode',
              'nilai': [
                'ufm',
              ],
            },
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'flow_berat_isi',
            'judul': 'Berat Isi (air tertimbang)',
            'satuan': 'kg',
            'judul_nilai': 'Set Point',
            'judul_pengulangan': 'Repeat',
            'titik_bisa_diubah': true,
            'pita_cetak': 3,
            'offset_kunci': 6000,
            'simpan_ke': 'measurements[].flow_berat_isi',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Set Point 1',
                'satuan': 'Lpm',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Set Point 2',
                'satuan': 'Lpm',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Set Point 3',
                'satuan': 'Lpm',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'kg',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
            'tampil_kalau': {
              'kode': 'spesifikasi_alat.flowmeter.varian_metode',
              'nilai': [
                'gravimetri',
              ],
            },
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'flow_berat_kosong',
            'judul': 'Berat Wadah Kosong (tara)',
            'satuan': 'kg',
            'judul_nilai': 'Set Point',
            'judul_pengulangan': 'Repeat',
            'titik_bisa_diubah': true,
            'pita_cetak': 3,
            'offset_kunci': 7000,
            'simpan_ke': 'measurements[].flow_berat_kosong',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Set Point 1',
                'satuan': 'Lpm',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Set Point 2',
                'satuan': 'Lpm',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Set Point 3',
                'satuan': 'Lpm',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'kg',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
            'tampil_kalau': {
              'kode': 'spesifikasi_alat.flowmeter.varian_metode',
              'nilai': [
                'gravimetri',
              ],
            },
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'flow_suhu_awal',
            'judul': 'Temperature Awal',
            'satuan': '°C',
            'judul_nilai': 'Set Point',
            'judul_pengulangan': 'Repeat',
            'titik_bisa_diubah': true,
            'pita_cetak': 4,
            'offset_kunci': 2000,
            'simpan_ke': 'measurements[].flow_suhu_awal',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Set Point 1',
                'satuan': 'Lpm',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Set Point 2',
                'satuan': 'Lpm',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Set Point 3',
                'satuan': 'Lpm',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': '°C',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'flow_suhu_akhir',
            'judul': 'Temperature Akhir',
            'satuan': '°C',
            'judul_nilai': 'Set Point',
            'judul_pengulangan': 'Repeat',
            'titik_bisa_diubah': true,
            'pita_cetak': 4,
            'offset_kunci': 3000,
            'simpan_ke': 'measurements[].flow_suhu_akhir',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Set Point 1',
                'satuan': 'Lpm',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Set Point 2',
                'satuan': 'Lpm',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Set Point 3',
                'satuan': 'Lpm',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': '°C',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'flow_densitas_uut',
            'judul': 'Densitas Fluida UUT (wajib kalau satuan berbasis massa)',
            'satuan': 'kg/L',
            'judul_nilai': 'Set Point',
            'judul_pengulangan': 'Repeat',
            'titik_bisa_diubah': true,
            'pita_cetak': 4,
            'offset_kunci': 4000,
            'simpan_ke': 'measurements[].flow_densitas_uut',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Set Point 1',
                'satuan': 'Lpm',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Set Point 2',
                'satuan': 'Lpm',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Set Point 3',
                'satuan': 'Lpm',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'kg/L',
              },
            ],
            'pengulangan': [
              1,
            ],
            'tampil_kalau': {
              'kode': 'spesifikasi_alat.flowmeter.varian_metode',
              'nilai': [
                'ufm',
              ],
            },
            'di_luar_kertas': true,
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'flow_waktu_menit',
            'judul': 'Time',
            'satuan': 'menit',
            'judul_nilai': 'Set Point',
            'judul_pengulangan': 'Repeat',
            'titik_bisa_diubah': true,
            'pita_cetak': 4,
            'offset_kunci': 8000,
            'simpan_ke': 'measurements[].flow_waktu_menit',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Set Point 1',
                'satuan': 'Lpm',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Set Point 2',
                'satuan': 'Lpm',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Set Point 3',
                'satuan': 'Lpm',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'menit',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
            'tampil_kalau': {
              'kode': 'spesifikasi_alat.flowmeter.varian_metode',
              'nilai': [
                'gravimetri',
              ],
            },
          },
        ],
      },
      {
        'kode': 'di_luar_kertas',
        'halaman': 2,
        'judul': 'Di luar kertas — dipakai hitung',
        'di_luar_kertas': true,
        'catatan': 'Tidak ada di formulir kertas SIDIK-FM-CAL-0538, tapi dipakai olah data. Tetap diisi.',
        'field': [
          {
            'kode': 'spesifikasi_alat.rentang_ukur',
            'label': 'Rentang Ukur',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
            'di_luar_kertas': true,
          },
          {
            'kode': 'nomor_order',
            'label': 'Order Number',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
            'di_luar_kertas': true,
          },
        ],
      },
      {
        'kode': 'penutup',
        'halaman': 2,
        'judul': 'Catatan & Tanda Tangan',
        'field': [
          {
            'kode': 'catatan_teknisi',
            'label': 'Catatan',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'teknisi.nama',
            'label': 'Dikalibrasi Oleh',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'reviewer.nama',
            'label': 'Diperiksa Oleh',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
    ],
  };
}
