/// Bentuk lembar kerja contoh **Autoklaf**.
///
/// DIGENERATE `docs/skrip/gen-contoh-lembar-kerja.php` di repo API — jangan
/// disunting tangan.
///
/// ## Kenapa Autoklaf punya berkasnya sendiri
///
/// Besarannya SUHU dan TEKANAN sekaligus, jadi dia nggak duduk di
/// `contoh_lembar_kerja_suhu.dart` bareng ketiga alat suhu. Lembarnya juga
/// membawa kunci tingkat-atas yang nggak dipunyai lembar mana pun:
/// `jumlah_disk`, `jumlah_titik_waktu`, `jumlah_pembacaan_tekanan`,
/// `satuan_tekanan_pilihan`, dan `display_tekanan_pilihan`.
///
/// ## Utang terakhir yang dilunasi
///
/// Sampai 9 September 2026 Autoklaf jatuh ke bentuk pH di mode mock — utang
/// TERAKHIR dari tujuh yang ditemukan `bentuk_mock_semua_profil_test.dart`.
/// Yang bikin dia ditinggal paling belakang: sertifikatnya TIGA bagian yang
/// nggak sebangun (Sebaran Suhu, Kinerja, Tekanan), dan bentuk pH nggak punya
/// satu pun di antaranya — bukan "sebagian kolomnya salah", tapi tiga blok yang
/// hilang seluruhnya.
///
/// Perlu dicatat supaya nggak salah baca: jalur mock Autoklaf di HP SUDAH
/// teruji lewat `autoclave_matriks_lembar_generik_test.dart` dan
/// `autoclave_payload_matriks_test.dart`. Yang belum ada cuma bentuk lembarnya
/// sendiri — dan itu justru yang bikin ketiga test itu jalan di atas bentuk
/// yang bukan miliknya.
library;

/// Bentuk lembar kerja contoh **Autoklaf**.
///
/// Kode profil `autoclave`, satuan `-`, kertas `SIDIK-FM-CAL-0539_Rev.4`.
Map<String, dynamic> contohBentukLembarKerjaAutoklaf({
  bool untukAdmin = false,
}) {
  return {
    'kode_dokumen': 'SIDIK-FM-CAL-0539_Rev.4',
    'kode_lembar': 'LK-285-IDN',
    'penerbit': 'PT. SIDIK',
    'judul': 'Calibration Worksheet - Autoclave',
    'metode': 'SIDIK-IK-CAL-0531_Rev.4',
    'besaran': [
      'Suhu',
      'Tekanan',
    ],
    'satuan_suhu': '°C',
    'jumlah_disk': 3,
    'jumlah_titik_waktu': 5,
    'jumlah_pembacaan_tekanan': 5,
    'satuan_tekanan_pilihan': [
      {
        'nilai': 'Bar',
        'label': 'Bar',
        'faktor': 1.0,
      },
      {
        'nilai': 'MPa',
        'label': 'MPa',
        'faktor': 10.0,
      },
      {
        'nilai': 'kPa',
        'label': 'kPa',
        'faktor': 0.01,
      },
      {
        'nilai': 'Psi',
        'label': 'Psi',
        'faktor': 0.0689475729,
      },
      {
        'nilai': 'kg/cm2',
        'label': 'kg/cm²',
        'faktor': 0.980665,
      },
      {
        'nilai': 'inHg',
        'label': 'inHg',
        'faktor': 0.033863886666667,
      },
      {
        'nilai': 'mmHg',
        'label': 'mmHg',
        'faktor': 0.0013332239,
      },
      {
        'nilai': 'Pa',
        'label': 'Pa',
        'faktor': 1.0E-5,
      },
    ],
    'display_tekanan_pilihan': [
      {
        'nilai': 'Digital',
        'label': 'Digital',
      },
      {
        'nilai': 'Analog 1',
        'label': 'Analog (rasio jarum:NST 1/2)',
      },
      {
        'nilai': 'Analog 2',
        'label': 'Analog (rasio jarum:NST 1/5)',
      },
      {
        'nilai': 'Analog 3',
        'label': 'Analog (rasio jarum:NST 1/10)',
      },
    ],
    'semua_kolom_opsional': true,
    'catatan_pengisian': 'Kolom yang belum bisa diisi di lapangan boleh dikosongin. Suhu butuh minimal 1 disk terisi; tekanan butuh minimal 1 pembacaan. Titik waktu yang kosong nggak ikut dirata-rata.',
    'bagian': [
      {
        'kode': 'identitas_alat',
        'grup': 'General Information',
        'kolom': 'kanan',
        'halaman': 1,
        'judul': 'Equipment Identity',
        'field': [
          {
            'kode': 'equipment_id',
            'label': 'Equipment',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_alat',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'equipment.nama_alat',
            'label': 'Equipment Name',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_merk',
            'label': 'Manufacturer',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_model',
            'label': 'Type',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_serial_number',
            'label': 'SN',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'range_suhu',
            'label': 'Range Temp.',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
            'kurung_satuan': true,
          },
          {
            'kode': 'resolusi_suhu',
            'label': 'Resolution Temp.',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
            'kurung_satuan': true,
          },
          {
            'kode': 'range_tekanan',
            'label': 'Range Pressure',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
            'kurung_satuan': true,
            'satuan_dari': 'satuan_tekanan',
          },
          {
            'kode': 'resolusi_tekanan',
            'label': 'Resolution Pressure',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
            'kurung_satuan': true,
            'satuan_dari': 'satuan_tekanan',
          },
          {
            'kode': 'satuan_tekanan',
            'label': 'Pressure Unit',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'Bar',
                'label': 'Bar',
                'faktor': 1.0,
              },
              {
                'nilai': 'MPa',
                'label': 'MPa',
                'faktor': 10.0,
              },
              {
                'nilai': 'kPa',
                'label': 'kPa',
                'faktor': 0.01,
              },
              {
                'nilai': 'Psi',
                'label': 'Psi',
                'faktor': 0.0689475729,
              },
              {
                'nilai': 'kg/cm2',
                'label': 'kg/cm²',
                'faktor': 0.980665,
              },
              {
                'nilai': 'inHg',
                'label': 'inHg',
                'faktor': 0.033863886666667,
              },
              {
                'nilai': 'mmHg',
                'label': 'mmHg',
                'faktor': 0.0013332239,
              },
              {
                'nilai': 'Pa',
                'label': 'Pa',
                'faktor': 1.0E-5,
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
            'di_kertas': false,
          },
        ],
      },
      {
        'kode': 'informasi_umum',
        'grup': 'General Information',
        'halaman': 1,
        'judul': 'General Information',
        'field': [
          {
            'kode': 'tanggal_terima',
            'label': 'Receive Date',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'pemilik_nama',
            'label': 'Customer',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'pemilik_alamat',
            'label': 'Addresss',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_kalibrasi',
            'label': 'Calibration Date',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'kondisi_lokasi',
        'grup': 'General Information',
        'kolom': 'kiri',
        'halaman': 1,
        'judul': 'Location & Environmental Condition',
        'field': [
          {
            'kode': 'lokasi',
            'label': 'Location of Calibration',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'lab',
                'label': 'Inlab',
              },
              {
                'nilai': 'onsite',
                'label': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi_nama',
            'label': 'Nama Tempat (Insitu)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'onsite',
              ],
            },
            'di_kertas': false,
          },
          {
            'kode': 'room_id',
            'label': 'Ruangan (Inlab)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_ruangan',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'lab',
              ],
            },
            'di_kertas': false,
          },
          {
            'kode': 'suhu_awal',
            'label': 'T awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_akhir',
            'label': 'T akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_awal',
            'label': 'RH awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_akhir',
            'label': 'RH akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'thermohygro_standard_id',
            'label': 'Thermohygro used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_thermohygro',
            'satuan': null,
            'pilihan': [
              {
                'nilai': '2',
                'label': 'TH-2',
                'grup': 'Insitu',
                'tercetak': true,
              },
              {
                'nilai': '6',
                'label': 'TH-6',
                'grup': 'Insitu',
                'tercetak': true,
              },
              {
                'nilai': '7',
                'label': 'TH-7',
                'grup': 'Inlab',
                'tercetak': true,
              },
              {
                'nilai': '1',
                'label': 'TH-1',
                'grup': 'Inlab',
                'tercetak': false,
              },
              {
                'nilai': '3',
                'label': 'TH-3',
                'grup': 'Inlab',
                'tercetak': false,
              },
              {
                'nilai': '4',
                'label': 'TH-4',
                'grup': 'Inlab',
                'tercetak': false,
              },
              {
                'nilai': '5',
                'label': 'TH-5',
                'grup': 'Inlab',
                'tercetak': false,
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
            'tampilan': 'centang',
          },
        ],
      },
      {
        'kode': 'usage_check',
        'grup': 'Data Result',
        'halaman': 1,
        'judul': 'Standard Used:',
        'baris': [
          {
            'label': 'Temperature Calibrator -Technosoft (Disk 1,2,3)',
            'standard_id': 40,
            'serial_number': '1011001961',
            'no_sertifikat': '1011001961',
            'tertelusur_ke': 'SNSU-BSN',
            'terdaftar': true,
            'anggota': [
              {
                'label': 'Temperature Calibrator 1 (Tecnosoft/SterilDisk)',
                'standard_id': 40,
                'serial_number': '1011001961',
                'no_sertifikat': '1011001961',
                'tertelusur_ke': 'SNSU-BSN',
                'terdaftar': true,
              },
              {
                'label': 'Temperature Calibrator 2 (Tecnosoft/TS01SD)',
                'standard_id': 41,
                'serial_number': '1011004038',
                'no_sertifikat': '1011004038',
                'tertelusur_ke': 'SNSU-BSN',
                'terdaftar': true,
              },
              {
                'label': 'Temperature Calibrator 3 (Tecnosoft/TS01SD)',
                'standard_id': 42,
                'serial_number': '1011004063',
                'no_sertifikat': '1011004063',
                'tertelusur_ke': 'SNSU-BSN',
                'terdaftar': true,
              },
            ],
          },
          {
            'label': 'Pressure Disk Logger-Technosoft',
            'standard_id': 43,
            'serial_number': '3501009550',
            'no_sertifikat': '3501009550',
            'tertelusur_ke': 'SNSU-BSN',
            'terdaftar': true,
            'anggota': <dynamic>[],
          },
        ],
        'field': [
          {
            'kode': 'standar_dicek.*.dipakai',
            'label': 'Usage Check',
            'tipe': 'centang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'hasil_pengukuran',
        'grup': 'Data Result',
        'halaman': 1,
        'judul': 'Calibration Result for Temperature & Pressure',
        'field': [
          {
            'kode': 'set_point',
            'label': 'Set Point',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'judul': 'Calibration Result for Temperature & Pressure',
            'sumbu_pengulangan': 'kolom',
            'baris': [
              {
                'titik_ukur': 0.0,
                'label': 'Time',
                'tipe': 'jam',
              },
              {
                'titik_ukur': 0.0,
                'label': 'Temp. Disk 1',
                'satuan': '°C',
                'resolusi': 0.01,
                'desimal': 2,
                'pita': {
                  'min': 21.0,
                  'maks': 140.0,
                },
              },
              {
                'titik_ukur': 0.0,
                'label': 'Temp. Disk 2',
                'satuan': '°C',
                'resolusi': 0.01,
                'desimal': 2,
                'pita': {
                  'min': 21.0,
                  'maks': 140.0,
                },
              },
              {
                'titik_ukur': 0.0,
                'label': 'Temp. Disk 3',
                'satuan': '°C',
                'resolusi': 0.01,
                'desimal': 2,
                'pita': {
                  'min': 21.0,
                  'maks': 140.0,
                },
              },
              {
                'titik_ukur': 0.0,
                'label': 'Indikator Suhu',
                'satuan': '°C',
                'pita': {
                  'min': 21.0,
                  'maks': 140.0,
                },
              },
              {
                'titik_ukur': 0.0,
                'label': 'Indikator Pressure',
                'desimal': 3,
              },
              {
                'titik_ukur': 0.0,
                'label': 'Tekanan atm awal',
                'desimal': 3,
              },
              {
                'titik_ukur': 0.0,
                'label': 'Suhu Ruang',
                'satuan': '°C',
                'resolusi': 0.1,
                'desimal': 1,
                'pita': {
                  'min': 5.0,
                  'maks': 45.0,
                },
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'satuan': null,
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
              4,
              5,
            ],
          },
        ],
        'matriks': {
          'judul_kolom': 'Pengukuran Berulang UUT Selama Proses Sterilisasi',
          'titik_waktu': [
            1,
            2,
            3,
            4,
            5,
          ],
          'baris_waktu': {
            'kode': 'waktu',
            'label': 'Time',
            'tipe': 'jam',
            'format': 'HH:mm:ss',
            'kode_data': 'waktu',
          },
          'baris': [
            {
              'kode': 'disk_1',
              'label': 'Temp. Disk 1',
              'tipe': 'disk',
              'satuan': '°C',
              'kode_data': 'suhu.disk.0',
            },
            {
              'kode': 'disk_2',
              'label': 'Temp. Disk 2',
              'tipe': 'disk',
              'satuan': '°C',
              'kode_data': 'suhu.disk.1',
            },
            {
              'kode': 'disk_3',
              'label': 'Temp. Disk 3',
              'tipe': 'disk',
              'satuan': '°C',
              'kode_data': 'suhu.disk.2',
            },
            {
              'kode': 'indikator_suhu',
              'label': 'Indikator Suhu',
              'tipe': 'indikator_suhu',
              'satuan': '°C',
              'kode_data': 'suhu.indikator',
            },
            {
              'kode': 'indikator_pressure',
              'label': 'Indikator Pressure',
              'tipe': 'indikator_tekanan',
              'satuan': null,
              'satuan_dari': 'satuan_tekanan',
              'kurung_satuan': true,
              'kode_data': 'tekanan.indikator_pressure',
            },
            {
              'kode': 'tekanan_atm_awal',
              'label': 'Tekanan atm awal',
              'tipe': 'tekanan_atm',
              'satuan': null,
              'satuan_dari': 'satuan_tekanan',
              'kurung_satuan': true,
              'kode_data': 'tekanan.tekanan_atm_awal',
            },
            {
              'kode': 'suhu_ruang',
              'label': 'Suhu Ruang',
              'tipe': 'suhu_ruang',
              'satuan': '°C',
              'kode_data': 'suhu.suhu_ruang',
            },
          ],
        },
        'tabel_tekanan': {
          'label': 'Pressure Disk Logger — hasil unduh (Bar)',
          'di_luar_kertas': true,
          'catatan': 'Nggak ada di kertas: angkanya diunduh dari Pressure Disk Logger, bukan ditulis teknisi. Tanpa baris ini olah data tekanan nggak jalan.',
          'kolom': {
            'kode': 'tekanan.pembacaan_standar',
            'label': 'Standar Reading',
            'satuan': 'Bar',
          },
          'pengulangan': [
            1,
            2,
            3,
            4,
            5,
          ],
        },
        'field_di_luar_kertas': [
          {
            'kode': 'tekanan.uut_setting',
            'label': 'UUT Reading (dipakai hitung)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
            'di_luar_kertas': true,
            'satuan_dari': 'satuan_tekanan',
            'terisi_dari': 'tekanan.indikator_pressure',
            'catatan': 'Master INPUT_DATA nyimpen SATU UUT Reading, kertas nyediain lima kolom. Kalau kelima kolom Indikator Pressure isinya sama, angka itu yang kepakai; kalau beda, harus dipilih di sini — sistem nggak nebak.',
          },
          {
            'kode': 'display_tekanan',
            'label': 'Pressure Display Type',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'Digital',
                'label': 'Digital',
              },
              {
                'nilai': 'Analog 1',
                'label': 'Analog (rasio jarum:NST 1/2)',
              },
              {
                'nilai': 'Analog 2',
                'label': 'Analog (rasio jarum:NST 1/5)',
              },
              {
                'nilai': 'Analog 3',
                'label': 'Analog (rasio jarum:NST 1/10)',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
            'di_luar_kertas': true,
          },
        ],
      },
      {
        'kode': 'penutup',
        'grup': 'Data Result',
        'halaman': 1,
        'judul': 'Catatan:',
        'field': [
          {
            'kode': 'catatan_teknisi',
            'label': 'Catatan',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'teknisi.nama',
            'label': 'Calibrated by — Name',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'teknisi.tanda_tangan',
            'label': 'Calibrated by — Sign',
            'tipe': 'tanda_tangan',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'reviewer.nama',
            'label': 'Corrected by — Name',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'reviewer.tanda_tangan',
            'label': 'Corrected by — Sign',
            'tipe': 'tanda_tangan',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
    ],
    'untuk': 'teknisi',
  };
}
