/// Bentuk lembar kerja contoh **Enclosure** — Oven, Furnace, Bath, Inkubator,
/// dan Refrigerator.
///
/// DIGENERATE `docs/skrip/gen-contoh-lembar-kerja.php` di repo API — jangan
/// disunting tangan.
///
/// ## Kenapa kelimanya baru punya bentuk mock sekarang
///
/// Sampai 9 September 2026 kelimanya **jatuh ke bentuk pH** di mode mock, dan
/// nggak ada satu pun yang sadar: yang kegambar lembar pH tiga titik buffer,
/// tanpa error di mana pun. Yang menemukannya
/// `bentuk_mock_semua_profil_test.dart` — sapuan yang daftar profilnya diambil
/// dari registry server, bukan diketik tangan.
///
/// Kelima Enclosure yang paling berbahaya di daftar itu, dan alasannya bentuk
/// lembarnya: dia **GRID** (`grid_sensor` di tingkat atas, 9 termokopel x set
/// point), sementara bentuk pH nggak punya satu pun kotak yang cocok. Bukan
/// "sebagian kotaknya salah" — nggak ada yang cocok sama sekali.
///
/// ## Kelimanya SATU kertas dan SATU mesin hitung
///
/// `SIDIK-FM-CAL-0504_Rev.3` dipakai kelima profil, dan `EnclosureCalculator`
/// melayani kelimanya. Yang beda cuma judul & labelnya — itu sebabnya kelima
/// fungsi di bawah bentuknya nyaris identik, dan itu memang benar, bukan
/// salin-tempel yang kelupaan dirapikan.
///
/// `SemuaProfilLembarKerjaTest` di server MENGIZINKAN kelimanya berbagi satu
/// nomor formulir; pengecualian itu di-hardcode di sana berikut alasannya.
library;

/// Bentuk lembar kerja contoh **Oven**.
///
/// Kode profil `oven`, satuan `°C`, kertas `SIDIK-FM-CAL-0504_Rev.3`.
Map<String, dynamic> contohBentukLembarKerjaOven({
  bool untukAdmin = false,
}) {
  return {
    'kode_dokumen': 'SIDIK-FM-CAL-0504_Rev.3',
    'kode_metode': 'SIDIK-IK-CAL-0501_Rev.6',
    'judul': 'Calibration Worksheet - Enclosure (Oven)',
    'jumlah_pengulangan': 5,
    'satuan': '°C',
    'satuan_suhu': '°C',
    'semua_kolom_opsional': true,
    'catatan_pengisian': 'Tiap set point diisi GRID: 9 termokopel × 5 pembacaan, plus baris Indikator enclosure & Suhu Ruang. MERK KALIBRATOR (Constant/Yokogawa/Recorder) dan TIPE SENSOR (Type N/Type K) wajib dipilih — koreksi, drift, dan U95 beda per keduanya. Untuk kalibrator Recorder tiap termokopel juga wajib punya nomor Channel (CH1..CH20).',
    'grid_sensor': {
      'jumlah_sensor_saran': 9,
      'pengulangan': [
        1,
        2,
        3,
        4,
        5,
      ],
      'butuh_channel_untuk': 'recorder',
      'baris_indikator': true,
      'baris_suhu_ruang': true,
      'catatan_sensor_acuan': 'Sensor Acuan = termokopel bernomor TERKECIL yang terisi (keseragaman diukur relatif ke sensor itu). Urutan pengisian grid bebas — yang menentukan nomornya, bukan posisinya.',
    },
    'bagian': [
      {
        'kode': 'identitas_alat',
        'halaman': 1,
        'judul': 'Identitas Alat dan Data Customer',
        'field': [
          {
            'kode': 'equipment_id',
            'label': 'Nama Alat',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_alat',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'equipment.nama_alat',
            'label': 'Nama Alat (terpilih)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_merk',
            'label': 'Merk',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_model',
            'label': 'Type',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_serial_number',
            'label': 'No. Seri',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.rentang_ukur',
            'label': 'Rentang Ukur',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.kapasitas',
            'label': 'Kapasitas Alat',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.resolusi',
            'label': 'Resolusi Alat',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_terima',
            'label': 'Tgl. Diterima',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_kalibrasi',
            'label': 'Tgl. Kalibrasi',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'pemilik',
        'halaman': 1,
        'judul': 'Customer',
        'field': [
          {
            'kode': 'pemilik_nama',
            'label': 'Nama Customer',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'pemilik_alamat',
            'label': 'Alamat Customer',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'usage_check',
        'halaman': 1,
        'judul': 'Standar used',
        'baris': [
          {
            'label': 'Temperature Calibrator / Constant / 40T / 99875850',
            'standard_id': 44,
            'merk': 'Constant',
            'serial_number': '99875850',
            'no_sertifikat': '99875850',
            'tertelusur_ke': 'LK-202-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Temperature Calibrator / Yokogawa / CA 150 Handy Cal / 23P1005',
            'standard_id': 45,
            'merk': 'Yokogawa',
            'serial_number': '23P1005',
            'no_sertifikat': '23P1005',
            'tertelusur_ke': 'LK-202-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Temperature Calibrator / Victor / Victor 14+ / 992613877',
            'standard_id': null,
            'merk': null,
            'serial_number': null,
            'no_sertifikat': null,
            'tertelusur_ke': null,
            'terdaftar': false,
          },
          {
            'label': 'Temperature Recorder / Graptech / GL840-SDWV / C305B1470',
            'standard_id': 46,
            'merk': 'Graphtech',
            'serial_number': 'C305B1470',
            'no_sertifikat': 'C305B1470',
            'tertelusur_ke': 'LK-285-IDN',
            'terdaftar': true,
          },
        ],
        'field': [
          {
            'kode': 'standar_dicek.*.dipakai',
            'label': 'Dipakai',
            'tipe': 'centang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'standar_dicek.*.keterangan',
            'label': 'Keterangan',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'dimensi',
        'halaman': 1,
        'judul': 'Dimensi Alat',
        'field': [
          {
            'kode': 'dimensi_panjang',
            'label': 'Panjang (P)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'dimensi_lebar',
            'label': 'Lebar (L)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'dimensi_tinggi',
            'label': 'Tinggi (T)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'dimensi_jari_jari',
            'label': 'Jari-jari (r)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'dimensi_tinggi_silinder',
            'label': 'Tinggi silinder (T)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'dimensi.volume',
            'label': 'Volume',
            'tipe': 'angka',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': 'm³',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'persyaratan_alat',
            'label': 'Persyaratan Alat (ΔT)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'data_kalibrasi',
        'halaman': 1,
        'judul': 'CALIBRATION DATA',
        'field': [
          {
            'kode': 'tipe_sensor',
            'label': 'Temperature Type',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'Type N',
                'label': 'Type N',
              },
              {
                'nilai': 'Type K',
                'label': 'Type K',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi',
            'label': 'Location',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'lab',
                'label': 'Inlab',
              },
              {
                'nilai': 'onsite',
                'label': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi_nama',
            'label': 'Nama Tempat (Insitu)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'onsite',
              ],
            },
          },
          {
            'kode': 'room_id',
            'label': 'Ruangan (Inlab)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_ruangan',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'lab',
              ],
            },
          },
          {
            'kode': 'calibration_method_id',
            'label': 'Calibration Methode',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_metode',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'kondisi_lingkungan',
        'halaman': 1,
        'judul': 'Kondisi Lingkungan',
        'field': [
          {
            'kode': 'suhu_awal',
            'label': 'Suhu Ruangan — awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_akhir',
            'label': 'Suhu Ruangan — akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_awal',
            'label': 'Kelembapan — awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_akhir',
            'label': 'Kelembapan — akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'thermohygro_standard_id',
            'label': 'Thermohygro used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_thermohygro',
            'satuan': null,
            'pilihan': [
              {
                'nilai': '1',
                'label': 'TH-1',
                'grup': 'Inlab',
              },
              {
                'nilai': '3',
                'label': 'TH-3',
                'grup': 'Inlab',
              },
              {
                'nilai': '4',
                'label': 'TH-4',
                'grup': 'Inlab',
              },
              {
                'nilai': '5',
                'label': 'TH-5',
                'grup': 'Inlab',
              },
              {
                'nilai': '7',
                'label': 'TH-7',
                'grup': 'Inlab',
              },
              {
                'nilai': '2',
                'label': 'TH-2',
                'grup': 'Insitu',
              },
              {
                'nilai': '6',
                'label': 'TH-6',
                'grup': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'penutup',
        'halaman': 1,
        'judul': 'Catatan & Tanda Tangan',
        'field': [
          {
            'kode': 'catatan_teknisi',
            'label': 'Catatan',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'teknisi.nama',
            'label': 'Dikalibrasi Oleh',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'reviewer.nama',
            'label': 'Diperiksa Oleh',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
    ],
  };
}

/// Bentuk lembar kerja contoh **Furnace**.
///
/// Kode profil `furnace`, satuan `°C`, kertas `SIDIK-FM-CAL-0504_Rev.3`.
Map<String, dynamic> contohBentukLembarKerjaFurnace({
  bool untukAdmin = false,
}) {
  return {
    'kode_dokumen': 'SIDIK-FM-CAL-0504_Rev.3',
    'kode_metode': 'SIDIK-IK-CAL-0501_Rev.6',
    'judul': 'Calibration Worksheet - Enclosure (Furnace)',
    'jumlah_pengulangan': 5,
    'satuan': '°C',
    'satuan_suhu': '°C',
    'semua_kolom_opsional': true,
    'catatan_pengisian': 'Tiap set point diisi GRID: 9 termokopel × 5 pembacaan, plus baris Indikator enclosure & Suhu Ruang. MERK KALIBRATOR (Constant/Yokogawa/Recorder) dan TIPE SENSOR (Type N/Type K) wajib dipilih — koreksi, drift, dan U95 beda per keduanya. Untuk kalibrator Recorder tiap termokopel juga wajib punya nomor Channel (CH1..CH20).',
    'grid_sensor': {
      'jumlah_sensor_saran': 9,
      'pengulangan': [
        1,
        2,
        3,
        4,
        5,
      ],
      'butuh_channel_untuk': 'recorder',
      'baris_indikator': true,
      'baris_suhu_ruang': true,
      'catatan_sensor_acuan': 'Sensor Acuan = termokopel bernomor TERKECIL yang terisi (keseragaman diukur relatif ke sensor itu). Urutan pengisian grid bebas — yang menentukan nomornya, bukan posisinya.',
    },
    'bagian': [
      {
        'kode': 'identitas_alat',
        'halaman': 1,
        'judul': 'Identitas Alat dan Data Customer',
        'field': [
          {
            'kode': 'equipment_id',
            'label': 'Nama Alat',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_alat',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'equipment.nama_alat',
            'label': 'Nama Alat (terpilih)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_merk',
            'label': 'Merk',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_model',
            'label': 'Type',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_serial_number',
            'label': 'No. Seri',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.rentang_ukur',
            'label': 'Rentang Ukur',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.kapasitas',
            'label': 'Kapasitas Alat',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.resolusi',
            'label': 'Resolusi Alat',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_terima',
            'label': 'Tgl. Diterima',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_kalibrasi',
            'label': 'Tgl. Kalibrasi',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'pemilik',
        'halaman': 1,
        'judul': 'Customer',
        'field': [
          {
            'kode': 'pemilik_nama',
            'label': 'Nama Customer',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'pemilik_alamat',
            'label': 'Alamat Customer',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'usage_check',
        'halaman': 1,
        'judul': 'Standar used',
        'baris': [
          {
            'label': 'Temperature Calibrator / Constant / 40T / 99875850',
            'standard_id': 44,
            'merk': 'Constant',
            'serial_number': '99875850',
            'no_sertifikat': '99875850',
            'tertelusur_ke': 'LK-202-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Temperature Calibrator / Yokogawa / CA 150 Handy Cal / 23P1005',
            'standard_id': 45,
            'merk': 'Yokogawa',
            'serial_number': '23P1005',
            'no_sertifikat': '23P1005',
            'tertelusur_ke': 'LK-202-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Temperature Calibrator / Victor / Victor 14+ / 992613877',
            'standard_id': null,
            'merk': null,
            'serial_number': null,
            'no_sertifikat': null,
            'tertelusur_ke': null,
            'terdaftar': false,
          },
          {
            'label': 'Temperature Recorder / Graptech / GL840-SDWV / C305B1470',
            'standard_id': 46,
            'merk': 'Graphtech',
            'serial_number': 'C305B1470',
            'no_sertifikat': 'C305B1470',
            'tertelusur_ke': 'LK-285-IDN',
            'terdaftar': true,
          },
        ],
        'field': [
          {
            'kode': 'standar_dicek.*.dipakai',
            'label': 'Dipakai',
            'tipe': 'centang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'standar_dicek.*.keterangan',
            'label': 'Keterangan',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'dimensi',
        'halaman': 1,
        'judul': 'Dimensi Alat',
        'field': [
          {
            'kode': 'dimensi_panjang',
            'label': 'Panjang (P)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'dimensi_lebar',
            'label': 'Lebar (L)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'dimensi_tinggi',
            'label': 'Tinggi (T)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'dimensi_jari_jari',
            'label': 'Jari-jari (r)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'dimensi_tinggi_silinder',
            'label': 'Tinggi silinder (T)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'dimensi.volume',
            'label': 'Volume',
            'tipe': 'angka',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': 'm³',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'persyaratan_alat',
            'label': 'Persyaratan Alat (ΔT)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'data_kalibrasi',
        'halaman': 1,
        'judul': 'CALIBRATION DATA',
        'field': [
          {
            'kode': 'tipe_sensor',
            'label': 'Temperature Type',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'Type N',
                'label': 'Type N',
              },
              {
                'nilai': 'Type K',
                'label': 'Type K',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi',
            'label': 'Location',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'lab',
                'label': 'Inlab',
              },
              {
                'nilai': 'onsite',
                'label': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi_nama',
            'label': 'Nama Tempat (Insitu)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'onsite',
              ],
            },
          },
          {
            'kode': 'room_id',
            'label': 'Ruangan (Inlab)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_ruangan',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'lab',
              ],
            },
          },
          {
            'kode': 'calibration_method_id',
            'label': 'Calibration Methode',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_metode',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'kondisi_lingkungan',
        'halaman': 1,
        'judul': 'Kondisi Lingkungan',
        'field': [
          {
            'kode': 'suhu_awal',
            'label': 'Suhu Ruangan — awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_akhir',
            'label': 'Suhu Ruangan — akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_awal',
            'label': 'Kelembapan — awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_akhir',
            'label': 'Kelembapan — akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'thermohygro_standard_id',
            'label': 'Thermohygro used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_thermohygro',
            'satuan': null,
            'pilihan': [
              {
                'nilai': '1',
                'label': 'TH-1',
                'grup': 'Inlab',
              },
              {
                'nilai': '3',
                'label': 'TH-3',
                'grup': 'Inlab',
              },
              {
                'nilai': '4',
                'label': 'TH-4',
                'grup': 'Inlab',
              },
              {
                'nilai': '5',
                'label': 'TH-5',
                'grup': 'Inlab',
              },
              {
                'nilai': '7',
                'label': 'TH-7',
                'grup': 'Inlab',
              },
              {
                'nilai': '2',
                'label': 'TH-2',
                'grup': 'Insitu',
              },
              {
                'nilai': '6',
                'label': 'TH-6',
                'grup': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'penutup',
        'halaman': 1,
        'judul': 'Catatan & Tanda Tangan',
        'field': [
          {
            'kode': 'catatan_teknisi',
            'label': 'Catatan',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'teknisi.nama',
            'label': 'Dikalibrasi Oleh',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'reviewer.nama',
            'label': 'Diperiksa Oleh',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
    ],
  };
}

/// Bentuk lembar kerja contoh **Bath**.
///
/// Kode profil `bath`, satuan `°C`, kertas `SIDIK-FM-CAL-0504_Rev.3`.
Map<String, dynamic> contohBentukLembarKerjaBath({
  bool untukAdmin = false,
}) {
  return {
    'kode_dokumen': 'SIDIK-FM-CAL-0504_Rev.3',
    'kode_metode': 'SIDIK-IK-CAL-0501_Rev.6',
    'judul': 'Calibration Worksheet - Enclosure (Bath)',
    'jumlah_pengulangan': 5,
    'satuan': '°C',
    'satuan_suhu': '°C',
    'semua_kolom_opsional': true,
    'catatan_pengisian': 'Tiap set point diisi GRID: 9 termokopel × 5 pembacaan, plus baris Indikator enclosure & Suhu Ruang. MERK KALIBRATOR (Constant/Yokogawa/Recorder) dan TIPE SENSOR (Type N/Type K) wajib dipilih — koreksi, drift, dan U95 beda per keduanya. Untuk kalibrator Recorder tiap termokopel juga wajib punya nomor Channel (CH1..CH20).',
    'grid_sensor': {
      'jumlah_sensor_saran': 9,
      'pengulangan': [
        1,
        2,
        3,
        4,
        5,
      ],
      'butuh_channel_untuk': 'recorder',
      'baris_indikator': true,
      'baris_suhu_ruang': true,
      'catatan_sensor_acuan': 'Sensor Acuan = termokopel bernomor TERKECIL yang terisi (keseragaman diukur relatif ke sensor itu). Urutan pengisian grid bebas — yang menentukan nomornya, bukan posisinya.',
    },
    'bagian': [
      {
        'kode': 'identitas_alat',
        'halaman': 1,
        'judul': 'Identitas Alat dan Data Customer',
        'field': [
          {
            'kode': 'equipment_id',
            'label': 'Nama Alat',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_alat',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'equipment.nama_alat',
            'label': 'Nama Alat (terpilih)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_merk',
            'label': 'Merk',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_model',
            'label': 'Type',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_serial_number',
            'label': 'No. Seri',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.rentang_ukur',
            'label': 'Rentang Ukur',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.kapasitas',
            'label': 'Kapasitas Alat',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.resolusi',
            'label': 'Resolusi Alat',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_terima',
            'label': 'Tgl. Diterima',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_kalibrasi',
            'label': 'Tgl. Kalibrasi',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'pemilik',
        'halaman': 1,
        'judul': 'Customer',
        'field': [
          {
            'kode': 'pemilik_nama',
            'label': 'Nama Customer',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'pemilik_alamat',
            'label': 'Alamat Customer',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'usage_check',
        'halaman': 1,
        'judul': 'Standar used',
        'baris': [
          {
            'label': 'Temperature Calibrator / Constant / 40T / 99875850',
            'standard_id': 44,
            'merk': 'Constant',
            'serial_number': '99875850',
            'no_sertifikat': '99875850',
            'tertelusur_ke': 'LK-202-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Temperature Calibrator / Yokogawa / CA 150 Handy Cal / 23P1005',
            'standard_id': 45,
            'merk': 'Yokogawa',
            'serial_number': '23P1005',
            'no_sertifikat': '23P1005',
            'tertelusur_ke': 'LK-202-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Temperature Calibrator / Victor / Victor 14+ / 992613877',
            'standard_id': null,
            'merk': null,
            'serial_number': null,
            'no_sertifikat': null,
            'tertelusur_ke': null,
            'terdaftar': false,
          },
          {
            'label': 'Temperature Recorder / Graptech / GL840-SDWV / C305B1470',
            'standard_id': 46,
            'merk': 'Graphtech',
            'serial_number': 'C305B1470',
            'no_sertifikat': 'C305B1470',
            'tertelusur_ke': 'LK-285-IDN',
            'terdaftar': true,
          },
        ],
        'field': [
          {
            'kode': 'standar_dicek.*.dipakai',
            'label': 'Dipakai',
            'tipe': 'centang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'standar_dicek.*.keterangan',
            'label': 'Keterangan',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'dimensi',
        'halaman': 1,
        'judul': 'Dimensi Alat',
        'field': [
          {
            'kode': 'dimensi_panjang',
            'label': 'Panjang (P)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'dimensi_lebar',
            'label': 'Lebar (L)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'dimensi_tinggi',
            'label': 'Tinggi (T)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'dimensi_jari_jari',
            'label': 'Jari-jari (r)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'dimensi_tinggi_silinder',
            'label': 'Tinggi silinder (T)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'dimensi.volume',
            'label': 'Volume',
            'tipe': 'angka',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': 'm³',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'persyaratan_alat',
            'label': 'Persyaratan Alat (ΔT)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'data_kalibrasi',
        'halaman': 1,
        'judul': 'CALIBRATION DATA',
        'field': [
          {
            'kode': 'tipe_sensor',
            'label': 'Temperature Type',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'Type N',
                'label': 'Type N',
              },
              {
                'nilai': 'Type K',
                'label': 'Type K',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi',
            'label': 'Location',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'lab',
                'label': 'Inlab',
              },
              {
                'nilai': 'onsite',
                'label': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi_nama',
            'label': 'Nama Tempat (Insitu)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'onsite',
              ],
            },
          },
          {
            'kode': 'room_id',
            'label': 'Ruangan (Inlab)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_ruangan',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'lab',
              ],
            },
          },
          {
            'kode': 'calibration_method_id',
            'label': 'Calibration Methode',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_metode',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'kondisi_lingkungan',
        'halaman': 1,
        'judul': 'Kondisi Lingkungan',
        'field': [
          {
            'kode': 'suhu_awal',
            'label': 'Suhu Ruangan — awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_akhir',
            'label': 'Suhu Ruangan — akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_awal',
            'label': 'Kelembapan — awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_akhir',
            'label': 'Kelembapan — akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'thermohygro_standard_id',
            'label': 'Thermohygro used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_thermohygro',
            'satuan': null,
            'pilihan': [
              {
                'nilai': '1',
                'label': 'TH-1',
                'grup': 'Inlab',
              },
              {
                'nilai': '3',
                'label': 'TH-3',
                'grup': 'Inlab',
              },
              {
                'nilai': '4',
                'label': 'TH-4',
                'grup': 'Inlab',
              },
              {
                'nilai': '5',
                'label': 'TH-5',
                'grup': 'Inlab',
              },
              {
                'nilai': '7',
                'label': 'TH-7',
                'grup': 'Inlab',
              },
              {
                'nilai': '2',
                'label': 'TH-2',
                'grup': 'Insitu',
              },
              {
                'nilai': '6',
                'label': 'TH-6',
                'grup': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'penutup',
        'halaman': 1,
        'judul': 'Catatan & Tanda Tangan',
        'field': [
          {
            'kode': 'catatan_teknisi',
            'label': 'Catatan',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'teknisi.nama',
            'label': 'Dikalibrasi Oleh',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'reviewer.nama',
            'label': 'Diperiksa Oleh',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
    ],
  };
}

/// Bentuk lembar kerja contoh **Inkubator**.
///
/// Kode profil `inkubator`, satuan `°C`, kertas `SIDIK-FM-CAL-0504_Rev.3`.
Map<String, dynamic> contohBentukLembarKerjaInkubator({
  bool untukAdmin = false,
}) {
  return {
    'kode_dokumen': 'SIDIK-FM-CAL-0504_Rev.3',
    'kode_metode': 'SIDIK-IK-CAL-0501_Rev.6',
    'judul': 'Calibration Worksheet - Enclosure (Inkubator)',
    'jumlah_pengulangan': 5,
    'satuan': '°C',
    'satuan_suhu': '°C',
    'semua_kolom_opsional': true,
    'catatan_pengisian': 'Tiap set point diisi GRID: 9 termokopel × 5 pembacaan, plus baris Indikator enclosure & Suhu Ruang. MERK KALIBRATOR (Constant/Yokogawa/Recorder) dan TIPE SENSOR (Type N/Type K) wajib dipilih — koreksi, drift, dan U95 beda per keduanya. Untuk kalibrator Recorder tiap termokopel juga wajib punya nomor Channel (CH1..CH20).',
    'grid_sensor': {
      'jumlah_sensor_saran': 9,
      'pengulangan': [
        1,
        2,
        3,
        4,
        5,
      ],
      'butuh_channel_untuk': 'recorder',
      'baris_indikator': true,
      'baris_suhu_ruang': true,
      'catatan_sensor_acuan': 'Sensor Acuan = termokopel bernomor TERKECIL yang terisi (keseragaman diukur relatif ke sensor itu). Urutan pengisian grid bebas — yang menentukan nomornya, bukan posisinya.',
    },
    'bagian': [
      {
        'kode': 'identitas_alat',
        'halaman': 1,
        'judul': 'Identitas Alat dan Data Customer',
        'field': [
          {
            'kode': 'equipment_id',
            'label': 'Nama Alat',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_alat',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'equipment.nama_alat',
            'label': 'Nama Alat (terpilih)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_merk',
            'label': 'Merk',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_model',
            'label': 'Type',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_serial_number',
            'label': 'No. Seri',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.rentang_ukur',
            'label': 'Rentang Ukur',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.kapasitas',
            'label': 'Kapasitas Alat',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.resolusi',
            'label': 'Resolusi Alat',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_terima',
            'label': 'Tgl. Diterima',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_kalibrasi',
            'label': 'Tgl. Kalibrasi',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'pemilik',
        'halaman': 1,
        'judul': 'Customer',
        'field': [
          {
            'kode': 'pemilik_nama',
            'label': 'Nama Customer',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'pemilik_alamat',
            'label': 'Alamat Customer',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'usage_check',
        'halaman': 1,
        'judul': 'Standar used',
        'baris': [
          {
            'label': 'Temperature Calibrator / Constant / 40T / 99875850',
            'standard_id': 44,
            'merk': 'Constant',
            'serial_number': '99875850',
            'no_sertifikat': '99875850',
            'tertelusur_ke': 'LK-202-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Temperature Calibrator / Yokogawa / CA 150 Handy Cal / 23P1005',
            'standard_id': 45,
            'merk': 'Yokogawa',
            'serial_number': '23P1005',
            'no_sertifikat': '23P1005',
            'tertelusur_ke': 'LK-202-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Temperature Calibrator / Victor / Victor 14+ / 992613877',
            'standard_id': null,
            'merk': null,
            'serial_number': null,
            'no_sertifikat': null,
            'tertelusur_ke': null,
            'terdaftar': false,
          },
          {
            'label': 'Temperature Recorder / Graptech / GL840-SDWV / C305B1470',
            'standard_id': 46,
            'merk': 'Graphtech',
            'serial_number': 'C305B1470',
            'no_sertifikat': 'C305B1470',
            'tertelusur_ke': 'LK-285-IDN',
            'terdaftar': true,
          },
        ],
        'field': [
          {
            'kode': 'standar_dicek.*.dipakai',
            'label': 'Dipakai',
            'tipe': 'centang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'standar_dicek.*.keterangan',
            'label': 'Keterangan',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'dimensi',
        'halaman': 1,
        'judul': 'Dimensi Alat',
        'field': [
          {
            'kode': 'dimensi_panjang',
            'label': 'Panjang (P)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'dimensi_lebar',
            'label': 'Lebar (L)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'dimensi_tinggi',
            'label': 'Tinggi (T)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'dimensi_jari_jari',
            'label': 'Jari-jari (r)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'dimensi_tinggi_silinder',
            'label': 'Tinggi silinder (T)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'dimensi.volume',
            'label': 'Volume',
            'tipe': 'angka',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': 'm³',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'persyaratan_alat',
            'label': 'Persyaratan Alat (ΔT)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'data_kalibrasi',
        'halaman': 1,
        'judul': 'CALIBRATION DATA',
        'field': [
          {
            'kode': 'tipe_sensor',
            'label': 'Temperature Type',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'Type N',
                'label': 'Type N',
              },
              {
                'nilai': 'Type K',
                'label': 'Type K',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi',
            'label': 'Location',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'lab',
                'label': 'Inlab',
              },
              {
                'nilai': 'onsite',
                'label': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi_nama',
            'label': 'Nama Tempat (Insitu)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'onsite',
              ],
            },
          },
          {
            'kode': 'room_id',
            'label': 'Ruangan (Inlab)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_ruangan',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'lab',
              ],
            },
          },
          {
            'kode': 'calibration_method_id',
            'label': 'Calibration Methode',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_metode',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'kondisi_lingkungan',
        'halaman': 1,
        'judul': 'Kondisi Lingkungan',
        'field': [
          {
            'kode': 'suhu_awal',
            'label': 'Suhu Ruangan — awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_akhir',
            'label': 'Suhu Ruangan — akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_awal',
            'label': 'Kelembapan — awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_akhir',
            'label': 'Kelembapan — akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'thermohygro_standard_id',
            'label': 'Thermohygro used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_thermohygro',
            'satuan': null,
            'pilihan': [
              {
                'nilai': '1',
                'label': 'TH-1',
                'grup': 'Inlab',
              },
              {
                'nilai': '3',
                'label': 'TH-3',
                'grup': 'Inlab',
              },
              {
                'nilai': '4',
                'label': 'TH-4',
                'grup': 'Inlab',
              },
              {
                'nilai': '5',
                'label': 'TH-5',
                'grup': 'Inlab',
              },
              {
                'nilai': '7',
                'label': 'TH-7',
                'grup': 'Inlab',
              },
              {
                'nilai': '2',
                'label': 'TH-2',
                'grup': 'Insitu',
              },
              {
                'nilai': '6',
                'label': 'TH-6',
                'grup': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'penutup',
        'halaman': 1,
        'judul': 'Catatan & Tanda Tangan',
        'field': [
          {
            'kode': 'catatan_teknisi',
            'label': 'Catatan',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'teknisi.nama',
            'label': 'Dikalibrasi Oleh',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'reviewer.nama',
            'label': 'Diperiksa Oleh',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
    ],
  };
}

/// Bentuk lembar kerja contoh **Refrigerator**.
///
/// Kode profil `refrigerator`, satuan `°C`, kertas `SIDIK-FM-CAL-0504_Rev.3`.
Map<String, dynamic> contohBentukLembarKerjaRefrigerator({
  bool untukAdmin = false,
}) {
  return {
    'kode_dokumen': 'SIDIK-FM-CAL-0504_Rev.3',
    'kode_metode': 'SIDIK-IK-CAL-0501_Rev.6',
    'judul': 'Calibration Worksheet - Enclosure (Refrigerator)',
    'jumlah_pengulangan': 5,
    'satuan': '°C',
    'satuan_suhu': '°C',
    'semua_kolom_opsional': true,
    'catatan_pengisian': 'Tiap set point diisi GRID: 9 termokopel × 5 pembacaan, plus baris Indikator enclosure & Suhu Ruang. MERK KALIBRATOR (Constant/Yokogawa/Recorder) dan TIPE SENSOR (Type N/Type K) wajib dipilih — koreksi, drift, dan U95 beda per keduanya. Untuk kalibrator Recorder tiap termokopel juga wajib punya nomor Channel (CH1..CH20).',
    'grid_sensor': {
      'jumlah_sensor_saran': 9,
      'pengulangan': [
        1,
        2,
        3,
        4,
        5,
      ],
      'butuh_channel_untuk': 'recorder',
      'baris_indikator': true,
      'baris_suhu_ruang': true,
      'catatan_sensor_acuan': 'Sensor Acuan = termokopel bernomor TERKECIL yang terisi (keseragaman diukur relatif ke sensor itu). Urutan pengisian grid bebas — yang menentukan nomornya, bukan posisinya.',
    },
    'bagian': [
      {
        'kode': 'identitas_alat',
        'halaman': 1,
        'judul': 'Identitas Alat dan Data Customer',
        'field': [
          {
            'kode': 'equipment_id',
            'label': 'Nama Alat',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_alat',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'equipment.nama_alat',
            'label': 'Nama Alat (terpilih)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_merk',
            'label': 'Merk',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_model',
            'label': 'Type',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_serial_number',
            'label': 'No. Seri',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.rentang_ukur',
            'label': 'Rentang Ukur',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.kapasitas',
            'label': 'Kapasitas Alat',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.resolusi',
            'label': 'Resolusi Alat',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_terima',
            'label': 'Tgl. Diterima',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_kalibrasi',
            'label': 'Tgl. Kalibrasi',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'pemilik',
        'halaman': 1,
        'judul': 'Customer',
        'field': [
          {
            'kode': 'pemilik_nama',
            'label': 'Nama Customer',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'pemilik_alamat',
            'label': 'Alamat Customer',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'usage_check',
        'halaman': 1,
        'judul': 'Standar used',
        'baris': [
          {
            'label': 'Temperature Calibrator / Constant / 40T / 99875850',
            'standard_id': 44,
            'merk': 'Constant',
            'serial_number': '99875850',
            'no_sertifikat': '99875850',
            'tertelusur_ke': 'LK-202-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Temperature Calibrator / Yokogawa / CA 150 Handy Cal / 23P1005',
            'standard_id': 45,
            'merk': 'Yokogawa',
            'serial_number': '23P1005',
            'no_sertifikat': '23P1005',
            'tertelusur_ke': 'LK-202-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Temperature Calibrator / Victor / Victor 14+ / 992613877',
            'standard_id': null,
            'merk': null,
            'serial_number': null,
            'no_sertifikat': null,
            'tertelusur_ke': null,
            'terdaftar': false,
          },
          {
            'label': 'Temperature Recorder / Graptech / GL840-SDWV / C305B1470',
            'standard_id': 46,
            'merk': 'Graphtech',
            'serial_number': 'C305B1470',
            'no_sertifikat': 'C305B1470',
            'tertelusur_ke': 'LK-285-IDN',
            'terdaftar': true,
          },
        ],
        'field': [
          {
            'kode': 'standar_dicek.*.dipakai',
            'label': 'Dipakai',
            'tipe': 'centang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'standar_dicek.*.keterangan',
            'label': 'Keterangan',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'dimensi',
        'halaman': 1,
        'judul': 'Dimensi Alat',
        'field': [
          {
            'kode': 'dimensi_panjang',
            'label': 'Panjang (P)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'dimensi_lebar',
            'label': 'Lebar (L)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'dimensi_tinggi',
            'label': 'Tinggi (T)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'dimensi_jari_jari',
            'label': 'Jari-jari (r)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'dimensi_tinggi_silinder',
            'label': 'Tinggi silinder (T)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'dimensi.volume',
            'label': 'Volume',
            'tipe': 'angka',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': 'm³',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'persyaratan_alat',
            'label': 'Persyaratan Alat (ΔT)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'data_kalibrasi',
        'halaman': 1,
        'judul': 'CALIBRATION DATA',
        'field': [
          {
            'kode': 'tipe_sensor',
            'label': 'Temperature Type',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'Type N',
                'label': 'Type N',
              },
              {
                'nilai': 'Type K',
                'label': 'Type K',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi',
            'label': 'Location',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'lab',
                'label': 'Inlab',
              },
              {
                'nilai': 'onsite',
                'label': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi_nama',
            'label': 'Nama Tempat (Insitu)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'onsite',
              ],
            },
          },
          {
            'kode': 'room_id',
            'label': 'Ruangan (Inlab)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_ruangan',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'lab',
              ],
            },
          },
          {
            'kode': 'calibration_method_id',
            'label': 'Calibration Methode',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_metode',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'kondisi_lingkungan',
        'halaman': 1,
        'judul': 'Kondisi Lingkungan',
        'field': [
          {
            'kode': 'suhu_awal',
            'label': 'Suhu Ruangan — awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_akhir',
            'label': 'Suhu Ruangan — akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_awal',
            'label': 'Kelembapan — awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_akhir',
            'label': 'Kelembapan — akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'thermohygro_standard_id',
            'label': 'Thermohygro used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_thermohygro',
            'satuan': null,
            'pilihan': [
              {
                'nilai': '1',
                'label': 'TH-1',
                'grup': 'Inlab',
              },
              {
                'nilai': '3',
                'label': 'TH-3',
                'grup': 'Inlab',
              },
              {
                'nilai': '4',
                'label': 'TH-4',
                'grup': 'Inlab',
              },
              {
                'nilai': '5',
                'label': 'TH-5',
                'grup': 'Inlab',
              },
              {
                'nilai': '7',
                'label': 'TH-7',
                'grup': 'Inlab',
              },
              {
                'nilai': '2',
                'label': 'TH-2',
                'grup': 'Insitu',
              },
              {
                'nilai': '6',
                'label': 'TH-6',
                'grup': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'penutup',
        'halaman': 1,
        'judul': 'Catatan & Tanda Tangan',
        'field': [
          {
            'kode': 'catatan_teknisi',
            'label': 'Catatan',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'teknisi.nama',
            'label': 'Dikalibrasi Oleh',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'reviewer.nama',
            'label': 'Diperiksa Oleh',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
    ],
  };
}
