/// Bentuk lembar kerja contoh keluarga **PISTON VOLUME** — Piston Pipette,
/// Dispensett, Buret Digital (kertas FM-0528 one mark / FM-0529 graduated).
///
/// Yang HARUS diperhatikan HP, karena salah satu dari ini tidak menghasilkan
/// error apa pun:
///
///  1. **Tabel `measurements[].piston_kumulatif` berisi massa KUMULATIF**
///     M0..M10 (label dari `pengulangan_arah`). Tabel ini membawa
///     `kumulatif: true`: tampilkan SELISIH `M_i − M_{i−1}` di bawah tiap
///     kotak (`TabelHasil.kumulatif` + `_SelisihKumulatif`). Satu digit salah
///     di M1..M9 menggeser dua selisih berlawanan arah — rata-ratanya tidak
///     berubah sama sekali, cuma STDEV yang membengkak.
///  2. **Tabel `measurements[].piston_suhu_air`** — suhu awal & akhir per
///     titik, barisnya sinkron dengan tabel kumulatif.
///  3. **`spesifikasi_alat.piston.keluarga`** — `fixed` isi Titik 1 saja;
///     `graduated` isi MIN, MID, MAX.
///  4. **Tekanan udara (`tekanan_awal`/`tekanan_akhir`, hPa) WAJIB** — masuk
///     densitas udara, dan kertas lamanya belum punya kotak itu.
library;

/// Bentuk lembar kerja contoh **Piston Pipette**.
///
/// Kode profil `piston_pipette`, satuan `-`, kertas `SIDIK-FM-CAL-0529_Rev.3`.
Map<String, dynamic> contohBentukLembarKerjaPistonPipette({
  bool untukAdmin = false,
}) {
  return {
    'kode_dokumen': 'SIDIK-FM-CAL-0529_Rev.3',
    'kode_metode': 'SIDIK-IK-CAL-0522_Rev.5',
    'nomor_lingkup': 'LK-285-IDN',
    'judul': 'Calibration Worksheet - Piston Volume',
    'jumlah_pengulangan': 10,
    'semua_kolom_opsional': false,
    'catatan_pengisian': 'Tulis massa KUMULATIF di timbangan (M0 = tara, M1..M10 sesudah tiap pemindahan) — sistem yang menghitung selisihnya. Volume tetap: isi Titik 1 saja. Graduated: isi MIN, MID, MAX, masing-masing dengan suhu air awal & akhirnya. Tekanan udara (hPa) WAJIB: masuk densitas udara.',
    'budget_ketidakpastian': {
      'tersedia': true,
      'sumber': 'Master Olah Data Fixed/Graduated Piston Volume, PERHITUNGAN & PERHITUNGAN U95%',
      'catatan': 'Tujuh komponen dengan koefisien sensitivitas turunan parsial V20, k dari t-Student dengan v_eff dipotong ke bawah, lantai CMC lampiran LK-285-IDN.',
    },
    'bagian': [
      {
        'kode': 'identitas_alat',
        'halaman': 1,
        'judul': 'Equipment Identity',
        'field': [
          {
            'kode': 'equipment_id',
            'label': 'Pilih Alat',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_alat',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_model',
            'label': 'Model/Type',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_merk',
            'label': 'Manufacture',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_serial_number',
            'label': 'Serial Number',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.piston.keluarga',
            'label': 'Keluarga alat',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'fixed',
                'label': 'Volume tetap — One Mark (FM-0528)',
              },
              {
                'nilai': 'graduated',
                'label': 'Dapat diatur — Graduated (FM-0529)',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
            'mempengaruhi_ketidakpastian': true,
          },
          {
            'kode': 'spesifikasi_alat.piston.kapasitas',
            'label': 'Capacity',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
            'mempengaruhi_ketidakpastian': true,
          },
          {
            'kode': 'spesifikasi_alat.piston.satuan',
            'label': 'Satuan',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              'ml',
              'µl',
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'pemilik',
        'halaman': 1,
        'judul': 'Owner',
        'field': [
          {
            'kode': 'pemilik_nama',
            'label': 'Name',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'pemilik_alamat',
            'label': 'Address',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_awal',
            'label': 'Env. Condition — First (°C)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_akhir',
            'label': 'Env. Condition — End (°C)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_awal',
            'label': 'Env. Condition — First (%RH)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_akhir',
            'label': 'Env. Condition — End (%RH)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tekanan_awal',
            'label': 'Tekanan Udara — First (hPa)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'hPa',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
            'mempengaruhi_ketidakpastian': true,
          },
          {
            'kode': 'tekanan_akhir',
            'label': 'Tekanan Udara — End (hPa)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'hPa',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
            'mempengaruhi_ketidakpastian': true,
          },
          {
            'kode': 'lokasi',
            'label': 'Location',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'lab',
                'label': 'Inlab',
              },
              {
                'nilai': 'onsite',
                'label': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'room_id',
            'label': 'Ruangan (Inlab)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_ruangan',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'lab',
              ],
            },
          },
          {
            'kode': 'lokasi_nama',
            'label': 'Nama Tempat (Insitu)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'onsite',
              ],
            },
          },
          {
            'kode': 'thermohygro_standard_id',
            'label': 'Thermohygro Used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_thermohygro',
            'satuan': null,
            'pilihan': [
              {
                'nilai': '1',
                'label': 'TH-1',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '2',
                'label': 'TH-2',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '3',
                'label': 'TH-3',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '4',
                'label': 'TH-4',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '5',
                'label': 'TH-5',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '6',
                'label': 'TH-6',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '7',
                'label': 'TH-7',
                'grup': 'Thermohygro lab',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'usage_check',
        'halaman': 1,
        'judul': 'Standard',
        'baris': [
          {
            'label': 'Timbangan Excellent/HSEX1403752',
            'standard_id': 78,
            'serial_number': 'HSEX1403752',
            'no_sertifikat': 'HSEX1403752',
            'tertelusur_ke': 'LK-305-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Timbangan Mettler Toledo/1129063525',
            'standard_id': 76,
            'serial_number': '1129063525',
            'no_sertifikat': '1129063525',
            'tertelusur_ke': 'LK-305-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Timbangan Fujitsu FSR-A/SIDIK/134/2024',
            'standard_id': 77,
            'serial_number': 'SIDIK/134/2024',
            'no_sertifikat': 'SIDIK/134/2024',
            'tertelusur_ke': 'LK-305-IDN',
            'terdaftar': true,
          },
          {
            'label': 'RTD Sensor/SH1/20',
            'standard_id': 48,
            'serial_number': 'SH1/20',
            'no_sertifikat': 'SH1/20',
            'tertelusur_ke': 'SNSU-BSN',
            'terdaftar': true,
          },
          {
            'label': 'Temp. Calibrator Constant',
            'standard_id': 44,
            'serial_number': '99875850',
            'no_sertifikat': '99875850',
            'tertelusur_ke': 'LK-202-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Temp. Calibrator Yokogawa',
            'standard_id': 45,
            'serial_number': '23P1005',
            'no_sertifikat': '23P1005',
            'tertelusur_ke': 'LK-202-IDN',
            'terdaftar': true,
          },
        ],
        'field': [
          {
            'kode': 'spesifikasi_alat.piston.timbangan',
            'label': 'Timbangan',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              'Analytical Balance',
              'Electronic Balance Excellent',
              'Electronic Balance Fujitsu',
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
            'mempengaruhi_ketidakpastian': true,
          },
        ],
      },
      {
        'kode': 'hasil',
        'halaman': 2,
        'judul': 'Reading of Weighing Result',
        'field': <dynamic>[],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'piston_kumulatif',
            'offset_kunci': 1000,
            'judul': 'Weight of Content — massa KUMULATIF (gram)',
            'judul_nilai': 'Nominal UUT',
            'judul_pengulangan': 'M',
            'titik_bisa_diubah': false,
            'simpan_ke': 'measurements[].piston_kumulatif',
            'kumulatif': true,
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1 / MIN',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'MID',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'MAX',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Massa (g)',
                'tipe': 'angka',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
            ],
            'pengulangan_arah': [
              {
                'ke': 1,
                'label': 'M0',
              },
              {
                'ke': 2,
                'label': 'M1',
              },
              {
                'ke': 3,
                'label': 'M2',
              },
              {
                'ke': 4,
                'label': 'M3',
              },
              {
                'ke': 5,
                'label': 'M4',
              },
              {
                'ke': 6,
                'label': 'M5',
              },
              {
                'ke': 7,
                'label': 'M6',
              },
              {
                'ke': 8,
                'label': 'M7',
              },
              {
                'ke': 9,
                'label': 'M8',
              },
              {
                'ke': 10,
                'label': 'M9',
              },
              {
                'ke': 11,
                'label': 'M10',
              },
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'piston_suhu_air',
            'offset_kunci': 2000,
            'judul': 'Suhu Air Destilasi (°C)',
            'judul_nilai': 'Nominal UUT',
            'judul_pengulangan': 'Suhu',
            'titik_bisa_diubah': false,
            'simpan_ke': 'measurements[].piston_suhu_air',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1 / MIN',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'MID',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'MAX',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Suhu (°C)',
                'tipe': 'angka',
              },
            ],
            'pengulangan': [
              1,
              2,
            ],
            'pengulangan_arah': [
              {
                'ke': 1,
                'label': 'Awal',
              },
              {
                'ke': 2,
                'label': 'Akhir',
              },
            ],
          },
        ],
      },
      {
        'kode': 'penutup',
        'halaman': 2,
        'judul': 'Catatan & Tanda Tangan',
        'field': [
          {
            'kode': 'catatan_teknisi',
            'label': 'Catatan',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'teknisi.nama',
            'label': 'Calibrated by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'reviewer.nama',
            'label': 'Checked by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
    ],
  };
}

/// Bentuk lembar kerja contoh **Dispensett**.
///
/// Kode profil `dispensett`, satuan `-`, kertas `SIDIK-FM-CAL-0529_Rev.3`.
Map<String, dynamic> contohBentukLembarKerjaDispensett({
  bool untukAdmin = false,
}) {
  return {
    'kode_dokumen': 'SIDIK-FM-CAL-0529_Rev.3',
    'kode_metode': 'SIDIK-IK-CAL-0522_Rev.5',
    'nomor_lingkup': 'LK-285-IDN',
    'judul': 'Calibration Worksheet - Piston Volume',
    'jumlah_pengulangan': 10,
    'semua_kolom_opsional': false,
    'catatan_pengisian': 'Tulis massa KUMULATIF di timbangan (M0 = tara, M1..M10 sesudah tiap pemindahan) — sistem yang menghitung selisihnya. Volume tetap: isi Titik 1 saja. Graduated: isi MIN, MID, MAX, masing-masing dengan suhu air awal & akhirnya. Tekanan udara (hPa) WAJIB: masuk densitas udara.',
    'budget_ketidakpastian': {
      'tersedia': true,
      'sumber': 'Master Olah Data Fixed/Graduated Piston Volume, PERHITUNGAN & PERHITUNGAN U95%',
      'catatan': 'Tujuh komponen dengan koefisien sensitivitas turunan parsial V20, k dari t-Student dengan v_eff dipotong ke bawah, lantai CMC lampiran LK-285-IDN.',
    },
    'bagian': [
      {
        'kode': 'identitas_alat',
        'halaman': 1,
        'judul': 'Equipment Identity',
        'field': [
          {
            'kode': 'equipment_id',
            'label': 'Pilih Alat',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_alat',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_model',
            'label': 'Model/Type',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_merk',
            'label': 'Manufacture',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_serial_number',
            'label': 'Serial Number',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.piston.keluarga',
            'label': 'Keluarga alat',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'fixed',
                'label': 'Volume tetap — One Mark (FM-0528)',
              },
              {
                'nilai': 'graduated',
                'label': 'Dapat diatur — Graduated (FM-0529)',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
            'mempengaruhi_ketidakpastian': true,
          },
          {
            'kode': 'spesifikasi_alat.piston.kapasitas',
            'label': 'Capacity',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
            'mempengaruhi_ketidakpastian': true,
          },
          {
            'kode': 'spesifikasi_alat.piston.satuan',
            'label': 'Satuan',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              'ml',
              'µl',
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.piston.sub_jenis',
            'label': 'Sub-jenis',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'single_stroke',
                'label': 'Single Stroke (output diatur alat)',
              },
              {
                'nilai': 'multi_stroke',
                'label': 'Multi Stroke (output diatur pengguna)',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
            'mempengaruhi_ketidakpastian': true,
          },
        ],
      },
      {
        'kode': 'pemilik',
        'halaman': 1,
        'judul': 'Owner',
        'field': [
          {
            'kode': 'pemilik_nama',
            'label': 'Name',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'pemilik_alamat',
            'label': 'Address',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_awal',
            'label': 'Env. Condition — First (°C)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_akhir',
            'label': 'Env. Condition — End (°C)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_awal',
            'label': 'Env. Condition — First (%RH)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_akhir',
            'label': 'Env. Condition — End (%RH)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tekanan_awal',
            'label': 'Tekanan Udara — First (hPa)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'hPa',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
            'mempengaruhi_ketidakpastian': true,
          },
          {
            'kode': 'tekanan_akhir',
            'label': 'Tekanan Udara — End (hPa)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'hPa',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
            'mempengaruhi_ketidakpastian': true,
          },
          {
            'kode': 'lokasi',
            'label': 'Location',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'lab',
                'label': 'Inlab',
              },
              {
                'nilai': 'onsite',
                'label': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'room_id',
            'label': 'Ruangan (Inlab)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_ruangan',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'lab',
              ],
            },
          },
          {
            'kode': 'lokasi_nama',
            'label': 'Nama Tempat (Insitu)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'onsite',
              ],
            },
          },
          {
            'kode': 'thermohygro_standard_id',
            'label': 'Thermohygro Used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_thermohygro',
            'satuan': null,
            'pilihan': [
              {
                'nilai': '1',
                'label': 'TH-1',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '2',
                'label': 'TH-2',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '3',
                'label': 'TH-3',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '4',
                'label': 'TH-4',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '5',
                'label': 'TH-5',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '6',
                'label': 'TH-6',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '7',
                'label': 'TH-7',
                'grup': 'Thermohygro lab',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'usage_check',
        'halaman': 1,
        'judul': 'Standard',
        'baris': [
          {
            'label': 'Timbangan Excellent/HSEX1403752',
            'standard_id': 78,
            'serial_number': 'HSEX1403752',
            'no_sertifikat': 'HSEX1403752',
            'tertelusur_ke': 'LK-305-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Timbangan Mettler Toledo/1129063525',
            'standard_id': 76,
            'serial_number': '1129063525',
            'no_sertifikat': '1129063525',
            'tertelusur_ke': 'LK-305-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Timbangan Fujitsu FSR-A/SIDIK/134/2024',
            'standard_id': 77,
            'serial_number': 'SIDIK/134/2024',
            'no_sertifikat': 'SIDIK/134/2024',
            'tertelusur_ke': 'LK-305-IDN',
            'terdaftar': true,
          },
          {
            'label': 'RTD Sensor/SH1/20',
            'standard_id': 48,
            'serial_number': 'SH1/20',
            'no_sertifikat': 'SH1/20',
            'tertelusur_ke': 'SNSU-BSN',
            'terdaftar': true,
          },
          {
            'label': 'Temp. Calibrator Constant',
            'standard_id': 44,
            'serial_number': '99875850',
            'no_sertifikat': '99875850',
            'tertelusur_ke': 'LK-202-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Temp. Calibrator Yokogawa',
            'standard_id': 45,
            'serial_number': '23P1005',
            'no_sertifikat': '23P1005',
            'tertelusur_ke': 'LK-202-IDN',
            'terdaftar': true,
          },
        ],
        'field': [
          {
            'kode': 'spesifikasi_alat.piston.timbangan',
            'label': 'Timbangan',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              'Analytical Balance',
              'Electronic Balance Excellent',
              'Electronic Balance Fujitsu',
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
            'mempengaruhi_ketidakpastian': true,
          },
        ],
      },
      {
        'kode': 'hasil',
        'halaman': 2,
        'judul': 'Reading of Weighing Result',
        'field': <dynamic>[],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'piston_kumulatif',
            'offset_kunci': 1000,
            'judul': 'Weight of Content — massa KUMULATIF (gram)',
            'judul_nilai': 'Nominal UUT',
            'judul_pengulangan': 'M',
            'titik_bisa_diubah': false,
            'simpan_ke': 'measurements[].piston_kumulatif',
            'kumulatif': true,
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1 / MIN',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'MID',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'MAX',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Massa (g)',
                'tipe': 'angka',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
            ],
            'pengulangan_arah': [
              {
                'ke': 1,
                'label': 'M0',
              },
              {
                'ke': 2,
                'label': 'M1',
              },
              {
                'ke': 3,
                'label': 'M2',
              },
              {
                'ke': 4,
                'label': 'M3',
              },
              {
                'ke': 5,
                'label': 'M4',
              },
              {
                'ke': 6,
                'label': 'M5',
              },
              {
                'ke': 7,
                'label': 'M6',
              },
              {
                'ke': 8,
                'label': 'M7',
              },
              {
                'ke': 9,
                'label': 'M8',
              },
              {
                'ke': 10,
                'label': 'M9',
              },
              {
                'ke': 11,
                'label': 'M10',
              },
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'piston_suhu_air',
            'offset_kunci': 2000,
            'judul': 'Suhu Air Destilasi (°C)',
            'judul_nilai': 'Nominal UUT',
            'judul_pengulangan': 'Suhu',
            'titik_bisa_diubah': false,
            'simpan_ke': 'measurements[].piston_suhu_air',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1 / MIN',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'MID',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'MAX',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Suhu (°C)',
                'tipe': 'angka',
              },
            ],
            'pengulangan': [
              1,
              2,
            ],
            'pengulangan_arah': [
              {
                'ke': 1,
                'label': 'Awal',
              },
              {
                'ke': 2,
                'label': 'Akhir',
              },
            ],
          },
        ],
      },
      {
        'kode': 'penutup',
        'halaman': 2,
        'judul': 'Catatan & Tanda Tangan',
        'field': [
          {
            'kode': 'catatan_teknisi',
            'label': 'Catatan',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'teknisi.nama',
            'label': 'Calibrated by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'reviewer.nama',
            'label': 'Checked by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
    ],
  };
}

/// Bentuk lembar kerja contoh **Buret Digital**.
///
/// Kode profil `buret_digital`, satuan `-`, kertas `SIDIK-FM-CAL-0529_Rev.3`.
Map<String, dynamic> contohBentukLembarKerjaBuretDigital({
  bool untukAdmin = false,
}) {
  return {
    'kode_dokumen': 'SIDIK-FM-CAL-0529_Rev.3',
    'kode_metode': 'SIDIK-IK-CAL-0522_Rev.5',
    'nomor_lingkup': 'LK-285-IDN',
    'judul': 'Calibration Worksheet - Piston Volume',
    'jumlah_pengulangan': 10,
    'semua_kolom_opsional': false,
    'catatan_pengisian': 'Tulis massa KUMULATIF di timbangan (M0 = tara, M1..M10 sesudah tiap pemindahan) — sistem yang menghitung selisihnya. Volume tetap: isi Titik 1 saja. Graduated: isi MIN, MID, MAX, masing-masing dengan suhu air awal & akhirnya. Tekanan udara (hPa) WAJIB: masuk densitas udara.',
    'budget_ketidakpastian': {
      'tersedia': true,
      'sumber': 'Master Olah Data Fixed/Graduated Piston Volume, PERHITUNGAN & PERHITUNGAN U95%',
      'catatan': 'Tujuh komponen dengan koefisien sensitivitas turunan parsial V20, k dari t-Student dengan v_eff dipotong ke bawah, lantai CMC lampiran LK-285-IDN.',
    },
    'bagian': [
      {
        'kode': 'identitas_alat',
        'halaman': 1,
        'judul': 'Equipment Identity',
        'field': [
          {
            'kode': 'equipment_id',
            'label': 'Pilih Alat',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_alat',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_model',
            'label': 'Model/Type',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_merk',
            'label': 'Manufacture',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_serial_number',
            'label': 'Serial Number',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.piston.keluarga',
            'label': 'Keluarga alat',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'fixed',
                'label': 'Volume tetap — One Mark (FM-0528)',
              },
              {
                'nilai': 'graduated',
                'label': 'Dapat diatur — Graduated (FM-0529)',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
            'mempengaruhi_ketidakpastian': true,
          },
          {
            'kode': 'spesifikasi_alat.piston.kapasitas',
            'label': 'Capacity',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
            'mempengaruhi_ketidakpastian': true,
          },
          {
            'kode': 'spesifikasi_alat.piston.satuan',
            'label': 'Satuan',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              'ml',
              'µl',
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.piston.sub_jenis',
            'label': 'Sub-jenis',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'hand_driven',
                'label': 'Hand Driven',
              },
              {
                'nilai': 'motor_driven',
                'label': 'Motor Driven',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
            'mempengaruhi_ketidakpastian': true,
          },
        ],
      },
      {
        'kode': 'pemilik',
        'halaman': 1,
        'judul': 'Owner',
        'field': [
          {
            'kode': 'pemilik_nama',
            'label': 'Name',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'pemilik_alamat',
            'label': 'Address',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_awal',
            'label': 'Env. Condition — First (°C)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_akhir',
            'label': 'Env. Condition — End (°C)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_awal',
            'label': 'Env. Condition — First (%RH)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_akhir',
            'label': 'Env. Condition — End (%RH)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tekanan_awal',
            'label': 'Tekanan Udara — First (hPa)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'hPa',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
            'mempengaruhi_ketidakpastian': true,
          },
          {
            'kode': 'tekanan_akhir',
            'label': 'Tekanan Udara — End (hPa)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'hPa',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
            'mempengaruhi_ketidakpastian': true,
          },
          {
            'kode': 'lokasi',
            'label': 'Location',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'lab',
                'label': 'Inlab',
              },
              {
                'nilai': 'onsite',
                'label': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'room_id',
            'label': 'Ruangan (Inlab)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_ruangan',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'lab',
              ],
            },
          },
          {
            'kode': 'lokasi_nama',
            'label': 'Nama Tempat (Insitu)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'onsite',
              ],
            },
          },
          {
            'kode': 'thermohygro_standard_id',
            'label': 'Thermohygro Used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_thermohygro',
            'satuan': null,
            'pilihan': [
              {
                'nilai': '1',
                'label': 'TH-1',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '2',
                'label': 'TH-2',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '3',
                'label': 'TH-3',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '4',
                'label': 'TH-4',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '5',
                'label': 'TH-5',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '6',
                'label': 'TH-6',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '7',
                'label': 'TH-7',
                'grup': 'Thermohygro lab',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'usage_check',
        'halaman': 1,
        'judul': 'Standard',
        'baris': [
          {
            'label': 'Timbangan Excellent/HSEX1403752',
            'standard_id': 78,
            'serial_number': 'HSEX1403752',
            'no_sertifikat': 'HSEX1403752',
            'tertelusur_ke': 'LK-305-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Timbangan Mettler Toledo/1129063525',
            'standard_id': 76,
            'serial_number': '1129063525',
            'no_sertifikat': '1129063525',
            'tertelusur_ke': 'LK-305-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Timbangan Fujitsu FSR-A/SIDIK/134/2024',
            'standard_id': 77,
            'serial_number': 'SIDIK/134/2024',
            'no_sertifikat': 'SIDIK/134/2024',
            'tertelusur_ke': 'LK-305-IDN',
            'terdaftar': true,
          },
          {
            'label': 'RTD Sensor/SH1/20',
            'standard_id': 48,
            'serial_number': 'SH1/20',
            'no_sertifikat': 'SH1/20',
            'tertelusur_ke': 'SNSU-BSN',
            'terdaftar': true,
          },
          {
            'label': 'Temp. Calibrator Constant',
            'standard_id': 44,
            'serial_number': '99875850',
            'no_sertifikat': '99875850',
            'tertelusur_ke': 'LK-202-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Temp. Calibrator Yokogawa',
            'standard_id': 45,
            'serial_number': '23P1005',
            'no_sertifikat': '23P1005',
            'tertelusur_ke': 'LK-202-IDN',
            'terdaftar': true,
          },
        ],
        'field': [
          {
            'kode': 'spesifikasi_alat.piston.timbangan',
            'label': 'Timbangan',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              'Analytical Balance',
              'Electronic Balance Excellent',
              'Electronic Balance Fujitsu',
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
            'mempengaruhi_ketidakpastian': true,
          },
        ],
      },
      {
        'kode': 'hasil',
        'halaman': 2,
        'judul': 'Reading of Weighing Result',
        'field': <dynamic>[],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'piston_kumulatif',
            'offset_kunci': 1000,
            'judul': 'Weight of Content — massa KUMULATIF (gram)',
            'judul_nilai': 'Nominal UUT',
            'judul_pengulangan': 'M',
            'titik_bisa_diubah': false,
            'simpan_ke': 'measurements[].piston_kumulatif',
            'kumulatif': true,
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1 / MIN',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'MID',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'MAX',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Massa (g)',
                'tipe': 'angka',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
            ],
            'pengulangan_arah': [
              {
                'ke': 1,
                'label': 'M0',
              },
              {
                'ke': 2,
                'label': 'M1',
              },
              {
                'ke': 3,
                'label': 'M2',
              },
              {
                'ke': 4,
                'label': 'M3',
              },
              {
                'ke': 5,
                'label': 'M4',
              },
              {
                'ke': 6,
                'label': 'M5',
              },
              {
                'ke': 7,
                'label': 'M6',
              },
              {
                'ke': 8,
                'label': 'M7',
              },
              {
                'ke': 9,
                'label': 'M8',
              },
              {
                'ke': 10,
                'label': 'M9',
              },
              {
                'ke': 11,
                'label': 'M10',
              },
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'piston_suhu_air',
            'offset_kunci': 2000,
            'judul': 'Suhu Air Destilasi (°C)',
            'judul_nilai': 'Nominal UUT',
            'judul_pengulangan': 'Suhu',
            'titik_bisa_diubah': false,
            'simpan_ke': 'measurements[].piston_suhu_air',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1 / MIN',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'MID',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'MAX',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Suhu (°C)',
                'tipe': 'angka',
              },
            ],
            'pengulangan': [
              1,
              2,
            ],
            'pengulangan_arah': [
              {
                'ke': 1,
                'label': 'Awal',
              },
              {
                'ke': 2,
                'label': 'Akhir',
              },
            ],
          },
        ],
      },
      {
        'kode': 'penutup',
        'halaman': 2,
        'judul': 'Catatan & Tanda Tangan',
        'field': [
          {
            'kode': 'catatan_teknisi',
            'label': 'Catatan',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'teknisi.nama',
            'label': 'Calibrated by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'reviewer.nama',
            'label': 'Checked by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
    ],
  };
}
