/// Bentuk lembar kerja contoh **Gaya** — Mesin UTM, Load Cell, Proving Ring
/// (alat ke-40, 41, 42).
///
/// DIGENERATE `docs/skrip/gen-contoh-lembar-kerja.php` di repo API — jangan
/// disunting tangan.
///
/// ## Kenapa berkas ini baru ada 25 Sep 2026
///
/// Ketiga alat Gaya mendarat di server tanpa satu pun bentuk contoh di HP, jadi
/// nol test yang pernah menyusun payload Gaya dari definisi lembarnya. Chaos
/// review hari itu menemukan akibatnya: tabel Preload ber-`simpan_ke`
/// `spesifikasi_alat.gaya` menimpa seluruh blok spesifikasi — satuan, standar,
/// kapasitas, misalignment — di tiap kiriman, dan tidak satu sesi Gaya pun dari
/// HP pernah terhitung. Sekarang `simpan_ke`-nya `spesifikasi_alat.gaya.preload`.
///
///  1. **Tabel deret-bernama** (`measurements[].gaya_pos_0/90/180/270` untuk
///     UTM & Load Cell, `gaya_up`/`gaya_down` untuk Proving Ring) digabung per
///     POSISI baris; nominalnya dari tabel PERTAMA, dan kotak Nominal tabel lain
///     menampilkannya (`LembarKerjaState.acuanNominal`).
///  2. **Dua halaman** — identitas & standar | pengukuran & penutup.
library;

/// Bentuk lembar kerja contoh **Mesin UTM**.
///
/// Kode profil `utm`, satuan `-`, kertas `SIDIK-FM-CAL-0519_Rev.3`.
Map<String, dynamic> contohBentukLembarKerjaUtm({
  bool untukAdmin = false,
}) {
  return {
    'kode_dokumen': 'SIDIK-FM-CAL-0519_Rev.3',
    'kode_metode': 'SIDIK-IK-CAL-0513_Rev.3',
    'nomor_lingkup': 'LK-285-IDN',
    'judul': 'Lembar Kerja Kalibrasi Mesin UTM',
    'jumlah_pengulangan': 3,
    'semua_kolom_opsional': false,
    'catatan_pengisian': 'Tiap titik beban diisi DUA BELAS kali: empat posisi (0°, 90°, 180°, 270°) x tiga replikat. Empat posisi bukan pengulangan biasa — kalau load cell standar tidak tepat di sumbu piringan, kesalahannya cuma kelihatan waktu alat dihadapkan ke arah berbeda. Preload (zero & kapasitas maks) dan empat pengukuran misalignment diisi sekali per sesi, bukan per titik.',
    'budget_ketidakpastian': {
      'tersedia': true,
      'sumber': 'Master Olah Data Gaya — UTM (.xlsm, PERHITUNGAN FC & PERHITUNGAN U95%)',
      'catatan': 'Delapan komponen dalam PERSEN (kesalahan load cell proporsional, bukan absolut), k dari t-Student dengan v_eff dipotong ke bawah, lalu dikonversi ke kN dan diadu ke lantai CMC dari lampiran akreditasi. Dua penyimpangan master direplikasi apa adanya dan tercatat di jejak sesi: baris drift tidak dibagi divisornya, dan Correction memakai nilai sebelum koreksi termal sementara sertifikat mencetak yang sesudahnya.',
    },
    'tanpa_keputusan': {
      'alasan': 'Sertifikat gaya tidak menyatakan lulus/tidak lulus. Lab melaporkan seberapa meleset; pelanggan yang menilai apakah itu cukup baik untuk pemakaiannya. ISO/IEC 17025 klausul 7.8.6.1 — pernyataan kesesuaian butuh aturan keputusan yang disepakati.',
    },
    'bagian': [
      {
        'kode': 'identitas_alat',
        'halaman': 1,
        'judul': 'Identitas Alat',
        'field': [
          {
            'kode': 'equipment_id',
            'label': 'Pilih Alat',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_alat',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_model',
            'label': 'Nama Alat',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_merk',
            'label': 'Merk',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_serial_number',
            'label': 'No. Seri',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.gaya.kapasitas',
            'label': 'Kapasitas Maks',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.gaya.satuan',
            'label': 'Satuan Gaya',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              'kN',
              'N',
              'lbf',
              'kgf',
              'tnf',
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.gaya.resolusi_uut',
            'label': 'Resolusi Alat',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.gaya.tipe_beban',
            'label': 'Tipe Beban',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              'Push',
              'Pull',
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'pemilik',
        'halaman': 1,
        'judul': 'Pemilik Alat',
        'field': [
          {
            'kode': 'pemilik_nama',
            'label': 'Nama Customer',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'pemilik_alamat',
            'label': 'Alamat Customer',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_awal',
            'label': 'Env. Condition — First (°C)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_akhir',
            'label': 'Env. Condition — End (°C)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_awal',
            'label': 'Env. Condition — First (%RH)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_akhir',
            'label': 'Env. Condition — End (%RH)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi',
            'label': 'Location',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'lab',
                'label': 'Inlab',
              },
              {
                'nilai': 'onsite',
                'label': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'room_id',
            'label': 'Ruangan (Inlab)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_ruangan',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'lab',
              ],
            },
          },
          {
            'kode': 'lokasi_nama',
            'label': 'Nama Tempat (Insitu)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'onsite',
              ],
            },
          },
          {
            'kode': 'thermohygro_standard_id',
            'label': 'Thermohygro Used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_thermohygro',
            'satuan': null,
            'pilihan': [
              {
                'nilai': '1',
                'label': 'TH-1',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '2',
                'label': 'TH-2',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '3',
                'label': 'TH-3',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '4',
                'label': 'TH-4',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '5',
                'label': 'TH-5',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '6',
                'label': 'TH-6',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '7',
                'label': 'TH-7',
                'grup': 'Thermohygro lab',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'usage_check',
        'halaman': 1,
        'judul': 'Standar & Preload Test',
        'baris': [
          {
            'label': 'Load Cell 5 kN',
            'standard_id': 81,
            'serial_number': 'LC-01-SDK',
            'no_sertifikat': null,
            'tertelusur_ke': 'LK-057-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Load Cell 100 kN',
            'standard_id': 82,
            'serial_number': 'J10CC13283',
            'no_sertifikat': null,
            'tertelusur_ke': 'LK-057-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Load Cell 3000 kN',
            'standard_id': 83,
            'serial_number': 'C-140-BZ/0008',
            'no_sertifikat': null,
            'tertelusur_ke': 'LK-013-IDN',
            'terdaftar': true,
          },
        ],
        'field': [
          {
            'kode': 'spesifikasi_alat.gaya.kapasitas_standar',
            'label': 'Kapasitas Standar (kN)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.gaya.resolusi_standar',
            'label': 'Resolusi Standar (kN)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.gaya.suhu_sertifikat_standar',
            'label': 'Suhu Sertifikat Standar (°C)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
        'tabel': [
          {
            'tahap': 'sebelum_adjustment',
            'grup': 'preload',
            'offset_kunci': 9000,
            'judul': 'Preload Test (3 replikat)',
            'judul_nilai': 'Pemeriksaan',
            'judul_pengulangan': 'Ulangan ke',
            'titik_bisa_diubah': false,
            'simpan_ke': 'spesifikasi_alat.gaya.preload',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Zero',
                'kunci': 'preload_zero',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Max Capacity',
                'kunci': 'preload_max',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Pembacaan',
                'tipe': 'angka',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
        ],
      },
      {
        'kode': 'misalignment',
        'halaman': 1,
        'judul': 'Misalignment Axial',
        'field': [
          {
            'kode': 'spesifikasi_alat.gaya.misalignment.1',
            'label': 'Sisi X1 (mm)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.gaya.misalignment.2',
            'label': 'Sisi X2 (mm)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.gaya.misalignment.3',
            'label': 'Sisi X3 (mm)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.gaya.misalignment.4',
            'label': 'Sisi X4 (mm)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'hasil',
        'halaman': 2,
        'judul': 'Accuracy Test',
        'tampilan': 'kartu_per_baris',
        'kartu_sejajar': true,
        'nominal_berbintang': false,
        'field': <dynamic>[],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'gaya_pos_0',
            'offset_kunci': 1000,
            'judul': 'a. Posisi 0°',
            'judul_nilai': 'Nominal',
            'judul_pengulangan': 'Replikat ke',
            'titik_bisa_diubah': false,
            'simpan_ke': 'measurements[].gaya_pos_0',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Titik 2',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Titik 3',
              },
              {
                'nomor': 4,
                'titik_ukur': null,
                'label': 'Titik 4',
              },
              {
                'nomor': 5,
                'titik_ukur': null,
                'label': 'Titik 5',
              },
              {
                'nomor': 6,
                'titik_ukur': null,
                'label': 'Titik 6',
              },
              {
                'nomor': 7,
                'titik_ukur': null,
                'label': 'Titik 7',
              },
              {
                'nomor': 8,
                'titik_ukur': null,
                'label': 'Titik 8',
              },
              {
                'nomor': 9,
                'titik_ukur': null,
                'label': 'Titik 9',
              },
              {
                'nomor': 10,
                'titik_ukur': null,
                'label': 'Titik 10',
              },
              {
                'nomor': 11,
                'titik_ukur': null,
                'label': 'Titik 11',
              },
              {
                'nomor': 12,
                'titik_ukur': null,
                'label': 'Titik 12',
              },
              {
                'nomor': 13,
                'titik_ukur': null,
                'label': 'Titik 13',
              },
              {
                'nomor': 14,
                'titik_ukur': null,
                'label': 'Titik 14',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Pembacaan UUT',
                'tipe': 'angka',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'gaya_pos_90',
            'offset_kunci': 2000,
            'judul': 'b. Posisi 90°',
            'judul_nilai': 'Nominal',
            'judul_pengulangan': 'Replikat ke',
            'titik_bisa_diubah': false,
            'simpan_ke': 'measurements[].gaya_pos_90',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Titik 2',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Titik 3',
              },
              {
                'nomor': 4,
                'titik_ukur': null,
                'label': 'Titik 4',
              },
              {
                'nomor': 5,
                'titik_ukur': null,
                'label': 'Titik 5',
              },
              {
                'nomor': 6,
                'titik_ukur': null,
                'label': 'Titik 6',
              },
              {
                'nomor': 7,
                'titik_ukur': null,
                'label': 'Titik 7',
              },
              {
                'nomor': 8,
                'titik_ukur': null,
                'label': 'Titik 8',
              },
              {
                'nomor': 9,
                'titik_ukur': null,
                'label': 'Titik 9',
              },
              {
                'nomor': 10,
                'titik_ukur': null,
                'label': 'Titik 10',
              },
              {
                'nomor': 11,
                'titik_ukur': null,
                'label': 'Titik 11',
              },
              {
                'nomor': 12,
                'titik_ukur': null,
                'label': 'Titik 12',
              },
              {
                'nomor': 13,
                'titik_ukur': null,
                'label': 'Titik 13',
              },
              {
                'nomor': 14,
                'titik_ukur': null,
                'label': 'Titik 14',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Pembacaan UUT',
                'tipe': 'angka',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'gaya_pos_180',
            'offset_kunci': 3000,
            'judul': 'c. Posisi 180°',
            'judul_nilai': 'Nominal',
            'judul_pengulangan': 'Replikat ke',
            'titik_bisa_diubah': false,
            'simpan_ke': 'measurements[].gaya_pos_180',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Titik 2',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Titik 3',
              },
              {
                'nomor': 4,
                'titik_ukur': null,
                'label': 'Titik 4',
              },
              {
                'nomor': 5,
                'titik_ukur': null,
                'label': 'Titik 5',
              },
              {
                'nomor': 6,
                'titik_ukur': null,
                'label': 'Titik 6',
              },
              {
                'nomor': 7,
                'titik_ukur': null,
                'label': 'Titik 7',
              },
              {
                'nomor': 8,
                'titik_ukur': null,
                'label': 'Titik 8',
              },
              {
                'nomor': 9,
                'titik_ukur': null,
                'label': 'Titik 9',
              },
              {
                'nomor': 10,
                'titik_ukur': null,
                'label': 'Titik 10',
              },
              {
                'nomor': 11,
                'titik_ukur': null,
                'label': 'Titik 11',
              },
              {
                'nomor': 12,
                'titik_ukur': null,
                'label': 'Titik 12',
              },
              {
                'nomor': 13,
                'titik_ukur': null,
                'label': 'Titik 13',
              },
              {
                'nomor': 14,
                'titik_ukur': null,
                'label': 'Titik 14',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Pembacaan UUT',
                'tipe': 'angka',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'gaya_pos_270',
            'offset_kunci': 4000,
            'judul': 'd. Posisi 270°',
            'judul_nilai': 'Nominal',
            'judul_pengulangan': 'Replikat ke',
            'titik_bisa_diubah': false,
            'simpan_ke': 'measurements[].gaya_pos_270',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Titik 2',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Titik 3',
              },
              {
                'nomor': 4,
                'titik_ukur': null,
                'label': 'Titik 4',
              },
              {
                'nomor': 5,
                'titik_ukur': null,
                'label': 'Titik 5',
              },
              {
                'nomor': 6,
                'titik_ukur': null,
                'label': 'Titik 6',
              },
              {
                'nomor': 7,
                'titik_ukur': null,
                'label': 'Titik 7',
              },
              {
                'nomor': 8,
                'titik_ukur': null,
                'label': 'Titik 8',
              },
              {
                'nomor': 9,
                'titik_ukur': null,
                'label': 'Titik 9',
              },
              {
                'nomor': 10,
                'titik_ukur': null,
                'label': 'Titik 10',
              },
              {
                'nomor': 11,
                'titik_ukur': null,
                'label': 'Titik 11',
              },
              {
                'nomor': 12,
                'titik_ukur': null,
                'label': 'Titik 12',
              },
              {
                'nomor': 13,
                'titik_ukur': null,
                'label': 'Titik 13',
              },
              {
                'nomor': 14,
                'titik_ukur': null,
                'label': 'Titik 14',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Pembacaan UUT',
                'tipe': 'angka',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
        ],
      },
      {
        'kode': 'penutup',
        'halaman': 2,
        'judul': 'Catatan & Tanda Tangan',
        'field': [
          {
            'kode': 'catatan_teknisi',
            'label': 'Note',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'teknisi.nama',
            'label': 'Calibrated by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'reviewer.nama',
            'label': 'Checked by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
    ],
  };
}

/// Bentuk lembar kerja contoh **Load Cell**.
///
/// Kode profil `load_cell`, satuan `-`, kertas `SIDIK-FM-CAL-0520_Rev.3`.
Map<String, dynamic> contohBentukLembarKerjaLoadCell({
  bool untukAdmin = false,
}) {
  return {
    'kode_dokumen': 'SIDIK-FM-CAL-0520_Rev.3',
    'kode_metode': 'SIDIK-IK-CAL-0514_Rev.3',
    'nomor_lingkup': 'LK-285-IDN',
    'judul': 'Lembar Kerja Kalibrasi Load Cell',
    'jumlah_pengulangan': 3,
    'semua_kolom_opsional': false,
    'catatan_pengisian': 'Tiap titik beban diisi DUA BELAS kali: empat posisi (0°, 90°, 180°, 270°) x tiga replikat. Empat posisi bukan pengulangan biasa — kalau load cell standar tidak tepat di sumbu piringan, kesalahannya cuma kelihatan waktu alat dihadapkan ke arah berbeda. Preload (zero & kapasitas maks) dan empat pengukuran misalignment diisi sekali per sesi, bukan per titik.',
    'budget_ketidakpastian': {
      'tersedia': true,
      'sumber': 'Master Olah Data Gaya — Load Cell (.xlsm, PERHITUNGAN FC & PERHITUNGAN U95%)',
      'catatan': 'Delapan komponen dalam PERSEN (kesalahan load cell proporsional, bukan absolut), k dari t-Student dengan v_eff dipotong ke bawah, lalu dikonversi ke kN dan diadu ke lantai CMC dari lampiran akreditasi. Dua penyimpangan master direplikasi apa adanya dan tercatat di jejak sesi: baris drift tidak dibagi divisornya, dan Correction memakai nilai sebelum koreksi termal sementara sertifikat mencetak yang sesudahnya.',
    },
    'tanpa_keputusan': {
      'alasan': 'Sertifikat gaya tidak menyatakan lulus/tidak lulus. Lab melaporkan seberapa meleset; pelanggan yang menilai apakah itu cukup baik untuk pemakaiannya. ISO/IEC 17025 klausul 7.8.6.1 — pernyataan kesesuaian butuh aturan keputusan yang disepakati.',
    },
    'bagian': [
      {
        'kode': 'identitas_alat',
        'halaman': 1,
        'judul': 'Identitas Alat',
        'field': [
          {
            'kode': 'equipment_id',
            'label': 'Pilih Alat',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_alat',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_model',
            'label': 'Nama Alat',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_merk',
            'label': 'Merk',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_serial_number',
            'label': 'No. Seri',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.gaya.kapasitas',
            'label': 'Kapasitas Maks',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.gaya.satuan',
            'label': 'Satuan Gaya',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              'kN',
              'N',
              'lbf',
              'kgf',
              'tnf',
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.gaya.resolusi_uut',
            'label': 'Resolusi Alat',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.gaya.tipe_beban',
            'label': 'Tipe Beban',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              'Push',
              'Pull',
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'pemilik',
        'halaman': 1,
        'judul': 'Pemilik Alat',
        'field': [
          {
            'kode': 'pemilik_nama',
            'label': 'Nama Customer',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'pemilik_alamat',
            'label': 'Alamat Customer',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_awal',
            'label': 'Env. Condition — First (°C)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_akhir',
            'label': 'Env. Condition — End (°C)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_awal',
            'label': 'Env. Condition — First (%RH)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_akhir',
            'label': 'Env. Condition — End (%RH)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi',
            'label': 'Location',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'lab',
                'label': 'Inlab',
              },
              {
                'nilai': 'onsite',
                'label': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'room_id',
            'label': 'Ruangan (Inlab)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_ruangan',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'lab',
              ],
            },
          },
          {
            'kode': 'lokasi_nama',
            'label': 'Nama Tempat (Insitu)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'onsite',
              ],
            },
          },
          {
            'kode': 'thermohygro_standard_id',
            'label': 'Thermohygro Used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_thermohygro',
            'satuan': null,
            'pilihan': [
              {
                'nilai': '1',
                'label': 'TH-1',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '2',
                'label': 'TH-2',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '3',
                'label': 'TH-3',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '4',
                'label': 'TH-4',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '5',
                'label': 'TH-5',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '6',
                'label': 'TH-6',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '7',
                'label': 'TH-7',
                'grup': 'Thermohygro lab',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'usage_check',
        'halaman': 1,
        'judul': 'Standar & Preload Test',
        'baris': [
          {
            'label': 'Load Cell 5 kN',
            'standard_id': 81,
            'serial_number': 'LC-01-SDK',
            'no_sertifikat': null,
            'tertelusur_ke': 'LK-057-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Load Cell 100 kN',
            'standard_id': 82,
            'serial_number': 'J10CC13283',
            'no_sertifikat': null,
            'tertelusur_ke': 'LK-057-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Load Cell 3000 kN',
            'standard_id': 83,
            'serial_number': 'C-140-BZ/0008',
            'no_sertifikat': null,
            'tertelusur_ke': 'LK-013-IDN',
            'terdaftar': true,
          },
        ],
        'field': [
          {
            'kode': 'spesifikasi_alat.gaya.kapasitas_standar',
            'label': 'Kapasitas Standar (kN)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.gaya.resolusi_standar',
            'label': 'Resolusi Standar (kN)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.gaya.suhu_sertifikat_standar',
            'label': 'Suhu Sertifikat Standar (°C)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
        'tabel': [
          {
            'tahap': 'sebelum_adjustment',
            'grup': 'preload',
            'offset_kunci': 9000,
            'judul': 'Preload Test (3 replikat)',
            'judul_nilai': 'Pemeriksaan',
            'judul_pengulangan': 'Ulangan ke',
            'titik_bisa_diubah': false,
            'simpan_ke': 'spesifikasi_alat.gaya.preload',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Zero',
                'kunci': 'preload_zero',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Max Capacity',
                'kunci': 'preload_max',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Pembacaan',
                'tipe': 'angka',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
        ],
      },
      {
        'kode': 'misalignment',
        'halaman': 1,
        'judul': 'Misalignment Axial',
        'field': [
          {
            'kode': 'spesifikasi_alat.gaya.misalignment.1',
            'label': 'Sisi X1 (mm)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.gaya.misalignment.2',
            'label': 'Sisi X2 (mm)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.gaya.misalignment.3',
            'label': 'Sisi X3 (mm)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.gaya.misalignment.4',
            'label': 'Sisi X4 (mm)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'hasil',
        'halaman': 2,
        'judul': 'Accuracy Test',
        'tampilan': 'kartu_per_baris',
        'kartu_sejajar': true,
        'nominal_berbintang': false,
        'field': <dynamic>[],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'gaya_pos_0',
            'offset_kunci': 1000,
            'judul': 'a. Posisi 0°',
            'judul_nilai': 'Nominal',
            'judul_pengulangan': 'Replikat ke',
            'titik_bisa_diubah': false,
            'simpan_ke': 'measurements[].gaya_pos_0',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Titik 2',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Titik 3',
              },
              {
                'nomor': 4,
                'titik_ukur': null,
                'label': 'Titik 4',
              },
              {
                'nomor': 5,
                'titik_ukur': null,
                'label': 'Titik 5',
              },
              {
                'nomor': 6,
                'titik_ukur': null,
                'label': 'Titik 6',
              },
              {
                'nomor': 7,
                'titik_ukur': null,
                'label': 'Titik 7',
              },
              {
                'nomor': 8,
                'titik_ukur': null,
                'label': 'Titik 8',
              },
              {
                'nomor': 9,
                'titik_ukur': null,
                'label': 'Titik 9',
              },
              {
                'nomor': 10,
                'titik_ukur': null,
                'label': 'Titik 10',
              },
              {
                'nomor': 11,
                'titik_ukur': null,
                'label': 'Titik 11',
              },
              {
                'nomor': 12,
                'titik_ukur': null,
                'label': 'Titik 12',
              },
              {
                'nomor': 13,
                'titik_ukur': null,
                'label': 'Titik 13',
              },
              {
                'nomor': 14,
                'titik_ukur': null,
                'label': 'Titik 14',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Pembacaan UUT',
                'tipe': 'angka',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'gaya_pos_90',
            'offset_kunci': 2000,
            'judul': 'b. Posisi 90°',
            'judul_nilai': 'Nominal',
            'judul_pengulangan': 'Replikat ke',
            'titik_bisa_diubah': false,
            'simpan_ke': 'measurements[].gaya_pos_90',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Titik 2',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Titik 3',
              },
              {
                'nomor': 4,
                'titik_ukur': null,
                'label': 'Titik 4',
              },
              {
                'nomor': 5,
                'titik_ukur': null,
                'label': 'Titik 5',
              },
              {
                'nomor': 6,
                'titik_ukur': null,
                'label': 'Titik 6',
              },
              {
                'nomor': 7,
                'titik_ukur': null,
                'label': 'Titik 7',
              },
              {
                'nomor': 8,
                'titik_ukur': null,
                'label': 'Titik 8',
              },
              {
                'nomor': 9,
                'titik_ukur': null,
                'label': 'Titik 9',
              },
              {
                'nomor': 10,
                'titik_ukur': null,
                'label': 'Titik 10',
              },
              {
                'nomor': 11,
                'titik_ukur': null,
                'label': 'Titik 11',
              },
              {
                'nomor': 12,
                'titik_ukur': null,
                'label': 'Titik 12',
              },
              {
                'nomor': 13,
                'titik_ukur': null,
                'label': 'Titik 13',
              },
              {
                'nomor': 14,
                'titik_ukur': null,
                'label': 'Titik 14',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Pembacaan UUT',
                'tipe': 'angka',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'gaya_pos_180',
            'offset_kunci': 3000,
            'judul': 'c. Posisi 180°',
            'judul_nilai': 'Nominal',
            'judul_pengulangan': 'Replikat ke',
            'titik_bisa_diubah': false,
            'simpan_ke': 'measurements[].gaya_pos_180',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Titik 2',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Titik 3',
              },
              {
                'nomor': 4,
                'titik_ukur': null,
                'label': 'Titik 4',
              },
              {
                'nomor': 5,
                'titik_ukur': null,
                'label': 'Titik 5',
              },
              {
                'nomor': 6,
                'titik_ukur': null,
                'label': 'Titik 6',
              },
              {
                'nomor': 7,
                'titik_ukur': null,
                'label': 'Titik 7',
              },
              {
                'nomor': 8,
                'titik_ukur': null,
                'label': 'Titik 8',
              },
              {
                'nomor': 9,
                'titik_ukur': null,
                'label': 'Titik 9',
              },
              {
                'nomor': 10,
                'titik_ukur': null,
                'label': 'Titik 10',
              },
              {
                'nomor': 11,
                'titik_ukur': null,
                'label': 'Titik 11',
              },
              {
                'nomor': 12,
                'titik_ukur': null,
                'label': 'Titik 12',
              },
              {
                'nomor': 13,
                'titik_ukur': null,
                'label': 'Titik 13',
              },
              {
                'nomor': 14,
                'titik_ukur': null,
                'label': 'Titik 14',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Pembacaan UUT',
                'tipe': 'angka',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'gaya_pos_270',
            'offset_kunci': 4000,
            'judul': 'd. Posisi 270°',
            'judul_nilai': 'Nominal',
            'judul_pengulangan': 'Replikat ke',
            'titik_bisa_diubah': false,
            'simpan_ke': 'measurements[].gaya_pos_270',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Titik 2',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Titik 3',
              },
              {
                'nomor': 4,
                'titik_ukur': null,
                'label': 'Titik 4',
              },
              {
                'nomor': 5,
                'titik_ukur': null,
                'label': 'Titik 5',
              },
              {
                'nomor': 6,
                'titik_ukur': null,
                'label': 'Titik 6',
              },
              {
                'nomor': 7,
                'titik_ukur': null,
                'label': 'Titik 7',
              },
              {
                'nomor': 8,
                'titik_ukur': null,
                'label': 'Titik 8',
              },
              {
                'nomor': 9,
                'titik_ukur': null,
                'label': 'Titik 9',
              },
              {
                'nomor': 10,
                'titik_ukur': null,
                'label': 'Titik 10',
              },
              {
                'nomor': 11,
                'titik_ukur': null,
                'label': 'Titik 11',
              },
              {
                'nomor': 12,
                'titik_ukur': null,
                'label': 'Titik 12',
              },
              {
                'nomor': 13,
                'titik_ukur': null,
                'label': 'Titik 13',
              },
              {
                'nomor': 14,
                'titik_ukur': null,
                'label': 'Titik 14',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Pembacaan UUT',
                'tipe': 'angka',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
        ],
      },
      {
        'kode': 'penutup',
        'halaman': 2,
        'judul': 'Catatan & Tanda Tangan',
        'field': [
          {
            'kode': 'catatan_teknisi',
            'label': 'Note',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'teknisi.nama',
            'label': 'Calibrated by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'reviewer.nama',
            'label': 'Checked by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
    ],
  };
}

/// Bentuk lembar kerja contoh **Proving Ring**.
///
/// Kode profil `proving_ring`, satuan `-`, kertas `-`.
Map<String, dynamic> contohBentukLembarKerjaProvingRing({
  bool untukAdmin = false,
}) {
  return {
    'kode_dokumen': null,
    'kode_metode': 'SIDIK-IK-CAL-0514_Rev.5',
    'nomor_lingkup': 'LK-285-IDN',
    'judul': 'Lembar Kerja Kalibrasi Proving Ring',
    'jumlah_pengulangan': 3,
    'semua_kolom_opsional': false,
    'catatan_pengisian': 'Tiap titik beban diisi ENAM kali: UP tiga kali lalu DOWN tiga kali. Arahnya bukan pengulangan biasa — cincin baja punya histeresis, jadi bacaan saat beban NAIK memang berbeda dari saat TURUN, dan perbedaannya itu yang diukur. Pembacaan diisi dalam DIVISI dial, bukan kgf. Preload dan empat pengukuran misalignment diisi sekali per sesi.',
    'budget_ketidakpastian': {
      'tersedia': true,
      'sumber': 'Master Olah Data Gaya — Proving Ring (.xlsm, PERHITUNGAN FC & PERHITUNGAN U95%)',
      'catatan': 'Delapan komponen dalam PERSEN (kesalahan load cell proporsional, bukan absolut), k dari t-Student dengan v_eff dipotong ke bawah, lalu dikonversi ke kN dan diadu ke lantai CMC dari lampiran akreditasi. Dua penyimpangan master direplikasi apa adanya dan tercatat di jejak sesi: baris drift tidak dibagi divisornya, dan Correction memakai nilai sebelum koreksi termal sementara sertifikat mencetak yang sesudahnya.',
    },
    'tanpa_keputusan': {
      'alasan': 'Sertifikat gaya tidak menyatakan lulus/tidak lulus. Lab melaporkan seberapa meleset; pelanggan yang menilai apakah itu cukup baik untuk pemakaiannya. ISO/IEC 17025 klausul 7.8.6.1 — pernyataan kesesuaian butuh aturan keputusan yang disepakati.',
    },
    'bagian': [
      {
        'kode': 'identitas_alat',
        'halaman': 1,
        'judul': 'Identitas Alat',
        'field': [
          {
            'kode': 'equipment_id',
            'label': 'Pilih Alat',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_alat',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_model',
            'label': 'Nama Alat',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_merk',
            'label': 'Merk',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_serial_number',
            'label': 'No. Seri',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.gaya.kapasitas',
            'label': 'Kapasitas Maks',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.gaya.satuan',
            'label': 'Satuan Gaya',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              'kN',
              'N',
              'lbf',
              'kgf',
              'tnf',
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.gaya.tipe_beban',
            'label': 'Tipe Beban',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              'Push',
              'Pull',
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.gaya.kapasitas_dial_mm',
            'label': 'Kapasitas Dial (mm)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.gaya.resolusi_dial_mm',
            'label': 'Resolusi Dial (mm)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'pemilik',
        'halaman': 1,
        'judul': 'Pemilik Alat',
        'field': [
          {
            'kode': 'pemilik_nama',
            'label': 'Nama Customer',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'pemilik_alamat',
            'label': 'Alamat Customer',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_awal',
            'label': 'Env. Condition — First (°C)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_akhir',
            'label': 'Env. Condition — End (°C)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_awal',
            'label': 'Env. Condition — First (%RH)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_akhir',
            'label': 'Env. Condition — End (%RH)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi',
            'label': 'Location',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'lab',
                'label': 'Inlab',
              },
              {
                'nilai': 'onsite',
                'label': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'room_id',
            'label': 'Ruangan (Inlab)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_ruangan',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'lab',
              ],
            },
          },
          {
            'kode': 'lokasi_nama',
            'label': 'Nama Tempat (Insitu)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'onsite',
              ],
            },
          },
          {
            'kode': 'thermohygro_standard_id',
            'label': 'Thermohygro Used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_thermohygro',
            'satuan': null,
            'pilihan': [
              {
                'nilai': '1',
                'label': 'TH-1',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '2',
                'label': 'TH-2',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '3',
                'label': 'TH-3',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '4',
                'label': 'TH-4',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '5',
                'label': 'TH-5',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '6',
                'label': 'TH-6',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '7',
                'label': 'TH-7',
                'grup': 'Thermohygro lab',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'usage_check',
        'halaman': 1,
        'judul': 'Standar & Preload Test',
        'baris': [
          {
            'label': 'Load Cell 5 kN',
            'standard_id': 81,
            'serial_number': 'LC-01-SDK',
            'no_sertifikat': null,
            'tertelusur_ke': 'LK-057-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Load Cell 100 kN',
            'standard_id': 82,
            'serial_number': 'J10CC13283',
            'no_sertifikat': null,
            'tertelusur_ke': 'LK-057-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Load Cell 3000 kN',
            'standard_id': 83,
            'serial_number': 'C-140-BZ/0008',
            'no_sertifikat': null,
            'tertelusur_ke': 'LK-013-IDN',
            'terdaftar': true,
          },
        ],
        'field': [
          {
            'kode': 'spesifikasi_alat.gaya.kapasitas_standar',
            'label': 'Kapasitas Standar (kN)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.gaya.resolusi_standar',
            'label': 'Resolusi Standar (kN)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.gaya.suhu_sertifikat_standar',
            'label': 'Suhu Sertifikat Standar (°C)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
        'tabel': [
          {
            'tahap': 'sebelum_adjustment',
            'grup': 'preload',
            'offset_kunci': 9000,
            'judul': 'Preload Test (3 replikat)',
            'judul_nilai': 'Pemeriksaan',
            'judul_pengulangan': 'Ulangan ke',
            'titik_bisa_diubah': false,
            'simpan_ke': 'spesifikasi_alat.gaya.preload',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Zero',
                'kunci': 'preload_zero',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Max Capacity',
                'kunci': 'preload_max',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Pembacaan',
                'tipe': 'angka',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
        ],
      },
      {
        'kode': 'misalignment',
        'halaman': 1,
        'judul': 'Misalignment Axial',
        'field': [
          {
            'kode': 'spesifikasi_alat.gaya.misalignment.1',
            'label': 'Sisi X1 (mm)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.gaya.misalignment.2',
            'label': 'Sisi X2 (mm)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.gaya.misalignment.3',
            'label': 'Sisi X3 (mm)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.gaya.misalignment.4',
            'label': 'Sisi X4 (mm)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'hasil',
        'halaman': 2,
        'judul': 'Accuracy Test',
        'tampilan': 'kartu_per_baris',
        'kartu_sejajar': true,
        'nominal_berbintang': false,
        'field': <dynamic>[],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'gaya_up',
            'offset_kunci': 1000,
            'judul': 'a. Beban NAIK (UP)',
            'judul_nilai': 'Nominal',
            'judul_pengulangan': 'Replikat ke',
            'titik_bisa_diubah': false,
            'simpan_ke': 'measurements[].gaya_up',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Titik 2',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Titik 3',
              },
              {
                'nomor': 4,
                'titik_ukur': null,
                'label': 'Titik 4',
              },
              {
                'nomor': 5,
                'titik_ukur': null,
                'label': 'Titik 5',
              },
              {
                'nomor': 6,
                'titik_ukur': null,
                'label': 'Titik 6',
              },
              {
                'nomor': 7,
                'titik_ukur': null,
                'label': 'Titik 7',
              },
              {
                'nomor': 8,
                'titik_ukur': null,
                'label': 'Titik 8',
              },
              {
                'nomor': 9,
                'titik_ukur': null,
                'label': 'Titik 9',
              },
              {
                'nomor': 10,
                'titik_ukur': null,
                'label': 'Titik 10',
              },
              {
                'nomor': 11,
                'titik_ukur': null,
                'label': 'Titik 11',
              },
              {
                'nomor': 12,
                'titik_ukur': null,
                'label': 'Titik 12',
              },
              {
                'nomor': 13,
                'titik_ukur': null,
                'label': 'Titik 13',
              },
              {
                'nomor': 14,
                'titik_ukur': null,
                'label': 'Titik 14',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Pembacaan Dial (Div)',
                'tipe': 'angka',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'gaya_down',
            'offset_kunci': 2000,
            'judul': 'b. Beban TURUN (DOWN)',
            'judul_nilai': 'Nominal',
            'judul_pengulangan': 'Replikat ke',
            'titik_bisa_diubah': false,
            'simpan_ke': 'measurements[].gaya_down',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Titik 2',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Titik 3',
              },
              {
                'nomor': 4,
                'titik_ukur': null,
                'label': 'Titik 4',
              },
              {
                'nomor': 5,
                'titik_ukur': null,
                'label': 'Titik 5',
              },
              {
                'nomor': 6,
                'titik_ukur': null,
                'label': 'Titik 6',
              },
              {
                'nomor': 7,
                'titik_ukur': null,
                'label': 'Titik 7',
              },
              {
                'nomor': 8,
                'titik_ukur': null,
                'label': 'Titik 8',
              },
              {
                'nomor': 9,
                'titik_ukur': null,
                'label': 'Titik 9',
              },
              {
                'nomor': 10,
                'titik_ukur': null,
                'label': 'Titik 10',
              },
              {
                'nomor': 11,
                'titik_ukur': null,
                'label': 'Titik 11',
              },
              {
                'nomor': 12,
                'titik_ukur': null,
                'label': 'Titik 12',
              },
              {
                'nomor': 13,
                'titik_ukur': null,
                'label': 'Titik 13',
              },
              {
                'nomor': 14,
                'titik_ukur': null,
                'label': 'Titik 14',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Pembacaan Dial (Div)',
                'tipe': 'angka',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
        ],
      },
      {
        'kode': 'penutup',
        'halaman': 2,
        'judul': 'Catatan & Tanda Tangan',
        'field': [
          {
            'kode': 'catatan_teknisi',
            'label': 'Note',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'teknisi.nama',
            'label': 'Calibrated by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'reviewer.nama',
            'label': 'Checked by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
    ],
  };
}
