/// Bentuk lembar kerja tiga alat suhu ber-PASANGAN deret, buat mode mock.
///
/// **Disalin apa adanya dari respons `GET /api/calibrations/lembar-kerja`
/// server**, bukan diketik ulang — berkas yang sama dipakai jadi fixture test
/// (`test/fixtures/lembar-kerja-*.json`). Bentuk mock yang diketik ulang cuma
/// membuktikan layar sepakat dengan dirinya sendiri, dan kontrak yang bergeser
/// di server nggak akan pernah memerahkannya.
///
/// Yang bikin ketiganya beda dari empat belas bentuk mock lain: tiap bagian
/// hasil punya DUA tabel ber-`tahap` sama (`sesudah_adjustment`) yang
/// dibedakan `peran` (`standar` / `uut`) dan `grup`. Lihat
/// `ProfilSuhuPasangan` di repo API.
library;

/// Thermocouple (alat ke-18) — `SIDIK-IK-CAL-0529_Rev.2`, sesi master
/// `0513-CAL-1124`.
Map<String, dynamic> contohBentukLembarKerjaThermocouple({bool untukAdmin = false}) {
  final bentuk = <String, dynamic>{
    'kode_dokumen': null,
    'kode_metode': 'SIDIK-IK-CAL-0529_Rev.2',
    'judul': 'Calibration Worksheet - Thermocouple',
    'jumlah_pengulangan': 5,
    'larutan_standar': [
      50,
      100,
      150,
      200,
      400,
      600,
    ],
    'satuan': '°C',
    'satuan_suhu': '°C',
    'semua_kolom_opsional': true,
    'catatan_pengisian': 'Kolom yang belum bisa diisi di lapangan boleh dikosongin — lembar kerja tetap bisa dikirim. Khusus alat ini: TIPE SENSOR STANDAR, DRYBLOCK, dan NO. TERMOKOPEL tiap baris wajib diisi. Ketiganya nentuin ANGKA, bukan catatan — tabel koreksi & dua komponen budget diambil dari situ. Tiap titik dibaca DUA deret: standar (detik ke-0, 20, 40, 60, 80) dan UUT (detik ke-10, 30, 50, 70, 90).',
    'bagian': [
      {
        'kode': 'identitas_alat',
        'halaman': 1,
        'judul': 'EQUIPMENT IDENTITY AND CUSTOMER DATA',
        'field': [
          {
            'kode': 'tanggal_terima',
            'label': 'Received Date',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_kalibrasi',
            'label': 'Calibration Date',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'equipment_id',
            'label': 'Equipment',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_alat',
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'equipment.nama_alat',
            'label': '1. Nama Alat',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_merk',
            'label': '2. Merk',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_model',
            'label': '3. Type',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_serial_number',
            'label': '4. No. Seri',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.rentang_ukur',
            'label': '5. Rentang Ukur',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.kapasitas',
            'label': '6. Kapasitas Alat',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.resolusi',
            'label': '7. Resolusi Indikator',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'pemilik',
        'halaman': 1,
        'judul': 'IDENTITAS CUSTOMER',
        'field': [
          {
            'kode': 'pemilik_nama',
            'label': '1. Nama Customer',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'pemilik_alamat',
            'label': '2. Alamat Customer',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'usage_check',
        'halaman': 1,
        'judul': 'STANDARD',
        'baris': [
          {
            'label': 'Temperature Calibrator Constant 40T',
            'standard_id': 44,
            'merk': 'Constant',
            'serial_number': '99875850',
            'no_sertifikat': '99875850',
            'tertelusur_ke': 'LK-202-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Temperature Calibrator Yokogawa CA 150 Handy Cal',
            'standard_id': 45,
            'merk': 'Yokogawa',
            'serial_number': '23P1005',
            'no_sertifikat': '23P1005',
            'tertelusur_ke': 'LK-202-IDN',
            'terdaftar': true,
          },
          {
            'label': 'PRT Pt-100',
            'standard_id': 47,
            'merk': null,
            'serial_number': 'SH1/20',
            'no_sertifikat': 'SH1/20',
            'tertelusur_ke': 'SNSU-BSN',
            'terdaftar': true,
          },
          {
            'label': 'Thermocouple Type K',
            'standard_id': 48,
            'merk': null,
            'serial_number': 'TC-01,02',
            'no_sertifikat': 'TC-01,02',
            'tertelusur_ke': 'LK-064-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Thermocouple Type N',
            'standard_id': 49,
            'merk': null,
            'serial_number': 'TCN-06,11',
            'no_sertifikat': 'TCN-06,11',
            'tertelusur_ke': 'LK-064-IDN',
            'terdaftar': true,
          },
        ],
        'field': [
          {
            'kode': 'standar_dicek.*.dipakai',
            'label': 'Usage Check',
            'tipe': 'centang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'standar_dicek.*.keterangan',
            'label': 'Keterangan',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'data_kalibrasi',
        'halaman': 1,
        'judul': 'PENGERJAAN',
        'field': [
          {
            'kode': 'tipe_sensor',
            'label': 'Standar Sensor',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'RTD',
                'label': 'RTD',
              },
              {
                'nilai': 'Type K',
                'label': 'Type K',
              },
              {
                'nilai': 'Type N',
                'label': 'Type N',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_bantu',
            'label': 'Dry Block Used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'A',
                'label': 'A — Isotech Fast Cal Low (−20…150 °C)',
              },
              {
                'nilai': 'B',
                'label': 'B — Techne Tecal 700xs (150…600 °C)',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi',
            'label': 'Lokasi Kalibrasi',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'lab',
                'label': 'Inlab',
              },
              {
                'nilai': 'onsite',
                'label': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi_nama',
            'label': 'Nama Tempat (Insitu)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'onsite',
              ],
            },
          },
          {
            'kode': 'room_id',
            'label': 'Ruangan (Inlab)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_ruangan',
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'lab',
              ],
            },
          },
          {
            'kode': 'calibration_method_id',
            'label': 'Calibration Method',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_metode',
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': true,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'hasil',
        'halaman': 1,
        'judul': 'DATA HASIL KALIBRASI',
        'field': [
          {
            'kode': 'suhu_awal',
            'label': 'Suhu Ruangan — Awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_akhir',
            'label': 'Suhu Ruangan — Akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_awal',
            'label': 'Kelembaban — Awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_akhir',
            'label': 'Kelembaban — Akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'thermohygro_standard_id',
            'label': 'Environmental Meter Used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_thermohygro',
            'satuan': null,
            'pilihan': [
              {
                'nilai': '1',
                'label': 'TH-1',
                'grup': 'Inlab',
              },
              {
                'nilai': '3',
                'label': 'TH-3',
                'grup': 'Inlab',
              },
              {
                'nilai': '4',
                'label': 'TH-4',
                'grup': 'Inlab',
              },
              {
                'nilai': '5',
                'label': 'TH-5',
                'grup': 'Inlab',
              },
              {
                'nilai': '7',
                'label': 'TH-7',
                'grup': 'Inlab',
              },
              {
                'nilai': '2',
                'label': 'TH-2',
                'grup': 'Insitu',
              },
              {
                'nilai': '6',
                'label': 'TH-6',
                'grup': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'standar',
            'peran': 'standar',
            'judul': 'Pembacaan Standard',
            'satuan': '°C',
            'judul_nilai': 'Set Point',
            'judul_pengulangan': 'Data Hasil Pengukuran/Pengulangan (PRT1…PRT5)',
            'pengulangan_arah': [
              {
                'ke': 1,
                'label': '0″',
              },
              {
                'ke': 2,
                'label': '20″',
              },
              {
                'ke': 3,
                'label': '40″',
              },
              {
                'ke': 4,
                'label': '60″',
              },
              {
                'ke': 5,
                'label': '80″',
              },
            ],
            'titik_bisa_diubah': true,
            'baris': [
              {
                'titik_ukur': 50,
                'label': '50 °C',
                'satuan': '°C',
                'standard_id': 45,
                'standard_nama': 'Temperature Calibrator Yokogawa CA 150 Handy Cal',
              },
              {
                'titik_ukur': 100,
                'label': '100 °C',
                'satuan': '°C',
                'standard_id': 45,
                'standard_nama': 'Temperature Calibrator Yokogawa CA 150 Handy Cal',
              },
              {
                'titik_ukur': 150,
                'label': '150 °C',
                'satuan': '°C',
                'standard_id': 45,
                'standard_nama': 'Temperature Calibrator Yokogawa CA 150 Handy Cal',
              },
              {
                'titik_ukur': 200,
                'label': '200 °C',
                'satuan': '°C',
                'standard_id': 45,
                'standard_nama': 'Temperature Calibrator Yokogawa CA 150 Handy Cal',
              },
              {
                'titik_ukur': 400,
                'label': '400 °C',
                'satuan': '°C',
                'standard_id': 45,
                'standard_nama': 'Temperature Calibrator Yokogawa CA 150 Handy Cal',
              },
              {
                'titik_ukur': 600,
                'label': '600 °C',
                'satuan': '°C',
                'standard_id': 45,
                'standard_nama': 'Temperature Calibrator Yokogawa CA 150 Handy Cal',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': '°C',
                'tipe': 'angka',
                'satuan': '°C',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
              4,
              5,
            ],
            'kolom_baris': [
              {
                'kode': 'no_probe',
                'label': 'No. Termokopel',
                'tipe': 'pilihan',
                'wajib': false,
                'sumber': null,
                'satuan': null,
                'pilihan': [
                  {
                    'nilai': '17',
                    'label': '17 — RTD',
                    'grup': 'RTD',
                  },
                  {
                    'nilai': '1',
                    'label': '1 — TCK-01',
                    'grup': 'Type K',
                  },
                  {
                    'nilai': '2',
                    'label': '2 — TCK-02',
                    'grup': 'Type K',
                  },
                  {
                    'nilai': '3',
                    'label': '3 — TCK-03',
                    'grup': 'Type K',
                  },
                  {
                    'nilai': '4',
                    'label': '4 — TCK-04',
                    'grup': 'Type K',
                  },
                  {
                    'nilai': '5',
                    'label': '5 — TCK-05',
                    'grup': 'Type K',
                  },
                  {
                    'nilai': '6',
                    'label': '6 — TCK-06',
                    'grup': 'Type K',
                  },
                  {
                    'nilai': '7',
                    'label': '7 — TCK-07',
                    'grup': 'Type K',
                  },
                  {
                    'nilai': '8',
                    'label': '8 — TCK-08',
                    'grup': 'Type K',
                  },
                  {
                    'nilai': '9',
                    'label': '9 — TCK-09',
                    'grup': 'Type K',
                  },
                  {
                    'nilai': '10',
                    'label': '10 — TCK-10',
                    'grup': 'Type K',
                  },
                  {
                    'nilai': '11',
                    'label': '11 — TCK-11',
                    'grup': 'Type K',
                  },
                  {
                    'nilai': '12',
                    'label': '12 — TCK-12',
                    'grup': 'Type K',
                  },
                  {
                    'nilai': '13',
                    'label': '13 — TCK-13',
                    'grup': 'Type K',
                  },
                  {
                    'nilai': '14',
                    'label': '14 — TCK-14',
                    'grup': 'Type K',
                  },
                  {
                    'nilai': '15',
                    'label': '15 — TCK-15',
                    'grup': 'Type K',
                  },
                  {
                    'nilai': '16',
                    'label': '16 — TCK-16',
                    'grup': 'Type K',
                  },
                  {
                    'nilai': '3',
                    'label': '3 — TCN3',
                    'grup': 'Type N',
                  },
                  {
                    'nilai': '4',
                    'label': '4 — TCN4',
                    'grup': 'Type N',
                  },
                  {
                    'nilai': '5',
                    'label': '5 — TCN5',
                    'grup': 'Type N',
                  },
                  {
                    'nilai': '6',
                    'label': '6 — TCN6',
                    'grup': 'Type N',
                  },
                  {
                    'nilai': '7',
                    'label': '7 — TCN7',
                    'grup': 'Type N',
                  },
                  {
                    'nilai': '8',
                    'label': '8 — TCN8',
                    'grup': 'Type N',
                  },
                  {
                    'nilai': '9',
                    'label': '9 — TCN9',
                    'grup': 'Type N',
                  },
                  {
                    'nilai': '10',
                    'label': '10 — TCN10',
                    'grup': 'Type N',
                  },
                  {
                    'nilai': '11',
                    'label': '11 — TCN11',
                    'grup': 'Type N',
                  },
                  {
                    'nilai': '12',
                    'label': '12 — TCN12',
                    'grup': 'Type N',
                  },
                ],
                'hanya_admin': false,
                'tampil_kalau': null,
              },
            ],
            'catatan': 'Type N mulai dari nomor 3; PRT PT100 (RTD) selalu nomor 17.',
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'uut',
            'peran': 'uut',
            'judul': 'Pembacaan UUT',
            'satuan': '°C',
            'judul_nilai': 'Set Point',
            'judul_pengulangan': 'Data Hasil Pengukuran/Pengulangan (PRT1…PRT5)',
            'pengulangan_arah': [
              {
                'ke': 1,
                'label': '10″',
              },
              {
                'ke': 2,
                'label': '30″',
              },
              {
                'ke': 3,
                'label': '50″',
              },
              {
                'ke': 4,
                'label': '70″',
              },
              {
                'ke': 5,
                'label': '90″',
              },
            ],
            'titik_bisa_diubah': true,
            'baris': [
              {
                'titik_ukur': 50,
                'label': '50 °C',
                'satuan': '°C',
                'standard_id': 45,
                'standard_nama': 'Temperature Calibrator Yokogawa CA 150 Handy Cal',
              },
              {
                'titik_ukur': 100,
                'label': '100 °C',
                'satuan': '°C',
                'standard_id': 45,
                'standard_nama': 'Temperature Calibrator Yokogawa CA 150 Handy Cal',
              },
              {
                'titik_ukur': 150,
                'label': '150 °C',
                'satuan': '°C',
                'standard_id': 45,
                'standard_nama': 'Temperature Calibrator Yokogawa CA 150 Handy Cal',
              },
              {
                'titik_ukur': 200,
                'label': '200 °C',
                'satuan': '°C',
                'standard_id': 45,
                'standard_nama': 'Temperature Calibrator Yokogawa CA 150 Handy Cal',
              },
              {
                'titik_ukur': 400,
                'label': '400 °C',
                'satuan': '°C',
                'standard_id': 45,
                'standard_nama': 'Temperature Calibrator Yokogawa CA 150 Handy Cal',
              },
              {
                'titik_ukur': 600,
                'label': '600 °C',
                'satuan': '°C',
                'standard_id': 45,
                'standard_nama': 'Temperature Calibrator Yokogawa CA 150 Handy Cal',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': '°C',
                'tipe': 'angka',
                'satuan': '°C',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
              4,
              5,
            ],
          },
        ],
      },
      {
        'kode': 'penutup',
        'halaman': 1,
        'judul': 'Catatan & Tanda Tangan',
        'field': [
          {
            'kode': 'catatan_teknisi',
            'label': 'Catatan',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'teknisi.nama',
            'label': 'Calculated by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'reviewer.nama',
            'label': 'Signed by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
    ],
  };

  return bentuk;
}

/// Termometer Gelas (alat ke-19) — `SIDIK-IK-CAL-0527_Rev.1`, sesi master
/// `0135-CAL-125`.
Map<String, dynamic> contohBentukLembarKerjaTermometerGelas({bool untukAdmin = false}) {
  final bentuk = <String, dynamic>{
    'kode_dokumen': null,
    'kode_metode': 'SIDIK-IK-CAL-0527_Rev.1',
    'judul': 'Calibration Worksheet - Thermometer Glass',
    'jumlah_pengulangan': 5,
    'larutan_standar': [
      30,
      50,
      60,
      80,
      100,
    ],
    'satuan': '°C',
    'satuan_suhu': '°C',
    'semua_kolom_opsional': true,
    'catatan_pengisian': 'Kolom yang belum bisa diisi di lapangan boleh dikosongin — lembar kerja tetap bisa dikirim. Khusus alat ini: OILBATH dan TIPE PENCELUPAN wajib dipilih, dan UJI TITIK ES diisi lebih dulu (Pre-Evaluation) karena rentangnya masuk budget. Tiap titik dibaca DUA deret: standar (detik ke-0, 20, 40, 60, 80) dan UUT (detik ke-10, 30, 50, 70, 90).',
    'bagian': [
      {
        'kode': 'identitas_alat',
        'halaman': 1,
        'judul': 'EQUIPMENT IDENTITY AND CUSTOMER DATA',
        'field': [
          {
            'kode': 'tanggal_terima',
            'label': 'Received Date',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_kalibrasi',
            'label': 'Calibration Date',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'equipment_id',
            'label': 'Equipment',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_alat',
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'equipment.nama_alat',
            'label': '1. Nama Alat',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_merk',
            'label': '2. Merk',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_model',
            'label': '3. Type',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_serial_number',
            'label': '4. No. Seri',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.rentang_ukur',
            'label': '5. Rentang Ukur',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.kapasitas',
            'label': '6. Kapasitas Alat',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.resolusi',
            'label': '7. Resolusi Alat (skala terkecil)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'pemilik',
        'halaman': 1,
        'judul': 'IDENTITAS CUSTOMER',
        'field': [
          {
            'kode': 'pemilik_nama',
            'label': '1. Nama Customer',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'pemilik_alamat',
            'label': '2. Alamat Customer',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'usage_check',
        'halaman': 1,
        'judul': 'STANDARD',
        'baris': [
          {
            'label': 'Temperature Calibrator Constant 40T',
            'standard_id': 44,
            'merk': 'Constant',
            'serial_number': '99875850',
            'no_sertifikat': '99875850',
            'tertelusur_ke': 'LK-202-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Temperature Calibrator Yokogawa CA 150 Handy Cal',
            'standard_id': 45,
            'merk': 'Yokogawa',
            'serial_number': '23P1005',
            'no_sertifikat': '23P1005',
            'tertelusur_ke': 'LK-202-IDN',
            'terdaftar': true,
          },
          {
            'label': 'PRT PT100',
            'standard_id': 47,
            'merk': null,
            'serial_number': 'SH1/20',
            'no_sertifikat': 'SH1/20',
            'tertelusur_ke': 'SNSU-BSN',
            'terdaftar': true,
          },
        ],
        'field': [
          {
            'kode': 'standar_dicek.*.dipakai',
            'label': 'Usage Check',
            'tipe': 'centang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'standar_dicek.*.keterangan',
            'label': 'Keterangan',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'data_kalibrasi',
        'halaman': 1,
        'judul': 'PENGERJAAN',
        'field': [
          {
            'kode': 'tipe_pencelupan',
            'label': 'Thermometer Type',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'Partial Immersion',
                'label': 'Partial Immersion',
              },
              {
                'nilai': 'Total Immersion',
                'label': 'Total Immersion',
              },
              {
                'nilai': 'Complete Immersion',
                'label': 'Complete Immersion',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_bantu',
            'label': 'Oilbath Used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'satu',
                'label': 'Oil Bath 1 (SIDIK/079/2022)',
              },
              {
                'nilai': 'dua',
                'label': 'Oil Bath 2 (SIDIK/080/2022)',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi',
            'label': 'Lokasi Kalibrasi',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'lab',
                'label': 'Inlab',
              },
              {
                'nilai': 'onsite',
                'label': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi_nama',
            'label': 'Nama Tempat (Insitu)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'onsite',
              ],
            },
          },
          {
            'kode': 'room_id',
            'label': 'Ruangan (Inlab)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_ruangan',
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'lab',
              ],
            },
          },
          {
            'kode': 'calibration_method_id',
            'label': 'Calibration Method',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_metode',
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': true,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'pre_evaluasi',
        'halaman': 1,
        'judul': '1. Pre-Evaluation (UUT) — Ice Point 30 menit',
        'field': [
          {
            'kode': 'titik_es_1',
            'label': 'Ice Point X1',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'titik_es_2',
            'label': 'Ice Point X2',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'titik_es_3',
            'label': 'Ice Point X3',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'hasil',
        'halaman': 1,
        'judul': 'DATA HASIL KALIBRASI',
        'field': [
          {
            'kode': 'suhu_awal',
            'label': 'Suhu Ruangan — Awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_akhir',
            'label': 'Suhu Ruangan — Akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_awal',
            'label': 'Kelembaban — Awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_akhir',
            'label': 'Kelembaban — Akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'thermohygro_standard_id',
            'label': 'Environmental Meter Used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_thermohygro',
            'satuan': null,
            'pilihan': [
              {
                'nilai': '1',
                'label': 'TH-1',
                'grup': 'Inlab',
              },
              {
                'nilai': '3',
                'label': 'TH-3',
                'grup': 'Inlab',
              },
              {
                'nilai': '4',
                'label': 'TH-4',
                'grup': 'Inlab',
              },
              {
                'nilai': '5',
                'label': 'TH-5',
                'grup': 'Inlab',
              },
              {
                'nilai': '7',
                'label': 'TH-7',
                'grup': 'Inlab',
              },
              {
                'nilai': '2',
                'label': 'TH-2',
                'grup': 'Insitu',
              },
              {
                'nilai': '6',
                'label': 'TH-6',
                'grup': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'standar',
            'peran': 'standar',
            'judul': '2. Pembacaan Standard',
            'satuan': '°C',
            'judul_nilai': 'Set Point',
            'judul_pengulangan': 'Data Hasil Pengukuran/Pengulangan (PRT1…PRT5)',
            'pengulangan_arah': [
              {
                'ke': 1,
                'label': '0″',
              },
              {
                'ke': 2,
                'label': '20″',
              },
              {
                'ke': 3,
                'label': '40″',
              },
              {
                'ke': 4,
                'label': '60″',
              },
              {
                'ke': 5,
                'label': '80″',
              },
            ],
            'titik_bisa_diubah': true,
            'baris': [
              {
                'titik_ukur': 30,
                'label': '30 °C',
                'satuan': '°C',
                'standard_id': 45,
                'standard_nama': 'Temperature Calibrator Yokogawa CA 150 Handy Cal',
              },
              {
                'titik_ukur': 50,
                'label': '50 °C',
                'satuan': '°C',
                'standard_id': 45,
                'standard_nama': 'Temperature Calibrator Yokogawa CA 150 Handy Cal',
              },
              {
                'titik_ukur': 60,
                'label': '60 °C',
                'satuan': '°C',
                'standard_id': 45,
                'standard_nama': 'Temperature Calibrator Yokogawa CA 150 Handy Cal',
              },
              {
                'titik_ukur': 80,
                'label': '80 °C',
                'satuan': '°C',
                'standard_id': 45,
                'standard_nama': 'Temperature Calibrator Yokogawa CA 150 Handy Cal',
              },
              {
                'titik_ukur': 100,
                'label': '100 °C',
                'satuan': '°C',
                'standard_id': 45,
                'standard_nama': 'Temperature Calibrator Yokogawa CA 150 Handy Cal',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': '°C',
                'tipe': 'angka',
                'satuan': '°C',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
              4,
              5,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'uut',
            'peran': 'uut',
            'judul': '3. Pembacaan UUT',
            'satuan': '°C',
            'judul_nilai': 'Set Point',
            'judul_pengulangan': 'Data Hasil Pengukuran/Pengulangan (PRT1…PRT5)',
            'pengulangan_arah': [
              {
                'ke': 1,
                'label': '10″',
              },
              {
                'ke': 2,
                'label': '30″',
              },
              {
                'ke': 3,
                'label': '50″',
              },
              {
                'ke': 4,
                'label': '70″',
              },
              {
                'ke': 5,
                'label': '90″',
              },
            ],
            'titik_bisa_diubah': true,
            'baris': [
              {
                'titik_ukur': 30,
                'label': '30 °C',
                'satuan': '°C',
                'standard_id': 45,
                'standard_nama': 'Temperature Calibrator Yokogawa CA 150 Handy Cal',
              },
              {
                'titik_ukur': 50,
                'label': '50 °C',
                'satuan': '°C',
                'standard_id': 45,
                'standard_nama': 'Temperature Calibrator Yokogawa CA 150 Handy Cal',
              },
              {
                'titik_ukur': 60,
                'label': '60 °C',
                'satuan': '°C',
                'standard_id': 45,
                'standard_nama': 'Temperature Calibrator Yokogawa CA 150 Handy Cal',
              },
              {
                'titik_ukur': 80,
                'label': '80 °C',
                'satuan': '°C',
                'standard_id': 45,
                'standard_nama': 'Temperature Calibrator Yokogawa CA 150 Handy Cal',
              },
              {
                'titik_ukur': 100,
                'label': '100 °C',
                'satuan': '°C',
                'standard_id': 45,
                'standard_nama': 'Temperature Calibrator Yokogawa CA 150 Handy Cal',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': '°C',
                'tipe': 'angka',
                'satuan': '°C',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
              4,
              5,
            ],
          },
        ],
      },
      {
        'kode': 'penutup',
        'halaman': 1,
        'judul': 'Catatan & Tanda Tangan',
        'field': [
          {
            'kode': 'catatan_teknisi',
            'label': 'Catatan',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'teknisi.nama',
            'label': 'Calculated by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'reviewer.nama',
            'label': 'Signed by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
    ],
  };

  return bentuk;
}

/// Thermohygrometer (alat ke-20) — `SIDIK-IK-CAL-0518_Rev.4`, sesi master
/// `0312-CAL-624`.
Map<String, dynamic> contohBentukLembarKerjaThermohygro({bool untukAdmin = false}) {
  final bentuk = <String, dynamic>{
    'kode_dokumen': null,
    'kode_metode': 'SIDIK-IK-CAL-0518_Rev.4',
    'judul': 'Calibration Worksheet - Temperatur & Kelembapan (Thermohygro)',
    'jumlah_pengulangan': 5,
    'larutan_standar': [
      15,
      25,
      35,
      45,
      50,
    ],
    'satuan': '°C',
    'satuan_suhu': '°C',
    'satuan_campuran': true,
    'semua_kolom_opsional': true,
    'catatan_pengisian': 'Kolom yang belum bisa diisi di lapangan boleh dikosongin — lembar kerja tetap bisa dikirim. Alat ini punya DUA parameter: suhu (°C) dan kelembapan (%RH), masing-masing dengan tabel & U95 sendiri. Chamber kelembapan dipilih sistem dari set point-nya: ≥ 50 %RH BIOBASE, < 50 %RH GEA.',
    'bagian': [
      {
        'kode': 'identitas_alat',
        'halaman': 1,
        'judul': 'EQUIPMENT IDENTITY AND CUSTOMER DATA',
        'field': [
          {
            'kode': 'tanggal_terima',
            'label': 'Received Date',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_kalibrasi',
            'label': 'Calibration Date',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'equipment_id',
            'label': 'Equipment',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_alat',
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'equipment.nama_alat',
            'label': '1. Nama Alat',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_merk',
            'label': '2. Merk',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_model',
            'label': '3. Type',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_serial_number',
            'label': '4. No. Seri',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.rentang_ukur',
            'label': '5. Rentang Ukur Suhu',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.kapasitas',
            'label': '6. Kapasitas Suhu',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.resolusi',
            'label': '7. Resolusi Suhu',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.rentang_ukur_kelembaban',
            'label': '8. Rentang Ukur Humi.',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.kapasitas_kelembaban',
            'label': '9. Kapasitas Humi.',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.resolusi_kelembaban',
            'label': '10. Resolusi Humi.',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'pemilik',
        'halaman': 1,
        'judul': 'IDENTITAS CUSTOMER',
        'field': [
          {
            'kode': 'pemilik_nama',
            'label': '1. Nama Customer',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'pemilik_alamat',
            'label': '2. Alamat Customer',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'usage_check',
        'halaman': 1,
        'judul': 'STANDARD',
        'baris': [
          {
            'label': 'Temperature Humidity Meter',
            'standard_id': 50,
            'merk': null,
            'serial_number': '201701023483',
            'no_sertifikat': '201701023483',
            'tertelusur_ke': 'LK-361-IDN',
            'terdaftar': true,
          },
        ],
        'field': [
          {
            'kode': 'standar_dicek.*.dipakai',
            'label': 'Usage Check',
            'tipe': 'centang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'standar_dicek.*.keterangan',
            'label': 'Keterangan',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'data_kalibrasi',
        'halaman': 1,
        'judul': 'PENGERJAAN',
        'field': [
          {
            'kode': 'lokasi',
            'label': 'Lokasi Kalibrasi',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'lab',
                'label': 'Inlab',
              },
              {
                'nilai': 'onsite',
                'label': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi_nama',
            'label': 'Nama Tempat (Insitu)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'onsite',
              ],
            },
          },
          {
            'kode': 'room_id',
            'label': 'Ruangan (Inlab)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_ruangan',
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'lab',
              ],
            },
          },
          {
            'kode': 'calibration_method_id',
            'label': 'Calibration Method',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_metode',
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': true,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'hasil_suhu',
        'halaman': 1,
        'judul': '1. KALIBRASI SUHU (TEMPERATURE)',
        'field': [
          {
            'kode': 'suhu_awal',
            'label': 'Suhu Ruangan — Awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_akhir',
            'label': 'Suhu Ruangan — Akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_awal',
            'label': 'Kelembaban — Awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_akhir',
            'label': 'Kelembaban — Akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'thermohygro_standard_id',
            'label': 'Environmental Meter Used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_thermohygro',
            'satuan': null,
            'pilihan': [
              {
                'nilai': '1',
                'label': 'TH-1',
                'grup': 'Inlab',
              },
              {
                'nilai': '3',
                'label': 'TH-3',
                'grup': 'Inlab',
              },
              {
                'nilai': '4',
                'label': 'TH-4',
                'grup': 'Inlab',
              },
              {
                'nilai': '5',
                'label': 'TH-5',
                'grup': 'Inlab',
              },
              {
                'nilai': '7',
                'label': 'TH-7',
                'grup': 'Inlab',
              },
              {
                'nilai': '2',
                'label': 'TH-2',
                'grup': 'Insitu',
              },
              {
                'nilai': '6',
                'label': 'TH-6',
                'grup': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'suhu_standar',
            'peran': 'standar',
            'judul': 'Pembacaan Standard [CHAMBER BIOBASE]',
            'satuan': '°C',
            'judul_nilai': 'Set Point',
            'judul_pengulangan': 'Data Hasil Pengukuran/Pengulangan (X1…X5)',
            'pengulangan_arah': [
              {
                'ke': 1,
                'label': 'X1',
              },
              {
                'ke': 2,
                'label': 'X2',
              },
              {
                'ke': 3,
                'label': 'X3',
              },
              {
                'ke': 4,
                'label': 'X4',
              },
              {
                'ke': 5,
                'label': 'X5',
              },
            ],
            'titik_bisa_diubah': true,
            'baris': [
              {
                'titik_ukur': 15,
                'label': '15 °C',
                'satuan': '°C',
                'standard_id': 50,
                'standard_nama': 'Temperature Humidity Meter',
              },
              {
                'titik_ukur': 25,
                'label': '25 °C',
                'satuan': '°C',
                'standard_id': 50,
                'standard_nama': 'Temperature Humidity Meter',
              },
              {
                'titik_ukur': 35,
                'label': '35 °C',
                'satuan': '°C',
                'standard_id': 50,
                'standard_nama': 'Temperature Humidity Meter',
              },
              {
                'titik_ukur': 45,
                'label': '45 °C',
                'satuan': '°C',
                'standard_id': 50,
                'standard_nama': 'Temperature Humidity Meter',
              },
              {
                'titik_ukur': 50,
                'label': '50 °C',
                'satuan': '°C',
                'standard_id': 50,
                'standard_nama': 'Temperature Humidity Meter',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': '°C',
                'tipe': 'angka',
                'satuan': '°C',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
              4,
              5,
            ],
            'parameter': 'suhu',
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'suhu_uut',
            'peran': 'uut',
            'judul': 'Pembacaan UUT',
            'satuan': '°C',
            'judul_nilai': 'Set Point',
            'judul_pengulangan': 'Data Hasil Pengukuran/Pengulangan (X1…X5)',
            'pengulangan_arah': [
              {
                'ke': 1,
                'label': 'X1',
              },
              {
                'ke': 2,
                'label': 'X2',
              },
              {
                'ke': 3,
                'label': 'X3',
              },
              {
                'ke': 4,
                'label': 'X4',
              },
              {
                'ke': 5,
                'label': 'X5',
              },
            ],
            'titik_bisa_diubah': true,
            'baris': [
              {
                'titik_ukur': 15,
                'label': '15 °C',
                'satuan': '°C',
                'standard_id': 50,
                'standard_nama': 'Temperature Humidity Meter',
              },
              {
                'titik_ukur': 25,
                'label': '25 °C',
                'satuan': '°C',
                'standard_id': 50,
                'standard_nama': 'Temperature Humidity Meter',
              },
              {
                'titik_ukur': 35,
                'label': '35 °C',
                'satuan': '°C',
                'standard_id': 50,
                'standard_nama': 'Temperature Humidity Meter',
              },
              {
                'titik_ukur': 45,
                'label': '45 °C',
                'satuan': '°C',
                'standard_id': 50,
                'standard_nama': 'Temperature Humidity Meter',
              },
              {
                'titik_ukur': 50,
                'label': '50 °C',
                'satuan': '°C',
                'standard_id': 50,
                'standard_nama': 'Temperature Humidity Meter',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': '°C',
                'tipe': 'angka',
                'satuan': '°C',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
              4,
              5,
            ],
            'parameter': 'suhu',
          },
        ],
      },
      {
        'kode': 'hasil_kelembaban',
        'halaman': 1,
        'judul': '2. KALIBRASI KELEMBAPAN (HUMIDITY)',
        'field': const [],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'kelembaban_standar',
            'peran': 'standar',
            'judul': 'Pembacaan Standard',
            'satuan': '%RH',
            'judul_nilai': 'Set Point',
            'judul_pengulangan': 'Data Hasil Pengukuran/Pengulangan (X1…X5)',
            'pengulangan_arah': [
              {
                'ke': 1,
                'label': 'X1',
              },
              {
                'ke': 2,
                'label': 'X2',
              },
              {
                'ke': 3,
                'label': 'X3',
              },
              {
                'ke': 4,
                'label': 'X4',
              },
              {
                'ke': 5,
                'label': 'X5',
              },
            ],
            'titik_bisa_diubah': true,
            'baris': [
              {
                'titik_ukur': 30,
                'label': '30 %RH',
                'satuan': '%RH',
                'standard_id': 50,
                'standard_nama': 'Temperature Humidity Meter',
              },
              {
                'titik_ukur': 49,
                'label': '49 %RH',
                'satuan': '%RH',
                'standard_id': 50,
                'standard_nama': 'Temperature Humidity Meter',
              },
              {
                'titik_ukur': 50,
                'label': '50 %RH',
                'satuan': '%RH',
                'standard_id': 50,
                'standard_nama': 'Temperature Humidity Meter',
              },
              {
                'titik_ukur': 70,
                'label': '70 %RH',
                'satuan': '%RH',
                'standard_id': 50,
                'standard_nama': 'Temperature Humidity Meter',
              },
              {
                'titik_ukur': 90,
                'label': '90 %RH',
                'satuan': '%RH',
                'standard_id': 50,
                'standard_nama': 'Temperature Humidity Meter',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': '%RH',
                'tipe': 'angka',
                'satuan': '%RH',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
              4,
              5,
            ],
            'parameter': 'kelembaban',
            'chamber_per_baris': [
              {
                'titik_ukur': 30,
                'chamber': 'gea',
              },
              {
                'titik_ukur': 49,
                'chamber': 'gea',
              },
              {
                'titik_ukur': 50,
                'chamber': 'biobase',
              },
              {
                'titik_ukur': 70,
                'chamber': 'biobase',
              },
              {
                'titik_ukur': 90,
                'chamber': 'biobase',
              },
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'kelembaban_uut',
            'peran': 'uut',
            'judul': 'Pembacaan UUT',
            'satuan': '%RH',
            'judul_nilai': 'Set Point',
            'judul_pengulangan': 'Data Hasil Pengukuran/Pengulangan (X1…X5)',
            'pengulangan_arah': [
              {
                'ke': 1,
                'label': 'X1',
              },
              {
                'ke': 2,
                'label': 'X2',
              },
              {
                'ke': 3,
                'label': 'X3',
              },
              {
                'ke': 4,
                'label': 'X4',
              },
              {
                'ke': 5,
                'label': 'X5',
              },
            ],
            'titik_bisa_diubah': true,
            'baris': [
              {
                'titik_ukur': 30,
                'label': '30 %RH',
                'satuan': '%RH',
                'standard_id': 50,
                'standard_nama': 'Temperature Humidity Meter',
              },
              {
                'titik_ukur': 49,
                'label': '49 %RH',
                'satuan': '%RH',
                'standard_id': 50,
                'standard_nama': 'Temperature Humidity Meter',
              },
              {
                'titik_ukur': 50,
                'label': '50 %RH',
                'satuan': '%RH',
                'standard_id': 50,
                'standard_nama': 'Temperature Humidity Meter',
              },
              {
                'titik_ukur': 70,
                'label': '70 %RH',
                'satuan': '%RH',
                'standard_id': 50,
                'standard_nama': 'Temperature Humidity Meter',
              },
              {
                'titik_ukur': 90,
                'label': '90 %RH',
                'satuan': '%RH',
                'standard_id': 50,
                'standard_nama': 'Temperature Humidity Meter',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': '%RH',
                'tipe': 'angka',
                'satuan': '%RH',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
              4,
              5,
            ],
            'parameter': 'kelembaban',
          },
        ],
      },
      {
        'kode': 'penutup',
        'halaman': 1,
        'judul': 'Catatan & Tanda Tangan',
        'field': [
          {
            'kode': 'catatan_teknisi',
            'label': 'Catatan',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'teknisi.nama',
            'label': 'Calculated by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'reviewer.nama',
            'label': 'Signed by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
    ],
  };

  return bentuk;
}
