/// Bentuk lembar kerja contoh **Dial Indicator, Jangka Sorong, Sieve Mesh**
/// (kelompok Panjang, alat ke-30..32).
///
/// DIGENERATE `docs/skrip/gen-contoh-lembar-kerja.php` di repo API — jangan
/// disunting tangan. Micrometer & Height Gauge tetap di
/// `contoh_lembar_kerja_panjang.dart`; berkas ini terpisah supaya berkas lama
/// yang tidak digenerate tidak ikut tertimpa.
///
/// ## Yang cuma ada di lembar-lembar ini
///
///  1. **Dial Indicator** — nominal tiap baris TUMPUKAN balok ukur (`kolom_baris`
///     `nominal` bertipe `daftar_angka`, mis. `2,5+1,3+1,2`), enam penunjukan
///     berlabel UP/DOWN (`pengulangan_arah`), dan field tingkat-bagian
///     `balok_pra_evaluasi` yang juga `daftar_angka`. Koma di dalamnya koma
///     DESIMAL, bukan pemisah.
///  2. **Jangka Sorong** — TIGA tabel titik (`simpan_ke`
///     `measurements[].js_outside|js_inside|js_depth`) yang digabung per POSISI
///     baris; server memecahnya ke `titik_ke` 1.. / 101.. / 201...
///  3. **Sieve Mesh** — opening TIDAK lewat `measurements[]`: tabelnya
///     `simpan_ke: spesifikasi_alat.sieve.opening` dengan tiga kolom
///     (warp/weft/kawat), baris = nomor opening (sampai 100).
library;

/// Bentuk lembar kerja contoh **Dial Indicator**.
///
/// Kode profil `dial_indicator`, satuan `mm`, kertas `SIDIK-FM-CAL-0526_Rev.3`.
Map<String, dynamic> contohBentukLembarKerjaDialIndicator({
  bool untukAdmin = false,
}) {
  return {
    'kode_dokumen': 'SIDIK-FM-CAL-0526_Rev.3',
    'kode_metode': 'SIDIK-IK-CAL-0519_Rev.3',
    'nomor_lingkup': 'LK-285-IDN',
    'judul': 'Calibration Work Sheet - Dial Indicator',
    'jumlah_pengulangan': 6,
    'satuan': 'mm',
    'satuan_suhu': '°C',
    'semua_kolom_opsional': true,
    'catatan_pengisian': 'Isi SATUAN alat lebih dulu — kapasitas, resolusi, blok Evaluation, dan penunjukan dial diketik dalam satuan itu. Balok ukur SELALU mm dan wajib dari daftar Gauge Block terkalibrasi; tulis tumpukannya dengan tanda + (mis. 2,5+1,3+1,2). Blok Evaluation wajib diisi: dari situ ketidakpastian keterulangan lahir.',
    'budget_ketidakpastian': {
      'tersedia': true,
      'sumber': 'Master Olah Data_Dial Indicator.xlsm',
      'catatan': 'Sepuluh komponen tingkat-SESI dalam mm, k dari t-Student (v_eff), lantai CMC per pita kapasitas. Sesi tanpa pita CMC, blok Evaluation < 2 pembacaan, balok ukur Evaluation kosong/tak terdaftar, atau resolusi kosong TIDAK diterbitkan.',
    },
    'bagian': [
      {
        'kode': 'identitas_alat',
        'halaman': 1,
        'judul': 'Identitas Alat',
        'field': [
          {
            'kode': 'equipment_id',
            'label': 'Pilih Alat',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_alat',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'equipment.nama_alat',
            'label': 'Nama Alat',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_merk',
            'label': 'Merk',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_model',
            'label': 'Type',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_serial_number',
            'label': 'Serial Number',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.dial_indicator.satuan',
            'label': 'Satuan Alat',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'mm',
                'label': 'mm',
              },
              {
                'nilai': 'inch',
                'label': 'inch',
              },
              {
                'nilai': 'µm',
                'label': 'µm',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.rentang_ukur',
            'label': 'Rentang Ukur',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.dial_indicator.kapasitas_mm',
            'label': 'Capacity (satuan alat)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.dial_indicator.resolusi_mm',
            'label': 'Resolusi (satuan alat)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_terima',
            'label': 'Received Date',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_kalibrasi',
            'label': 'Calibration Date',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_awal',
            'label': 'Suhu Ruangan — awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_akhir',
            'label': 'Suhu Ruangan — akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_awal',
            'label': 'Kelembapan — awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_akhir',
            'label': 'Kelembapan — akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi',
            'label': 'Lokasi Kalibrasi',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'lab',
                'label': 'Inlab',
              },
              {
                'nilai': 'onsite',
                'label': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'room_id',
            'label': 'Ruangan (Inlab)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_ruangan',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'lab',
              ],
            },
          },
          {
            'kode': 'lokasi_nama',
            'label': 'Nama Tempat (Insitu)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'onsite',
              ],
            },
          },
          {
            'kode': 'thermohygro_standard_id',
            'label': 'Thermohygro used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_thermohygro',
            'satuan': null,
            'pilihan': [
              {
                'nilai': '1',
                'label': 'TH-1',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '2',
                'label': 'TH-2',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '3',
                'label': 'TH-3',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '4',
                'label': 'TH-4',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '5',
                'label': 'TH-5',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '6',
                'label': 'TH-6',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '7',
                'label': 'TH-7',
                'grup': 'Thermohygro lab',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'pemilik',
        'halaman': 1,
        'judul': 'Data Customer',
        'field': [
          {
            'kode': 'pemilik_nama',
            'label': 'Owner',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'pemilik_alamat',
            'label': 'Address',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'nomor_order',
            'label': 'Order Number',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'usage_check',
        'halaman': 1,
        'judul': 'Standard Used',
        'baris': [
          {
            'label': 'Gauge Block/Metrology/GB-9122-0/0',
            'standard_id': 61,
            'serial_number': '160006',
            'no_sertifikat': '160006',
            'tertelusur_ke': 'LK-410-IDN',
            'terdaftar': true,
          },
        ],
        'field': [
          {
            'kode': 'standar_dicek.*.dipakai',
            'label': 'Usage Check',
            'tipe': 'centang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'standar_dicek.*.keterangan',
            'label': 'Keterangan',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'hasil',
        'halaman': 1,
        'judul': 'Data Kalibrasi',
        'field': <dynamic>[],
        'tabel': [
          {
            'kolom_baris': [
              {
                'kode': 'nominal',
                'label': 'Nominal Balok Ukur (mm, pisahkan dengan +)',
                'tipe': 'daftar_angka',
                'wajib': false,
                'sumber': null,
                'satuan': 'mm',
                'pilihan': <dynamic>[],
                'hanya_admin': false,
                'tampil_kalau': null,
              },
            ],
            'tahap': 'sesudah_adjustment',
            'grup': 'di_pembacaan',
            'judul': 'Pembacaan Alat',
            'satuan': 'mm',
            'judul_nilai': 'Nominal Balok Ukur',
            'judul_pengulangan': 'Pembacaan',
            'pengulangan_arah': [
              {
                'ke': 1,
                'label': 'UP X1',
              },
              {
                'ke': 2,
                'label': 'UP X2',
              },
              {
                'ke': 3,
                'label': 'UP X3',
              },
              {
                'ke': 4,
                'label': 'DOWN X1',
              },
              {
                'ke': 5,
                'label': 'DOWN X2',
              },
              {
                'ke': 6,
                'label': 'DOWN X3',
              },
            ],
            'titik_bisa_diubah': true,
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': 0.0,
                'label': 'Titik 1',
                'satuan': 'mm',
              },
              {
                'nomor': 2,
                'titik_ukur': 0.0,
                'label': 'Titik 2',
                'satuan': 'mm',
              },
              {
                'nomor': 3,
                'titik_ukur': 0.0,
                'label': 'Titik 3',
                'satuan': 'mm',
              },
              {
                'nomor': 4,
                'titik_ukur': 0.0,
                'label': 'Titik 4',
                'satuan': 'mm',
              },
              {
                'nomor': 5,
                'titik_ukur': 0.0,
                'label': 'Titik 5',
                'satuan': 'mm',
              },
              {
                'nomor': 6,
                'titik_ukur': 0.0,
                'label': 'Titik 6',
                'satuan': 'mm',
              },
              {
                'nomor': 7,
                'titik_ukur': 0.0,
                'label': 'Titik 7',
                'satuan': 'mm',
              },
              {
                'nomor': 8,
                'titik_ukur': 0.0,
                'label': 'Titik 8',
                'satuan': 'mm',
              },
              {
                'nomor': 9,
                'titik_ukur': 0.0,
                'label': 'Titik 9',
                'satuan': 'mm',
              },
              {
                'nomor': 10,
                'titik_ukur': 0.0,
                'label': 'Titik 10',
                'satuan': 'mm',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'mm',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
              4,
              5,
              6,
            ],
          },
        ],
      },
      {
        'kode': 'evaluasi',
        'halaman': 1,
        'judul': 'Evaluasi',
        'field': [
          {
            'kode': 'spesifikasi_alat.dial_indicator.balok_pra_evaluasi',
            'label': 'Nominal Balok Ukur Evaluasi (mm, pisahkan dengan +)',
            'tipe': 'daftar_angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'mm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'pra_pembacaan',
            'judul': 'Evaluasi (X1..X10)',
            'satuan': 'mm',
            'judul_nilai': 'Evaluasi',
            'judul_pengulangan': 'Pembacaan',
            'titik_bisa_diubah': false,
            'offset_kunci': 1000,
            'simpan_ke': 'spesifikasi_alat.dial_indicator.pra_evaluasi',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Evaluasi',
                'satuan': 'mm',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'mm',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
            ],
          },
        ],
      },
      {
        'kode': 'penutup',
        'halaman': 1,
        'judul': 'Catatan & Tanda Tangan',
        'field': [
          {
            'kode': 'catatan_teknisi',
            'label': 'Catatan',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'teknisi.nama',
            'label': 'Dikalibrasi Oleh',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'reviewer.nama',
            'label': 'Diperiksa Oleh',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
    ],
  };
}

/// Bentuk lembar kerja contoh **Vernier Caliper**.
///
/// Kode profil `jangka_sorong`, satuan `mm`, kertas `SIDIK-FM-CAL-0527_Rev.2`.
Map<String, dynamic> contohBentukLembarKerjaJangkaSorong({
  bool untukAdmin = false,
}) {
  return {
    'kode_dokumen': 'SIDIK-FM-CAL-0527_Rev.2',
    'kode_metode': 'SIDIK-IK-CAL-0520_Rev.2',
    'nomor_lingkup': 'LK-285-IDN',
    'judul': 'Calibration Work Sheet - Jangka Sorong',
    'jumlah_pengulangan': 10,
    'satuan': 'mm',
    'satuan_suhu': '°C',
    'semua_kolom_opsional': true,
    'catatan_pengisian': 'Isi SATUAN alat lebih dulu (mm/inch) — dia yang mengubah pembacaan dan blok Evaluation ke mm. Nominal ketiga tabel SUDAH DIPATOK dari daftar Caliper Checker dan balok ukur terkalibrasi; baris yang tidak dipakai biarkan kosong. Kedua blok Evaluation WAJIB diisi: dari situ repeatability Outside dan Inside lahir. Koma maupun titik diterima sebagai pemisah desimal.',
    'budget_ketidakpastian': {
      'tersedia': true,
      'sumber': 'Master Olah Data Caliper 2026 (std caliper checker+gb).xlsm',
      'catatan': 'Tiga budget tingkat-SESI dalam mm — Outside & Inside 10 komponen, Depth 11 — dengan lantai CMC 0,015 mm. Kapasitas di luar 0-300 mm, resolusi kosong, atau Evaluation kurang dari dua pembacaan TIDAK diterbitkan.',
    },
    'bagian': [
      {
        'kode': 'identitas_alat',
        'halaman': 1,
        'judul': 'Identitas Alat',
        'field': [
          {
            'kode': 'equipment_id',
            'label': 'Pilih Alat',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_alat',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'equipment.nama_alat',
            'label': 'Nama Alat',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_merk',
            'label': 'Merk',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_model',
            'label': 'Type',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_serial_number',
            'label': 'No. Seri',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.jangka_sorong.satuan',
            'label': 'Satuan Alat',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'mm',
                'label': 'mm',
              },
              {
                'nilai': 'inch',
                'label': 'inch',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.rentang_ukur',
            'label': 'Rentang Ukur',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.jangka_sorong.kapasitas_mm',
            'label': 'Kapasitas Max.',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'mm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.jangka_sorong.resolusi_mm',
            'label': 'Resolusi Alat',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'mm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_terima',
            'label': 'Tgl. Diterima',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_kalibrasi',
            'label': 'Tgl. Kalibrasi',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_awal',
            'label': 'Suhu Ruangan — awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_akhir',
            'label': 'Suhu Ruangan — akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_awal',
            'label': 'Kelembapan — awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_akhir',
            'label': 'Kelembapan — akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.jangka_sorong.kerataan_muka_ukur',
            'label': 'Kerataan Muka Ukur',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'baik',
                'label': 'Baik',
              },
              {
                'nilai': 'buruk',
                'label': 'Buruk',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi',
            'label': 'Lokasi Kalibrasi',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'lab',
                'label': 'Inlab',
              },
              {
                'nilai': 'onsite',
                'label': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'room_id',
            'label': 'Ruangan (Inlab)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_ruangan',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'lab',
              ],
            },
          },
          {
            'kode': 'lokasi_nama',
            'label': 'Nama Tempat (Insitu)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'onsite',
              ],
            },
          },
          {
            'kode': 'thermohygro_standard_id',
            'label': 'Environmental Meter Used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_thermohygro',
            'satuan': null,
            'pilihan': [
              {
                'nilai': '1',
                'label': 'TH-1',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '2',
                'label': 'TH-2',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '3',
                'label': 'TH-3',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '4',
                'label': 'TH-4',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '5',
                'label': 'TH-5',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '6',
                'label': 'TH-6',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '7',
                'label': 'TH-7',
                'grup': 'Thermohygro lab',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'pemilik',
        'halaman': 1,
        'judul': 'Data Customer',
        'field': [
          {
            'kode': 'pemilik_nama',
            'label': 'Nama Customer',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'pemilik_alamat',
            'label': 'Alamat Customer',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'nomor_order',
            'label': 'Order Number',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'usage_check',
        'halaman': 1,
        'judul': 'Standard Used',
        'baris': [
          {
            'label': 'Caliper Checker/Metrology/CMG-9060C',
            'standard_id': 62,
            'serial_number': '800035',
            'no_sertifikat': '800035',
            'tertelusur_ke': 'LK-404-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Gauge Block/Metrology/GB-9122-0',
            'standard_id': 61,
            'serial_number': '160006',
            'no_sertifikat': '160006',
            'tertelusur_ke': 'LK-410-IDN',
            'terdaftar': true,
          },
        ],
        'field': [
          {
            'kode': 'standar_dicek.*.dipakai',
            'label': 'Usage Check',
            'tipe': 'centang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'standar_dicek.*.keterangan',
            'label': 'Keterangan',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'hasil_outside',
        'halaman': 1,
        'judul': 'Outside Measurement',
        'field': <dynamic>[],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'outside',
            'judul': 'Outside Measurement',
            'satuan': 'mm',
            'judul_nilai': 'Nominal Caliper Checker',
            'judul_pengulangan': 'Pembacaan Alat',
            'titik_bisa_diubah': false,
            'offset_kunci': 0,
            'simpan_ke': 'measurements[].js_outside',
            'pengulangan_arah': [
              {
                'ke': 1,
                'label': 'X1',
              },
              {
                'ke': 2,
                'label': 'X1\'',
              },
              {
                'ke': 3,
                'label': 'X2',
              },
              {
                'ke': 4,
                'label': 'X2\'',
              },
              {
                'ke': 5,
                'label': 'X3',
              },
              {
                'ke': 6,
                'label': 'X3\'',
              },
              {
                'ke': 7,
                'label': 'X4',
              },
              {
                'ke': 8,
                'label': 'X4\'',
              },
              {
                'ke': 9,
                'label': 'X5',
              },
              {
                'ke': 10,
                'label': 'X5\'',
              },
            ],
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': 0.0,
                'label': '0',
                'satuan': 'mm',
              },
              {
                'nomor': 2,
                'titik_ukur': 25.0,
                'label': '25',
                'satuan': 'mm',
              },
              {
                'nomor': 3,
                'titik_ukur': 50.0,
                'label': '50',
                'satuan': 'mm',
              },
              {
                'nomor': 4,
                'titik_ukur': 100.0,
                'label': '100',
                'satuan': 'mm',
              },
              {
                'nomor': 5,
                'titik_ukur': 150.0,
                'label': '150',
                'satuan': 'mm',
              },
              {
                'nomor': 6,
                'titik_ukur': 200.0,
                'label': '200',
                'satuan': 'mm',
              },
              {
                'nomor': 7,
                'titik_ukur': 300.0,
                'label': '300',
                'satuan': 'mm',
              },
              {
                'nomor': 8,
                'titik_ukur': 400.0,
                'label': '400',
                'satuan': 'mm',
              },
              {
                'nomor': 9,
                'titik_ukur': 500.0,
                'label': '500',
                'satuan': 'mm',
              },
              {
                'nomor': 10,
                'titik_ukur': 550.0,
                'label': '550',
                'satuan': 'mm',
              },
              {
                'nomor': 11,
                'titik_ukur': 600.0,
                'label': '600',
                'satuan': 'mm',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'mm',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
            ],
          },
        ],
      },
      {
        'kode': 'evaluasi',
        'halaman': 1,
        'judul': 'Evaluation',
        'field': <dynamic>[],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'pra_pembacaan_outside',
            'judul': 'Evaluation Outside (pembacaan berulang di kapasitas)',
            'satuan': 'mm',
            'judul_nilai': 'Evaluation',
            'judul_pengulangan': 'Pembacaan',
            'titik_bisa_diubah': false,
            'offset_kunci': 3000,
            'simpan_ke': 'spesifikasi_alat.jangka_sorong.pra_evaluasi_outside',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Evaluation Outside',
                'satuan': 'mm',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'mm',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'pra_pembacaan_inside',
            'judul': 'Evaluation Inside (pembacaan berulang di kapasitas)',
            'satuan': 'mm',
            'judul_nilai': 'Evaluation',
            'judul_pengulangan': 'Pembacaan',
            'titik_bisa_diubah': false,
            'offset_kunci': 4000,
            'simpan_ke': 'spesifikasi_alat.jangka_sorong.pra_evaluasi_inside',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Evaluation Inside',
                'satuan': 'mm',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'mm',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
            ],
          },
        ],
      },
      {
        'kode': 'hasil_inside',
        'halaman': 1,
        'judul': 'Inside Measurement',
        'field': <dynamic>[],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'inside',
            'judul': 'Inside Measurement',
            'satuan': 'mm',
            'judul_nilai': 'Nominal Caliper Checker',
            'judul_pengulangan': 'Pembacaan Alat',
            'titik_bisa_diubah': false,
            'offset_kunci': 1000,
            'simpan_ke': 'measurements[].js_inside',
            'pengulangan_arah': [
              {
                'ke': 1,
                'label': 'X1',
              },
              {
                'ke': 2,
                'label': 'X2',
              },
              {
                'ke': 3,
                'label': 'X3',
              },
              {
                'ke': 4,
                'label': 'X4',
              },
              {
                'ke': 5,
                'label': 'X5',
              },
            ],
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': 0.0,
                'label': '0',
                'satuan': 'mm',
              },
              {
                'nomor': 2,
                'titik_ukur': 25.0,
                'label': '25',
                'satuan': 'mm',
              },
              {
                'nomor': 3,
                'titik_ukur': 50.0,
                'label': '50',
                'satuan': 'mm',
              },
              {
                'nomor': 4,
                'titik_ukur': 100.0,
                'label': '100',
                'satuan': 'mm',
              },
              {
                'nomor': 5,
                'titik_ukur': 150.0,
                'label': '150',
                'satuan': 'mm',
              },
              {
                'nomor': 6,
                'titik_ukur': 200.0,
                'label': '200',
                'satuan': 'mm',
              },
              {
                'nomor': 7,
                'titik_ukur': 300.0,
                'label': '300',
                'satuan': 'mm',
              },
              {
                'nomor': 8,
                'titik_ukur': 400.0,
                'label': '400',
                'satuan': 'mm',
              },
              {
                'nomor': 9,
                'titik_ukur': 500.0,
                'label': '500',
                'satuan': 'mm',
              },
              {
                'nomor': 10,
                'titik_ukur': 550.0,
                'label': '550',
                'satuan': 'mm',
              },
              {
                'nomor': 11,
                'titik_ukur': 600.0,
                'label': '600',
                'satuan': 'mm',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'mm',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
              4,
              5,
            ],
          },
        ],
      },
      {
        'kode': 'hasil_depth',
        'halaman': 1,
        'judul': 'Depth Measurement (Kedalaman < 50 mm)',
        'field': <dynamic>[],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'depth',
            'judul': 'Depth Measurement (Kedalaman < 50 mm)',
            'satuan': 'mm',
            'judul_nilai': 'Nominal Gauge Block',
            'judul_pengulangan': 'Pembacaan Alat',
            'titik_bisa_diubah': false,
            'offset_kunci': 2000,
            'simpan_ke': 'measurements[].js_depth',
            'pengulangan_arah': [
              {
                'ke': 1,
                'label': 'X1',
              },
              {
                'ke': 2,
                'label': 'X2',
              },
              {
                'ke': 3,
                'label': 'X3',
              },
              {
                'ke': 4,
                'label': 'X4',
              },
              {
                'ke': 5,
                'label': 'X5',
              },
            ],
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': 10.0,
                'label': '7,5 + 2,5 = 10',
                'satuan': 'mm',
              },
              {
                'nomor': 2,
                'titik_ukur': 20.0,
                'label': '11 + 9 = 20',
                'satuan': 'mm',
              },
              {
                'nomor': 3,
                'titik_ukur': 30.0,
                'label': '21 + 9 = 30',
                'satuan': 'mm',
              },
              {
                'nomor': 4,
                'titik_ukur': 40.0,
                'label': '40',
                'satuan': 'mm',
              },
              {
                'nomor': 5,
                'titik_ukur': 50.0,
                'label': '50',
                'satuan': 'mm',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'mm',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
              4,
              5,
            ],
          },
        ],
      },
      {
        'kode': 'kesejajaran',
        'halaman': 1,
        'judul': 'Pengukuran Kesejajaran Muka Ukur (Outside)',
        'field': <dynamic>[],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'kesejajaran',
            'judul': 'Kesejajaran Muka Ukur',
            'satuan': 'mm',
            'judul_nilai': 'Posisi',
            'judul_pengulangan': 'Nilai',
            'titik_bisa_diubah': false,
            'offset_kunci': 5000,
            'simpan_ke': 'spesifikasi_alat.jangka_sorong.kesejajaran',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': 1.0,
                'label': 'Atas',
                'satuan': 'mm',
              },
              {
                'nomor': 2,
                'titik_ukur': 2.0,
                'label': 'Tengah',
                'satuan': 'mm',
              },
              {
                'nomor': 3,
                'titik_ukur': 3.0,
                'label': 'Bawah',
                'satuan': 'mm',
              },
            ],
            'kolom': [
              {
                'kode': 'nominal',
                'label': 'Nominal',
                'tipe': 'angka',
                'satuan': 'mm',
              },
              {
                'kode': 'pembacaan',
                'label': 'Pembacaan',
                'tipe': 'angka',
                'satuan': 'mm',
              },
            ],
            'pengulangan': [
              1,
            ],
          },
        ],
      },
      {
        'kode': 'penutup',
        'halaman': 1,
        'judul': 'Catatan & Tanda Tangan',
        'field': [
          {
            'kode': 'catatan_teknisi',
            'label': 'Catatan',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'teknisi.nama',
            'label': 'Dikalibrasi Oleh',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'reviewer.nama',
            'label': 'Diperiksa Oleh',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
    ],
  };
}

/// Bentuk lembar kerja contoh **Sieve**.
///
/// Kode profil `sieve`, satuan `mm`, kertas `SIDIK-FM-CAL-0536_Rev.2`.
Map<String, dynamic> contohBentukLembarKerjaSieve({
  bool untukAdmin = false,
}) {
  return {
    'kode_dokumen': 'SIDIK-FM-CAL-0536_Rev.2',
    'kode_metode': 'SIDIK-IK-CAL-0526_Rev.3',
    'nomor_lingkup': 'LK-285-IDN',
    'judul': 'Calibration Worksheet - Sieve Mesh',
    'jumlah_pengulangan': 1,
    'satuan': 'mm',
    'satuan_suhu': '°C',
    'semua_kolom_opsional': true,
    'catatan_pengisian': 'Isi tipe sieve, nominal + satuan, dan standar yang dipakai LEBIH DULU — ketiganya menentukan batas MPE ASTM E11, jumlah minimum opening, dan budget. Nominal wajib persis ukuran ASTM E11 (penanda inch ditulis dalam inch, mis. 0,75). Opening diisi berurutan dari nomor 1: opening 1..6 WAJIB lengkap karena ketidakpastian pengulangan diambil dari keenamnya. Jumlah opening minimal mengikuti tabel (Inspection 19 mm = 15). Koma atau titik desimal sama-sama diterima.',
    'budget_ketidakpastian': {
      'tersedia': true,
      'sumber': 'Master Olah Data_Sieve Mesh.xlsm',
      'catatan': 'Tiga budget tingkat-SESI (warp, weft, Ø kawat) dalam mm, enam komponen masing-masing, k = 2. Lantai CMC = yang lebih besar dari pita lampiran dan pita master. Sesi dengan nominal di luar Tabel MPE, opening di bawah minimum, opening 1..6 tidak lengkap, standar kedaluwarsa, atau tanpa pita CMC TIDAK diterbitkan.',
    },
    'bagian': [
      {
        'kode': 'identitas_alat',
        'halaman': 1,
        'judul': 'Equipment Identity and Customer Data',
        'field': [
          {
            'kode': 'equipment_id',
            'label': 'Pilih Alat',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_alat',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'equipment.nama_alat',
            'label': 'Name',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_model',
            'label': 'Type/Model',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_serial_number',
            'label': 'Serial Number',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_merk',
            'label': 'Merk/Manufacture',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.sieve.tipe',
            'label': 'Tipe Sieve',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'compliance',
                'label': 'Compliance',
              },
              {
                'nilai': 'inspection',
                'label': 'Inspection',
              },
              {
                'nilai': 'calibration',
                'label': 'Calibration',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.sieve.satuan',
            'label': 'Satuan Nominal',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'mm',
                'label': 'mm',
              },
              {
                'nilai': 'inch',
                'label': 'inch',
              },
              {
                'nilai': 'µm',
                'label': 'µm',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.sieve.nominal',
            'label': 'Range/Nominal Sieve',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.sieve.jumlah_opening_total',
            'label': 'Jumlah total opening (untuk ukuran "all")',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_terima',
            'label': 'Received Date',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_kalibrasi',
            'label': 'Calibration Date',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_awal',
            'label': 'Suhu — First',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_akhir',
            'label': 'Suhu — End',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_awal',
            'label': 'Kelembapan — First',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_akhir',
            'label': 'Kelembapan — End',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi',
            'label': 'Lokasi Kalibrasi',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'lab',
                'label': 'Inlab',
              },
              {
                'nilai': 'onsite',
                'label': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'room_id',
            'label': 'Ruangan (Inlab)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_ruangan',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'lab',
              ],
            },
          },
          {
            'kode': 'lokasi_nama',
            'label': 'Nama Tempat (Insitu)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'onsite',
              ],
            },
          },
          {
            'kode': 'thermohygro_standard_id',
            'label': 'Thermohygro Used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_thermohygro',
            'satuan': null,
            'pilihan': [
              {
                'nilai': '1',
                'label': 'TH-1',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '2',
                'label': 'TH-2',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '3',
                'label': 'TH-3',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '4',
                'label': 'TH-4',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '5',
                'label': 'TH-5',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '6',
                'label': 'TH-6',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '7',
                'label': 'TH-7',
                'grup': 'Thermohygro lab',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'pemilik',
        'halaman': 1,
        'judul': 'Owner',
        'field': [
          {
            'kode': 'pemilik_nama',
            'label': 'Name',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'pemilik_alamat',
            'label': 'Address',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'nomor_order',
            'label': 'Order Number',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'usage_check',
        'halaman': 1,
        'judul': 'Standard',
        'baris': [
          {
            'label': 'Digital Microscope/Dino-Lite',
            'standard_id': 64,
            'serial_number': 'B1401068',
            'no_sertifikat': 'B1401068',
            'tertelusur_ke': 'LK-410-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Digital Caliper Tesa',
            'standard_id': 63,
            'serial_number': 'LPI-0368',
            'no_sertifikat': 'LPI-0368',
            'tertelusur_ke': 'LK-285-IDN',
            'terdaftar': true,
          },
        ],
        'field': [
          {
            'kode': 'spesifikasi_alat.sieve.standar_dipakai',
            'label': 'Standar yang dipakai mengukur',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'mikroskop',
                'label': 'Digital Microscope/Dino-Lite',
              },
              {
                'nilai': 'caliper',
                'label': 'Digital Caliper Tesa',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'standar_dicek.*.dipakai',
            'label': 'Usage Check',
            'tipe': 'centang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'standar_dicek.*.keterangan',
            'label': 'Keterangan',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'hasil',
        'halaman': 1,
        'judul': '1. Kalibrasi Dimensi Lubang dan Diameter Kawat',
        'field': <dynamic>[],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'opening',
            'judul': 'Measurement Result',
            'satuan': null,
            'judul_nilai': 'No',
            'judul_pengulangan': 'Opening',
            'titik_bisa_diubah': true,
            'simpan_ke': 'spesifikasi_alat.sieve.opening',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': 1.0,
                'label': '1 (kiri 1)',
                'satuan': null,
              },
              {
                'nomor': 2,
                'titik_ukur': 2.0,
                'label': '2 (kiri 2)',
                'satuan': null,
              },
              {
                'nomor': 3,
                'titik_ukur': 3.0,
                'label': '3 (kiri 3)',
                'satuan': null,
              },
              {
                'nomor': 4,
                'titik_ukur': 4.0,
                'label': '4 (kiri 4)',
                'satuan': null,
              },
              {
                'nomor': 5,
                'titik_ukur': 5.0,
                'label': '5 (kiri 5)',
                'satuan': null,
              },
              {
                'nomor': 6,
                'titik_ukur': 6.0,
                'label': '6 (kiri 6)',
                'satuan': null,
              },
              {
                'nomor': 7,
                'titik_ukur': 7.0,
                'label': '7 (kiri 7)',
                'satuan': null,
              },
              {
                'nomor': 8,
                'titik_ukur': 8.0,
                'label': '8 (kiri 8)',
                'satuan': null,
              },
              {
                'nomor': 9,
                'titik_ukur': 9.0,
                'label': '9 (kiri 9)',
                'satuan': null,
              },
              {
                'nomor': 10,
                'titik_ukur': 10.0,
                'label': '10 (kiri 10)',
                'satuan': null,
              },
              {
                'nomor': 11,
                'titik_ukur': 11.0,
                'label': '11 (kiri 11)',
                'satuan': null,
              },
              {
                'nomor': 12,
                'titik_ukur': 12.0,
                'label': '12 (kiri 12)',
                'satuan': null,
              },
              {
                'nomor': 13,
                'titik_ukur': 13.0,
                'label': '13 (kiri 13)',
                'satuan': null,
              },
              {
                'nomor': 14,
                'titik_ukur': 14.0,
                'label': '14 (kiri 14)',
                'satuan': null,
              },
              {
                'nomor': 15,
                'titik_ukur': 15.0,
                'label': '15 (kiri 15)',
                'satuan': null,
              },
              {
                'nomor': 16,
                'titik_ukur': 16.0,
                'label': '16 (kanan 1)',
                'satuan': null,
              },
              {
                'nomor': 17,
                'titik_ukur': 17.0,
                'label': '17 (kanan 2)',
                'satuan': null,
              },
              {
                'nomor': 18,
                'titik_ukur': 18.0,
                'label': '18 (kanan 3)',
                'satuan': null,
              },
              {
                'nomor': 19,
                'titik_ukur': 19.0,
                'label': '19 (kanan 4)',
                'satuan': null,
              },
              {
                'nomor': 20,
                'titik_ukur': 20.0,
                'label': '20 (kanan 5)',
                'satuan': null,
              },
              {
                'nomor': 21,
                'titik_ukur': 21.0,
                'label': '21 (kanan 6)',
                'satuan': null,
              },
              {
                'nomor': 22,
                'titik_ukur': 22.0,
                'label': '22 (kanan 7)',
                'satuan': null,
              },
              {
                'nomor': 23,
                'titik_ukur': 23.0,
                'label': '23 (kanan 8)',
                'satuan': null,
              },
              {
                'nomor': 24,
                'titik_ukur': 24.0,
                'label': '24 (kanan 9)',
                'satuan': null,
              },
              {
                'nomor': 25,
                'titik_ukur': 25.0,
                'label': '25 (kanan 10)',
                'satuan': null,
              },
              {
                'nomor': 26,
                'titik_ukur': 26.0,
                'label': '26 (kanan 11)',
                'satuan': null,
              },
              {
                'nomor': 27,
                'titik_ukur': 27.0,
                'label': '27 (kanan 12)',
                'satuan': null,
              },
              {
                'nomor': 28,
                'titik_ukur': 28.0,
                'label': '28 (kanan 13)',
                'satuan': null,
              },
              {
                'nomor': 29,
                'titik_ukur': 29.0,
                'label': '29 (kanan 14)',
                'satuan': null,
              },
              {
                'nomor': 30,
                'titik_ukur': 30.0,
                'label': '30 (kanan 15)',
                'satuan': null,
              },
            ],
            'kolom': [
              {
                'kode': 'warp',
                'label': 'Wrap (x\')',
                'tipe': 'angka',
                'satuan': null,
              },
              {
                'kode': 'weft',
                'label': 'Weft (y\')',
                'tipe': 'angka',
                'satuan': null,
              },
              {
                'kode': 'kawat',
                'label': 'Ø Kawat',
                'tipe': 'angka',
                'satuan': null,
              },
            ],
            'pengulangan': [
              1,
            ],
          },
        ],
      },
      {
        'kode': 'frame',
        'halaman': 1,
        'judul': '2. Kalibrasi Diameter dan Ketinggian Rangka',
        'field': <dynamic>[],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'frame',
            'judul': 'Measurement Result',
            'satuan': 'mm',
            'judul_nilai': 'No',
            'judul_pengulangan': 'Rangka',
            'titik_bisa_diubah': false,
            'offset_kunci': 1000,
            'simpan_ke': 'spesifikasi_alat.sieve.frame',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': '1',
                'satuan': 'mm',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': '2',
                'satuan': 'mm',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': '3',
                'satuan': 'mm',
              },
            ],
            'kolom': [
              {
                'kode': 'diameter',
                'label': 'Ø Rangka (mm)',
                'tipe': 'angka',
                'satuan': 'mm',
              },
              {
                'kode': 'tinggi',
                'label': 'Ketinggian Rangka (mm)',
                'tipe': 'angka',
                'satuan': 'mm',
              },
            ],
            'pengulangan': [
              1,
            ],
          },
        ],
      },
      {
        'kode': 'penutup',
        'halaman': 1,
        'judul': 'Catatan & Tanda Tangan',
        'field': [
          {
            'kode': 'catatan_teknisi',
            'label': 'Catatan',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'teknisi.nama',
            'label': 'Calibrated by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'reviewer.nama',
            'label': 'Checked by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
    ],
  };
}
