/// Bentuk lembar kerja contoh keluarga **TEKANAN** — Pressure Gauge, Vacuum
/// Gauge, Differential Pressure (kertas bersama `SIDIK-FM-CAL-0507_Rev.5`).
///
/// Yang HARUS diperhatikan HP, karena salah satu dari ini tidak menghasilkan
/// error apa pun:
///
///  1. **Dua tabel deret-bernama yang barisnya sinkron** —
///     `measurements[].tekanan_up` dan `measurements[].tekanan_down`, tiga
///     pengulangan masing-masing. Baris ke-n keduanya titik setelan yang SAMA;
///     nominal dari tabel PERTAMA (`LembarKerjaState.acuanNominal`), persis
///     Proving Ring. UP dan DOWN yang tertukar tidak membuat sertifikat
///     terlihat aneh — rata-rata bergeser sedikit dan histeresis berganti tanda.
///  2. **`spesifikasi_alat.tekanan.*`** — varian kalibrator, satuan, tampilan,
///     rasio jarum, resolusi, kapasitas (SPMK: media & beda tinggi). Kotak
///     bertanda `mempengaruhi_ketidakpastian: true` tidak boleh diisi otomatis
///     dari OCR tanpa konfirmasi teknisi.
///  3. **Koma desimal** — `99,6` dikirim `99.6` (server membakukannya juga).
///  4. **Dua halaman** — identitas & standar | pengukuran & penutup.
library;

/// Bentuk lembar kerja contoh **Pressure Gauge**.
///
/// Kode profil `pressure_gauge`, satuan `-`, kertas `SIDIK-FM-CAL-0507_Rev.5`.
Map<String, dynamic> contohBentukLembarKerjaPressureGauge({
  bool untukAdmin = false,
}) {
  return {
    'kode_dokumen': 'SIDIK-FM-CAL-0507_Rev.5',
    'kode_metode': 'SIDIK-IK-CAL-0504_Rev.6',
    'nomor_lingkup': 'LK-285-IDN',
    'judul': 'Calibration Worksheet - Pressure & Vacuum Gauge',
    'jumlah_pengulangan': 3,
    'semua_kolom_opsional': false,
    'catatan_pengisian': 'Tiap titik: naikkan tekanan sampai jarum/display UUT TEPAT di angka setelan, lalu catat bacaan STANDAR — tiga kali arah naik (UP), lalu tiga kali arah turun (DOWN). Titik pertama wajib titik NOL: zero error dibaca dari situ. Satuan yang dipilih berlaku untuk setelan dan bacaan standar sekaligus.',
    'budget_ketidakpastian': {
      'tersedia': true,
      'sumber': 'Master Olah Data Pressure (DRUCK07G / DRUCK13G / SPMK / Differential), PERHITUNGAN FC & PERHITUNGAN U95%',
      'catatan': 'Enam komponen (tujuh di SPMK: + beda level), k dari t-Student dengan v_eff dipotong ke bawah, lantai CMC dari lampiran LK-285-IDN. Tiga cacat master yang mengecilkan U95 dihitung benar; angka versi master tercatat di jejak sesi.',
    },
    'tanpa_keputusan': {
      'alasan': 'Sertifikat tekanan tidak menyatakan lulus/tidak lulus — keempat master tidak memuat pernyataan kesesuaian (ISO/IEC 17025 klausul 7.8.6.1).',
    },
    'bagian': [
      {
        'kode': 'identitas_alat',
        'halaman': 1,
        'judul': 'Equipment',
        'field': [
          {
            'kode': 'equipment_id',
            'label': 'Pilih Alat',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_alat',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_model',
            'label': 'Type/Model',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_merk',
            'label': 'Merk/Manufacture',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_serial_number',
            'label': 'Serial Number/LPI',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.tekanan.kapasitas',
            'label': 'Kapasitas Maks (Range)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.tekanan.resolusi',
            'label': 'Resolusi',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.tekanan.satuan',
            'label': 'Satuan Tekanan',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              'Bar',
              'Psi',
              'kg/cm2',
              'kPa',
              'MPa',
              'inHg',
              'mmHg',
              'Pa',
              'mBar',
              'mmH2O',
              'Torr',
              'cmHg',
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.tekanan.tampilan',
            'label': 'Option of Resolution Display',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'digital',
                'label': 'Digital',
              },
              {
                'nilai': 'analog',
                'label': 'Analog (rasio jarum/NST)',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.tekanan.rasio_jarum',
            'label': 'Rasio jarum/NST',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              '1/2',
              '1/5',
              '1/10',
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
            'mempengaruhi_ketidakpastian': true,
          },
        ],
      },
      {
        'kode': 'pemilik',
        'halaman': 1,
        'judul': 'Owner',
        'field': [
          {
            'kode': 'pemilik_nama',
            'label': 'Name',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'pemilik_alamat',
            'label': 'Address',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_awal',
            'label': 'Environment Cond. — First (°C)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_akhir',
            'label': 'Environment Cond. — End (°C)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_awal',
            'label': 'Environment Cond. — First (%RH)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_akhir',
            'label': 'Environment Cond. — End (%RH)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi',
            'label': 'Location',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'lab',
                'label': 'Inlab',
              },
              {
                'nilai': 'onsite',
                'label': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'room_id',
            'label': 'Ruangan (Inlab)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_ruangan',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'lab',
              ],
            },
          },
          {
            'kode': 'lokasi_nama',
            'label': 'Nama Tempat (Insitu)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'onsite',
              ],
            },
          },
          {
            'kode': 'thermohygro_standard_id',
            'label': 'Thermohygro used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_thermohygro',
            'satuan': null,
            'pilihan': [
              {
                'nilai': '1',
                'label': 'TH-1',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '2',
                'label': 'TH-2',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '3',
                'label': 'TH-3',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '4',
                'label': 'TH-4',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '5',
                'label': 'TH-5',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '6',
                'label': 'TH-6',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '7',
                'label': 'TH-7',
                'grup': 'Thermohygro lab',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'usage_check',
        'halaman': 1,
        'judul': 'Standard',
        'baris': [
          {
            'label': 'SPMK/SPMK 700/223180480',
            'standard_id': 84,
            'serial_number': '223180480',
            'no_sertifikat': null,
            'tertelusur_ke': 'LK-025-IDN',
            'terdaftar': true,
          },
          {
            'label': 'ADDITEL/ADT681-05-DP5-MBAR/211H18280008',
            'standard_id': 85,
            'serial_number': '211H18280008',
            'no_sertifikat': null,
            'tertelusur_ke': 'BSN-SNSU',
            'terdaftar': true,
          },
          {
            'label': 'GE/Druck DPI611-07G/5568079',
            'standard_id': 86,
            'serial_number': '5568079',
            'no_sertifikat': null,
            'tertelusur_ke': 'LK-045-IDN',
            'terdaftar': true,
          },
          {
            'label': 'GE/Druck DPI611-13G/5608066',
            'standard_id': 87,
            'serial_number': '5608066',
            'no_sertifikat': null,
            'tertelusur_ke': 'LK-460-IDN',
            'terdaftar': true,
          },
        ],
        'field': [
          {
            'kode': 'spesifikasi_alat.tekanan.varian',
            'label': 'Kalibrator (master olah data)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'druck07g',
                'label': 'GE Druck DPI611-07G (-0,8 ~ 2 bar)',
              },
              {
                'nilai': 'druck13g',
                'label': 'GE Druck DPI611-13G (0 ~ 20 bar)',
              },
              {
                'nilai': 'spmk',
                'label': 'SPMK 700 (0 ~ 600 bar)',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
            'mempengaruhi_ketidakpastian': true,
          },
          {
            'kode': 'spesifikasi_alat.tekanan.media',
            'label': 'Media',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': '1',
                'label': 'Water',
              },
              {
                'nilai': '2',
                'label': 'Oil',
              },
              {
                'nilai': '3',
                'label': 'Air (Udara)',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
            'mempengaruhi_ketidakpastian': true,
          },
          {
            'kode': 'spesifikasi_alat.tekanan.tinggi_standar',
            'label': 'Standard Pressure Height (m)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.tekanan.tinggi_uut',
            'label': 'UUT Pressure Height (m)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.tekanan.beda_tinggi',
            'label': 'Deviation Height (h) (m)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
            'mempengaruhi_ketidakpastian': true,
          },
        ],
      },
      {
        'kode': 'hasil',
        'halaman': 2,
        'judul': 'Pressure Calibration',
        'tampilan': 'kartu_per_set_point',
        'kartu_sejajar': true,
        'nominal_berbintang': false,
        'field': <dynamic>[],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'tekanan_up',
            'offset_kunci': 1000,
            'judul': 'UP (tekanan dinaikkan)',
            'judul_nilai': 'UUT Setting',
            'judul_pengulangan': 'Pengulangan ke',
            'titik_bisa_diubah': false,
            'simpan_ke': 'measurements[].tekanan_up',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Titik 2',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Titik 3',
              },
              {
                'nomor': 4,
                'titik_ukur': null,
                'label': 'Titik 4',
              },
              {
                'nomor': 5,
                'titik_ukur': null,
                'label': 'Titik 5',
              },
              {
                'nomor': 6,
                'titik_ukur': null,
                'label': 'Titik 6',
              },
              {
                'nomor': 7,
                'titik_ukur': null,
                'label': 'Titik 7',
              },
              {
                'nomor': 8,
                'titik_ukur': null,
                'label': 'Titik 8',
              },
              {
                'nomor': 9,
                'titik_ukur': null,
                'label': 'Titik 9',
              },
              {
                'nomor': 10,
                'titik_ukur': null,
                'label': 'Titik 10',
              },
              {
                'nomor': 11,
                'titik_ukur': null,
                'label': 'Titik 11',
              },
              {
                'nomor': 12,
                'titik_ukur': null,
                'label': 'Titik 12',
              },
              {
                'nomor': 13,
                'titik_ukur': null,
                'label': 'Titik 13',
              },
              {
                'nomor': 14,
                'titik_ukur': null,
                'label': 'Titik 14',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Standard Reading',
                'tipe': 'angka',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'tekanan_down',
            'offset_kunci': 2000,
            'judul': 'DOWN (tekanan diturunkan)',
            'judul_nilai': 'UUT Setting',
            'judul_pengulangan': 'Pengulangan ke',
            'titik_bisa_diubah': false,
            'simpan_ke': 'measurements[].tekanan_down',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Titik 2',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Titik 3',
              },
              {
                'nomor': 4,
                'titik_ukur': null,
                'label': 'Titik 4',
              },
              {
                'nomor': 5,
                'titik_ukur': null,
                'label': 'Titik 5',
              },
              {
                'nomor': 6,
                'titik_ukur': null,
                'label': 'Titik 6',
              },
              {
                'nomor': 7,
                'titik_ukur': null,
                'label': 'Titik 7',
              },
              {
                'nomor': 8,
                'titik_ukur': null,
                'label': 'Titik 8',
              },
              {
                'nomor': 9,
                'titik_ukur': null,
                'label': 'Titik 9',
              },
              {
                'nomor': 10,
                'titik_ukur': null,
                'label': 'Titik 10',
              },
              {
                'nomor': 11,
                'titik_ukur': null,
                'label': 'Titik 11',
              },
              {
                'nomor': 12,
                'titik_ukur': null,
                'label': 'Titik 12',
              },
              {
                'nomor': 13,
                'titik_ukur': null,
                'label': 'Titik 13',
              },
              {
                'nomor': 14,
                'titik_ukur': null,
                'label': 'Titik 14',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Standard Reading',
                'tipe': 'angka',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
        ],
      },
      {
        'kode': 'penutup',
        'halaman': 2,
        'judul': 'Catatan & Tanda Tangan',
        'field': [
          {
            'kode': 'catatan_teknisi',
            'label': 'Catatan',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'teknisi.nama',
            'label': 'Calibrated by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'reviewer.nama',
            'label': 'Checked by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
    ],
  };
}

/// Bentuk lembar kerja contoh **Vacuum Gauge**.
///
/// Kode profil `vacuum_gauge`, satuan `-`, kertas `SIDIK-FM-CAL-0507_Rev.5`.
Map<String, dynamic> contohBentukLembarKerjaVacuumGauge({
  bool untukAdmin = false,
}) {
  return {
    'kode_dokumen': 'SIDIK-FM-CAL-0507_Rev.5',
    'kode_metode': 'SIDIK-IK-CAL-0534_Rev.1',
    'nomor_lingkup': 'LK-285-IDN',
    'judul': 'Calibration Worksheet - Pressure & Vacuum Gauge',
    'jumlah_pengulangan': 3,
    'semua_kolom_opsional': false,
    'catatan_pengisian': 'Tiap titik: naikkan tekanan sampai jarum/display UUT TEPAT di angka setelan, lalu catat bacaan STANDAR — tiga kali arah naik (UP), lalu tiga kali arah turun (DOWN). Titik pertama wajib titik NOL: zero error dibaca dari situ. Satuan yang dipilih berlaku untuk setelan dan bacaan standar sekaligus.',
    'budget_ketidakpastian': {
      'tersedia': true,
      'sumber': 'Master Olah Data Pressure (DRUCK07G / DRUCK13G / SPMK / Differential), PERHITUNGAN FC & PERHITUNGAN U95%',
      'catatan': 'Enam komponen (tujuh di SPMK: + beda level), k dari t-Student dengan v_eff dipotong ke bawah, lantai CMC dari lampiran LK-285-IDN. Tiga cacat master yang mengecilkan U95 dihitung benar; angka versi master tercatat di jejak sesi.',
    },
    'tanpa_keputusan': {
      'alasan': 'Sertifikat tekanan tidak menyatakan lulus/tidak lulus — keempat master tidak memuat pernyataan kesesuaian (ISO/IEC 17025 klausul 7.8.6.1).',
    },
    'bagian': [
      {
        'kode': 'identitas_alat',
        'halaman': 1,
        'judul': 'Equipment',
        'field': [
          {
            'kode': 'equipment_id',
            'label': 'Pilih Alat',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_alat',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_model',
            'label': 'Type/Model',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_merk',
            'label': 'Merk/Manufacture',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_serial_number',
            'label': 'Serial Number/LPI',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.tekanan.kapasitas',
            'label': 'Kapasitas Maks (Range)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.tekanan.resolusi',
            'label': 'Resolusi',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.tekanan.satuan',
            'label': 'Satuan Tekanan',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              'Bar',
              'Psi',
              'kg/cm2',
              'kPa',
              'MPa',
              'inHg',
              'mmHg',
              'Pa',
              'mBar',
              'mmH2O',
              'Torr',
              'cmHg',
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.tekanan.tampilan',
            'label': 'Option of Resolution Display',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'digital',
                'label': 'Digital',
              },
              {
                'nilai': 'analog',
                'label': 'Analog (rasio jarum/NST)',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.tekanan.rasio_jarum',
            'label': 'Rasio jarum/NST',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              '1/2',
              '1/5',
              '1/10',
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
            'mempengaruhi_ketidakpastian': true,
          },
        ],
      },
      {
        'kode': 'pemilik',
        'halaman': 1,
        'judul': 'Owner',
        'field': [
          {
            'kode': 'pemilik_nama',
            'label': 'Name',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'pemilik_alamat',
            'label': 'Address',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_awal',
            'label': 'Environment Cond. — First (°C)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_akhir',
            'label': 'Environment Cond. — End (°C)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_awal',
            'label': 'Environment Cond. — First (%RH)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_akhir',
            'label': 'Environment Cond. — End (%RH)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi',
            'label': 'Location',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'lab',
                'label': 'Inlab',
              },
              {
                'nilai': 'onsite',
                'label': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'room_id',
            'label': 'Ruangan (Inlab)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_ruangan',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'lab',
              ],
            },
          },
          {
            'kode': 'lokasi_nama',
            'label': 'Nama Tempat (Insitu)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'onsite',
              ],
            },
          },
          {
            'kode': 'thermohygro_standard_id',
            'label': 'Thermohygro used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_thermohygro',
            'satuan': null,
            'pilihan': [
              {
                'nilai': '1',
                'label': 'TH-1',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '2',
                'label': 'TH-2',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '3',
                'label': 'TH-3',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '4',
                'label': 'TH-4',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '5',
                'label': 'TH-5',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '6',
                'label': 'TH-6',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '7',
                'label': 'TH-7',
                'grup': 'Thermohygro lab',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'usage_check',
        'halaman': 1,
        'judul': 'Standard',
        'baris': [
          {
            'label': 'SPMK/SPMK 700/223180480',
            'standard_id': 84,
            'serial_number': '223180480',
            'no_sertifikat': null,
            'tertelusur_ke': 'LK-025-IDN',
            'terdaftar': true,
          },
          {
            'label': 'ADDITEL/ADT681-05-DP5-MBAR/211H18280008',
            'standard_id': 85,
            'serial_number': '211H18280008',
            'no_sertifikat': null,
            'tertelusur_ke': 'BSN-SNSU',
            'terdaftar': true,
          },
          {
            'label': 'GE/Druck DPI611-07G/5568079',
            'standard_id': 86,
            'serial_number': '5568079',
            'no_sertifikat': null,
            'tertelusur_ke': 'LK-045-IDN',
            'terdaftar': true,
          },
          {
            'label': 'GE/Druck DPI611-13G/5608066',
            'standard_id': 87,
            'serial_number': '5608066',
            'no_sertifikat': null,
            'tertelusur_ke': 'LK-460-IDN',
            'terdaftar': true,
          },
        ],
        'field': [
          {
            'kode': 'spesifikasi_alat.tekanan.varian',
            'label': 'Kalibrator (master olah data)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'druck07g',
                'label': 'GE Druck DPI611-07G (-0,8 ~ 2 bar)',
              },
              {
                'nilai': 'druck13g',
                'label': 'GE Druck DPI611-13G (0 ~ 20 bar)',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
            'mempengaruhi_ketidakpastian': true,
          },
        ],
      },
      {
        'kode': 'hasil',
        'halaman': 2,
        'judul': 'Pressure Calibration',
        'tampilan': 'kartu_per_set_point',
        'kartu_sejajar': true,
        'nominal_berbintang': false,
        'field': <dynamic>[],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'tekanan_up',
            'offset_kunci': 1000,
            'judul': 'UP (tekanan dinaikkan)',
            'judul_nilai': 'UUT Setting',
            'judul_pengulangan': 'Pengulangan ke',
            'titik_bisa_diubah': false,
            'simpan_ke': 'measurements[].tekanan_up',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Titik 2',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Titik 3',
              },
              {
                'nomor': 4,
                'titik_ukur': null,
                'label': 'Titik 4',
              },
              {
                'nomor': 5,
                'titik_ukur': null,
                'label': 'Titik 5',
              },
              {
                'nomor': 6,
                'titik_ukur': null,
                'label': 'Titik 6',
              },
              {
                'nomor': 7,
                'titik_ukur': null,
                'label': 'Titik 7',
              },
              {
                'nomor': 8,
                'titik_ukur': null,
                'label': 'Titik 8',
              },
              {
                'nomor': 9,
                'titik_ukur': null,
                'label': 'Titik 9',
              },
              {
                'nomor': 10,
                'titik_ukur': null,
                'label': 'Titik 10',
              },
              {
                'nomor': 11,
                'titik_ukur': null,
                'label': 'Titik 11',
              },
              {
                'nomor': 12,
                'titik_ukur': null,
                'label': 'Titik 12',
              },
              {
                'nomor': 13,
                'titik_ukur': null,
                'label': 'Titik 13',
              },
              {
                'nomor': 14,
                'titik_ukur': null,
                'label': 'Titik 14',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Standard Reading',
                'tipe': 'angka',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'tekanan_down',
            'offset_kunci': 2000,
            'judul': 'DOWN (tekanan diturunkan)',
            'judul_nilai': 'UUT Setting',
            'judul_pengulangan': 'Pengulangan ke',
            'titik_bisa_diubah': false,
            'simpan_ke': 'measurements[].tekanan_down',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Titik 2',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Titik 3',
              },
              {
                'nomor': 4,
                'titik_ukur': null,
                'label': 'Titik 4',
              },
              {
                'nomor': 5,
                'titik_ukur': null,
                'label': 'Titik 5',
              },
              {
                'nomor': 6,
                'titik_ukur': null,
                'label': 'Titik 6',
              },
              {
                'nomor': 7,
                'titik_ukur': null,
                'label': 'Titik 7',
              },
              {
                'nomor': 8,
                'titik_ukur': null,
                'label': 'Titik 8',
              },
              {
                'nomor': 9,
                'titik_ukur': null,
                'label': 'Titik 9',
              },
              {
                'nomor': 10,
                'titik_ukur': null,
                'label': 'Titik 10',
              },
              {
                'nomor': 11,
                'titik_ukur': null,
                'label': 'Titik 11',
              },
              {
                'nomor': 12,
                'titik_ukur': null,
                'label': 'Titik 12',
              },
              {
                'nomor': 13,
                'titik_ukur': null,
                'label': 'Titik 13',
              },
              {
                'nomor': 14,
                'titik_ukur': null,
                'label': 'Titik 14',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Standard Reading',
                'tipe': 'angka',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
        ],
      },
      {
        'kode': 'penutup',
        'halaman': 2,
        'judul': 'Catatan & Tanda Tangan',
        'field': [
          {
            'kode': 'catatan_teknisi',
            'label': 'Catatan',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'teknisi.nama',
            'label': 'Calibrated by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'reviewer.nama',
            'label': 'Checked by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
    ],
  };
}

/// Bentuk lembar kerja contoh **Differential Pressure**.
///
/// Kode profil `differential_pressure`, satuan `-`, kertas `SIDIK-FM-CAL-0507_Rev.5`.
Map<String, dynamic> contohBentukLembarKerjaDifferentialPressure({
  bool untukAdmin = false,
}) {
  return {
    'kode_dokumen': 'SIDIK-FM-CAL-0507_Rev.5',
    'kode_metode': 'SIDIK-IK-CAL-0532_Rev.0',
    'nomor_lingkup': 'LK-285-IDN',
    'judul': 'Calibration Worksheet - Pressure & Vacuum Gauge',
    'jumlah_pengulangan': 3,
    'semua_kolom_opsional': false,
    'catatan_pengisian': 'Tiap titik: naikkan tekanan sampai jarum/display UUT TEPAT di angka setelan, lalu catat bacaan STANDAR — tiga kali arah naik (UP), lalu tiga kali arah turun (DOWN). Titik pertama wajib titik NOL: zero error dibaca dari situ. Satuan yang dipilih berlaku untuk setelan dan bacaan standar sekaligus.',
    'budget_ketidakpastian': {
      'tersedia': true,
      'sumber': 'Master Olah Data Pressure (DRUCK07G / DRUCK13G / SPMK / Differential), PERHITUNGAN FC & PERHITUNGAN U95%',
      'catatan': 'Enam komponen (tujuh di SPMK: + beda level), k dari t-Student dengan v_eff dipotong ke bawah, lantai CMC dari lampiran LK-285-IDN. Tiga cacat master yang mengecilkan U95 dihitung benar; angka versi master tercatat di jejak sesi.',
    },
    'tanpa_keputusan': {
      'alasan': 'Sertifikat tekanan tidak menyatakan lulus/tidak lulus — keempat master tidak memuat pernyataan kesesuaian (ISO/IEC 17025 klausul 7.8.6.1).',
    },
    'bagian': [
      {
        'kode': 'identitas_alat',
        'halaman': 1,
        'judul': 'Equipment',
        'field': [
          {
            'kode': 'equipment_id',
            'label': 'Pilih Alat',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_alat',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_model',
            'label': 'Type/Model',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_merk',
            'label': 'Merk/Manufacture',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_serial_number',
            'label': 'Serial Number/LPI',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.tekanan.kapasitas',
            'label': 'Kapasitas Maks (Range)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.tekanan.resolusi',
            'label': 'Resolusi',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.tekanan.satuan',
            'label': 'Satuan Tekanan',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              'Bar',
              'Psi',
              'kg/cm2',
              'kPa',
              'MPa',
              'inHg',
              'mmHg',
              'Pa',
              'mBar',
              'mmH2O',
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.tekanan.tampilan',
            'label': 'Option of Resolution Display',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'digital',
                'label': 'Digital',
              },
              {
                'nilai': 'analog',
                'label': 'Analog (rasio jarum/NST)',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.tekanan.rasio_jarum',
            'label': 'Rasio jarum/NST',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              '1/2',
              '1/5',
              '1/10',
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
            'mempengaruhi_ketidakpastian': true,
          },
        ],
      },
      {
        'kode': 'pemilik',
        'halaman': 1,
        'judul': 'Owner',
        'field': [
          {
            'kode': 'pemilik_nama',
            'label': 'Name',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'pemilik_alamat',
            'label': 'Address',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_awal',
            'label': 'Environment Cond. — First (°C)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_akhir',
            'label': 'Environment Cond. — End (°C)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_awal',
            'label': 'Environment Cond. — First (%RH)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_akhir',
            'label': 'Environment Cond. — End (%RH)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi',
            'label': 'Location',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'lab',
                'label': 'Inlab',
              },
              {
                'nilai': 'onsite',
                'label': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'room_id',
            'label': 'Ruangan (Inlab)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_ruangan',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'lab',
              ],
            },
          },
          {
            'kode': 'lokasi_nama',
            'label': 'Nama Tempat (Insitu)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'onsite',
              ],
            },
          },
          {
            'kode': 'thermohygro_standard_id',
            'label': 'Thermohygro used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_thermohygro',
            'satuan': null,
            'pilihan': [
              {
                'nilai': '1',
                'label': 'TH-1',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '2',
                'label': 'TH-2',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '3',
                'label': 'TH-3',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '4',
                'label': 'TH-4',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '5',
                'label': 'TH-5',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '6',
                'label': 'TH-6',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '7',
                'label': 'TH-7',
                'grup': 'Thermohygro lab',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'usage_check',
        'halaman': 1,
        'judul': 'Standard',
        'baris': [
          {
            'label': 'SPMK/SPMK 700/223180480',
            'standard_id': 84,
            'serial_number': '223180480',
            'no_sertifikat': null,
            'tertelusur_ke': 'LK-025-IDN',
            'terdaftar': true,
          },
          {
            'label': 'ADDITEL/ADT681-05-DP5-MBAR/211H18280008',
            'standard_id': 85,
            'serial_number': '211H18280008',
            'no_sertifikat': null,
            'tertelusur_ke': 'BSN-SNSU',
            'terdaftar': true,
          },
          {
            'label': 'GE/Druck DPI611-07G/5568079',
            'standard_id': 86,
            'serial_number': '5568079',
            'no_sertifikat': null,
            'tertelusur_ke': 'LK-045-IDN',
            'terdaftar': true,
          },
          {
            'label': 'GE/Druck DPI611-13G/5608066',
            'standard_id': 87,
            'serial_number': '5608066',
            'no_sertifikat': null,
            'tertelusur_ke': 'LK-460-IDN',
            'terdaftar': true,
          },
        ],
        'field': [
          {
            'kode': 'spesifikasi_alat.tekanan.varian',
            'label': 'Kalibrator (master olah data)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'differential',
                'label': 'Additel ADT681-05-DP5-MBAR (±10 mbar)',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
            'mempengaruhi_ketidakpastian': true,
          },
        ],
      },
      {
        'kode': 'hasil',
        'halaman': 2,
        'judul': 'Pressure Calibration',
        'tampilan': 'kartu_per_set_point',
        'kartu_sejajar': true,
        'nominal_berbintang': false,
        'field': <dynamic>[],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'tekanan_up',
            'offset_kunci': 1000,
            'judul': 'UP (tekanan dinaikkan)',
            'judul_nilai': 'UUT Setting',
            'judul_pengulangan': 'Pengulangan ke',
            'titik_bisa_diubah': false,
            'simpan_ke': 'measurements[].tekanan_up',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Titik 2',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Titik 3',
              },
              {
                'nomor': 4,
                'titik_ukur': null,
                'label': 'Titik 4',
              },
              {
                'nomor': 5,
                'titik_ukur': null,
                'label': 'Titik 5',
              },
              {
                'nomor': 6,
                'titik_ukur': null,
                'label': 'Titik 6',
              },
              {
                'nomor': 7,
                'titik_ukur': null,
                'label': 'Titik 7',
              },
              {
                'nomor': 8,
                'titik_ukur': null,
                'label': 'Titik 8',
              },
              {
                'nomor': 9,
                'titik_ukur': null,
                'label': 'Titik 9',
              },
              {
                'nomor': 10,
                'titik_ukur': null,
                'label': 'Titik 10',
              },
              {
                'nomor': 11,
                'titik_ukur': null,
                'label': 'Titik 11',
              },
              {
                'nomor': 12,
                'titik_ukur': null,
                'label': 'Titik 12',
              },
              {
                'nomor': 13,
                'titik_ukur': null,
                'label': 'Titik 13',
              },
              {
                'nomor': 14,
                'titik_ukur': null,
                'label': 'Titik 14',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Standard Reading',
                'tipe': 'angka',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'tekanan_down',
            'offset_kunci': 2000,
            'judul': 'DOWN (tekanan diturunkan)',
            'judul_nilai': 'UUT Setting',
            'judul_pengulangan': 'Pengulangan ke',
            'titik_bisa_diubah': false,
            'simpan_ke': 'measurements[].tekanan_down',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Titik 2',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Titik 3',
              },
              {
                'nomor': 4,
                'titik_ukur': null,
                'label': 'Titik 4',
              },
              {
                'nomor': 5,
                'titik_ukur': null,
                'label': 'Titik 5',
              },
              {
                'nomor': 6,
                'titik_ukur': null,
                'label': 'Titik 6',
              },
              {
                'nomor': 7,
                'titik_ukur': null,
                'label': 'Titik 7',
              },
              {
                'nomor': 8,
                'titik_ukur': null,
                'label': 'Titik 8',
              },
              {
                'nomor': 9,
                'titik_ukur': null,
                'label': 'Titik 9',
              },
              {
                'nomor': 10,
                'titik_ukur': null,
                'label': 'Titik 10',
              },
              {
                'nomor': 11,
                'titik_ukur': null,
                'label': 'Titik 11',
              },
              {
                'nomor': 12,
                'titik_ukur': null,
                'label': 'Titik 12',
              },
              {
                'nomor': 13,
                'titik_ukur': null,
                'label': 'Titik 13',
              },
              {
                'nomor': 14,
                'titik_ukur': null,
                'label': 'Titik 14',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Standard Reading',
                'tipe': 'angka',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
        ],
      },
      {
        'kode': 'penutup',
        'halaman': 2,
        'judul': 'Catatan & Tanda Tangan',
        'field': [
          {
            'kode': 'catatan_teknisi',
            'label': 'Catatan',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'teknisi.nama',
            'label': 'Calibrated by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'reviewer.nama',
            'label': 'Checked by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
    ],
  };
}
