/// Bentuk lembar kerja contoh **Flowmeter Ultrasonic** (kelompok Aliran, alat
/// ke-27 & ke-28).
///
/// ## Kenapa berkas ini ada, dan kenapa isinya nggak diketik tangan
///
/// Isinya salinan APA ADANYA dari respons
/// `GET /api/calibrations/lembar-kerja?equipment_id=…` untuk alat contoh
/// ter-seed `FM-TOT-DEMO-01` dan `FM-FLW-DEMO-01`. Digenerate dari bentuk yang
/// beneran dikirim server (`docs/skrip/gen-contoh-lembar-kerja-flowmeter.php`
/// di repo API), bukan disusun ulang di sini: bentuk yang diketik tangan bakal
/// menyimpang diam-diam begitu backendnya direvisi, dan test yang jalan di atas
/// bentuk basi memberi rasa aman yang salah.
///
/// ## Yang cuma ada di lembar ini
///
///  1. **Satu titik, DUA deret berdampingan.** `flow_uut_pembacaan` dan
///     `flow_std_pembacaan` tabelnya terpisah, dan deviasinya lahir dari
///     selisih BERPASANGAN keduanya. Tertukar atau tertimpa, yang terbit bukan
///     error melainkan deviasi NOL di setiap titik.
///  2. **Deret UUT yang BERSARANG** pada varian Flowrate: `pengulangan` itu
///     ulangan, `kolom` (`durasi_1..3`) itu durasi 20"/40"/60". Simpangan
///     bakunya dihitung atas ketiga durasi ulangan ITU — diratakan, komponen
///     budget ke-3 keluar jauh lebih besar dan tetap terlihat masuk akal.
///  3. **LIMA tabel ber-`tahap` sama** di bagian `hasil`, plus dua di bagian
///     `pipa`. Kunci barisnya dipisah `offset_kunci` (0 / 1000 / 2000 / 3000 /
///     4000 / 5000 / 5100); tanpa itu angka yang diketik di satu kotak muncul
///     di kotak lain, tanpa satu pun error.
///  4. **Geometri pipa yang MENENTUKAN ANGKA.** Diameter & ketebalan kosong
///     bikin `u_A` nol dan DUA komponen budget lenyap sekaligus.
///
/// Dropdown bersumber master (`master_alat`, `master_ruangan`,
/// `master_thermohygro`) sengaja kosong di sini — sama seperti berkas contoh
/// alat lain, mode mock memang nggak punya masternya.
library;

/// Bentuk lembar kerja contoh **Flow Meter Cairan (Totalizer)**.
///
/// Kode profil `flowmeter_totalizer`, satuan `L`, kertas `SIDIK-FM-CAL-0538_Rev.0`.
///
/// DIGENERATE `docs/skrip/gen-contoh-lembar-kerja-flowmeter.php` di repo API —
/// jangan disunting tangan.
Map<String, dynamic> contohBentukLembarKerjaFlowmeterTotalizer({
  bool untukAdmin = false,
}) {
  return {
    'kode_dokumen': 'SIDIK-FM-CAL-0538_Rev.0',
    'kode_metode': 'SIDIK-IK-CAL-0528_Rev.4',
    'nomor_lingkup': 'LK-285-IDN',
    'judul': 'Calibration Work Sheet - Flow Meter Cairan (Totalizer)',
    'jumlah_pengulangan': 3,
    'satuan': 'L',
    'satuan_suhu': '°C',
    'semua_kolom_opsional': true,
    'catatan_pengisian': 'Isi MODE dan SATUAN alat lebih dulu — mode menentukan budgetnya 8 komponen, satuan menentukan faktor konversinya ke L. Satuan berbasis MASSA (kg, kg/h, kg/min) WAJIB disertai densitas fluida UUT; tanpa itu pembacaannya tidak bisa diubah ke L sama sekali dan titiknya tidak diterbitkan. Diameter luar & ketebalan pipa dibaca 3 kali — dari sebarannya komponen `Cross Section Area` lahir, jadi mengosongkannya MENGECILKAN U95.',
    'budget_ketidakpastian': {
      'tersedia': true,
      'sumber': '1.3 Master Olah Data Flowmeter_Ultrasonic Totalizer (1000-1900L) 2026.xlsm',
      'catatan': 'Delapan komponen PER TITIK, berlantai CMC `% of reading` dari lampiran LK-285-IDN no. 30. Belum memuat komponen "Pengulangan Pembacaan UUT" yang lahir di revisi Flowrate 20 Mei 2026 — ditiru apa adanya, lihat pertanyaan lab §3.',
    },
    'bagian': [
      {
        'kode': 'identitas_alat',
        'halaman': 1,
        'judul': 'Identitas Alat dan Data Customer',
        'field': [
          {
            'kode': 'equipment_id',
            'label': 'Nama Alat',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_alat',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'equipment.nama_alat',
            'label': 'Nama Alat',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_merk',
            'label': 'Merk',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_model',
            'label': 'Type',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_serial_number',
            'label': 'No. Seri',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.mode',
            'label': 'Mode',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'totalizer',
                'label': 'Totalizer',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.satuan',
            'label': 'Satuan Alat',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'L',
                'label': 'L',
              },
              {
                'nilai': 'm3',
                'label': 'm3',
              },
              {
                'nilai': 'usg',
                'label': 'usg',
              },
              {
                'nilai': 'ml',
                'label': 'ml',
              },
              {
                'nilai': 'kg',
                'label': 'kg',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.rentang_ukur',
            'label': 'Rentang Ukur',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.kapasitas',
            'label': 'Kapasitas Max.',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'L',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.resolusi',
            'label': 'Resolusi Alat',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'L',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.material_pipa',
            'label': 'Material Pipa',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.jenis_fluida',
            'label': 'Jenis Fluida',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.path_configuration',
            'label': 'Path Configuration',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'Z',
                'label': 'Z-Method',
              },
              {
                'nilai': 'V',
                'label': 'V-Method',
              },
              {
                'nilai': 'W',
                'label': 'W-Method',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.liner_material',
            'label': 'Liner — Material',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.liner_ketebalan_mm',
            'label': 'Liner — Ketebalan',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'mm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_terima',
            'label': 'Tgl. Diterima',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_kalibrasi',
            'label': 'Tgl. Kalibrasi',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_awal',
            'label': 'Suhu Ruangan — awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_akhir',
            'label': 'Suhu Ruangan — akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_awal',
            'label': 'Kelembapan — awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_akhir',
            'label': 'Kelembapan — akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi',
            'label': 'Lokasi Kalibrasi',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'lab',
                'label': 'Inlab',
              },
              {
                'nilai': 'onsite',
                'label': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'room_id',
            'label': 'Ruangan (Inlab)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_ruangan',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'lab',
              ],
            },
          },
          {
            'kode': 'lokasi_nama',
            'label': 'Nama Tempat (Insitu)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'onsite',
              ],
            },
          },
          {
            'kode': 'thermohygro_standard_id',
            'label': 'Environmental Meter Used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_thermohygro',
            'satuan': null,
            'pilihan': [
              {
                'nilai': '1',
                'label': 'TH-1',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '2',
                'label': 'TH-2',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '3',
                'label': 'TH-3',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '4',
                'label': 'TH-4',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '5',
                'label': 'TH-5',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '6',
                'label': 'TH-6',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '7',
                'label': 'TH-7',
                'grup': 'Thermohygro lab',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'pemilik',
        'halaman': 1,
        'judul': 'Data Customer',
        'field': [
          {
            'kode': 'pemilik_nama',
            'label': 'Nama Customer',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'pemilik_alamat',
            'label': 'Alamat Customer',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'nomor_order',
            'label': 'Order Number',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'usage_check',
        'halaman': 1,
        'judul': 'Standard Used',
        'baris': [
          {
            'label': 'Ultrasonic Flowmeter/Krohne/UFC300',
            'standard_id': null,
            'serial_number': null,
            'no_sertifikat': null,
            'tertelusur_ke': null,
            'terdaftar': false,
          },
          {
            'label': 'Temperature Calibrator/Yokogawa/CA 150 Handy Cal',
            'standard_id': 13,
            'serial_number': '23P1005',
            'no_sertifikat': '23P1005',
            'tertelusur_ke': 'LK-285-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Thermocouple Type K',
            'standard_id': 48,
            'serial_number': 'TC-01,02',
            'no_sertifikat': 'TC-01,02',
            'tertelusur_ke': 'LK-064-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Digital Caliper/Tesa/Cal-IP67',
            'standard_id': null,
            'serial_number': null,
            'no_sertifikat': null,
            'tertelusur_ke': null,
            'terdaftar': false,
          },
          {
            'label': 'Ultrasonic Thickness Gauge/TM-8812',
            'standard_id': null,
            'serial_number': null,
            'no_sertifikat': null,
            'tertelusur_ke': null,
            'terdaftar': false,
          },
        ],
        'field': [
          {
            'kode': 'standar_dicek.*.dipakai',
            'label': 'Usage Check',
            'tipe': 'centang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'standar_dicek.*.keterangan',
            'label': 'Keterangan',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'pipa',
        'halaman': 1,
        'judul': 'Geometri Pipa',
        'field': <dynamic>[],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'pipa_diameter',
            'judul': 'Diameter Luar Pipa (Digital Caliper)',
            'satuan': 'mm',
            'judul_nilai': 'Diameter Luar',
            'judul_pengulangan': 'Pembacaan',
            'titik_bisa_diubah': false,
            'pita_cetak': 1,
            'offset_kunci': 5000,
            'simpan_ke': 'spesifikasi_alat.flowmeter.diameter_pipa_mm',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Diameter Luar',
                'satuan': 'mm',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'mm',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'pipa_ketebalan',
            'judul': 'Ketebalan Dinding Pipa (Ultrasonic Thickness Gauge)',
            'satuan': 'mm',
            'judul_nilai': 'Ketebalan',
            'judul_pengulangan': 'Pembacaan',
            'titik_bisa_diubah': false,
            'pita_cetak': 1,
            'offset_kunci': 5100,
            'simpan_ke': 'spesifikasi_alat.flowmeter.ketebalan_pipa_mm',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Ketebalan',
                'satuan': 'mm',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'mm',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
        ],
      },
      {
        'kode': 'hasil',
        'halaman': 1,
        'judul': 'Measurement',
        'field': <dynamic>[],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'flow_uut_pembacaan',
            'judul': 'Pembacaan UUT',
            'satuan': 'L',
            'judul_nilai': 'Titik',
            'judul_pengulangan': 'Ulangan',
            'titik_bisa_diubah': true,
            'pita_cetak': 2,
            'offset_kunci': 0,
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1',
                'satuan': 'L',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Titik 2',
                'satuan': 'L',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Titik 3',
                'satuan': 'L',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'L',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'flow_std_pembacaan',
            'judul': 'Pembacaan Standar (Krohne UFC300)',
            'satuan': 'L',
            'judul_nilai': 'Titik',
            'judul_pengulangan': 'Pembacaan',
            'titik_bisa_diubah': true,
            'pita_cetak': 3,
            'offset_kunci': 1000,
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1',
                'satuan': 'L',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Titik 2',
                'satuan': 'L',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Titik 3',
                'satuan': 'L',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'L',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'flow_suhu_awal',
            'judul': 'Suhu Air — awal',
            'satuan': '°C',
            'judul_nilai': 'Titik',
            'judul_pengulangan': 'Pembacaan',
            'titik_bisa_diubah': true,
            'pita_cetak': 4,
            'offset_kunci': 2000,
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1',
                'satuan': 'L',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Titik 2',
                'satuan': 'L',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Titik 3',
                'satuan': 'L',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': '°C',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'flow_suhu_akhir',
            'judul': 'Suhu Air — akhir',
            'satuan': '°C',
            'judul_nilai': 'Titik',
            'judul_pengulangan': 'Pembacaan',
            'titik_bisa_diubah': true,
            'pita_cetak': 4,
            'offset_kunci': 3000,
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1',
                'satuan': 'L',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Titik 2',
                'satuan': 'L',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Titik 3',
                'satuan': 'L',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': '°C',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'flow_densitas_uut',
            'judul': 'Densitas Fluida UUT (wajib kalau satuan berbasis massa)',
            'satuan': 'kg/L',
            'judul_nilai': 'Titik',
            'judul_pengulangan': 'Pembacaan',
            'titik_bisa_diubah': true,
            'pita_cetak': 4,
            'offset_kunci': 4000,
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1',
                'satuan': 'L',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Titik 2',
                'satuan': 'L',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Titik 3',
                'satuan': 'L',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'kg/L',
              },
            ],
            'pengulangan': [
              1,
            ],
          },
        ],
      },
      {
        'kode': 'penutup',
        'halaman': 1,
        'judul': 'Catatan & Tanda Tangan',
        'field': [
          {
            'kode': 'catatan_teknisi',
            'label': 'Catatan',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'teknisi.nama',
            'label': 'Dikalibrasi Oleh',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'reviewer.nama',
            'label': 'Diperiksa Oleh',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
    ],
  };
}

/// Bentuk lembar kerja contoh **Flow Meter Cairan (Flowrate)**.
///
/// Kode profil `flowmeter_flowrate`, satuan `Lpm`, kertas `SIDIK-FM-CAL-0538_Rev.0`.
///
/// DIGENERATE `docs/skrip/gen-contoh-lembar-kerja-flowmeter.php` di repo API —
/// jangan disunting tangan.
Map<String, dynamic> contohBentukLembarKerjaFlowmeterFlowrate({
  bool untukAdmin = false,
}) {
  return {
    'kode_dokumen': 'SIDIK-FM-CAL-0538_Rev.0',
    'kode_metode': 'SIDIK-IK-CAL-0528_Rev.4',
    'nomor_lingkup': 'LK-285-IDN',
    'judul': 'Calibration Work Sheet - Flow Meter Cairan (Flowrate)',
    'jumlah_pengulangan': 3,
    'satuan': 'Lpm',
    'satuan_suhu': '°C',
    'semua_kolom_opsional': true,
    'catatan_pengisian': 'Isi MODE dan SATUAN alat lebih dulu — mode menentukan budgetnya 9 komponen, satuan menentukan faktor konversinya ke Lpm. Satuan berbasis MASSA (kg, kg/h, kg/min) WAJIB disertai densitas fluida UUT; tanpa itu pembacaannya tidak bisa diubah ke Lpm sama sekali dan titiknya tidak diterbitkan. Diameter luar & ketebalan pipa dibaca 3 kali — dari sebarannya komponen `Cross Section Area` lahir, jadi mengosongkannya MENGECILKAN U95. Tiap ulangan diisi 3 durasi; simpangan bakunya dihitung atas ketiga durasi ulangan ITU, bukan antar-ulangan.',
    'budget_ketidakpastian': {
      'tersedia': true,
      'sumber': 'Master olda Ultrasonic Flowrate (100-300 lpm) 2026.xlsm',
      'catatan': 'Sembilan komponen PER TITIK, berlantai CMC `% of reading` dari lampiran LK-285-IDN no. 31. Komponen ke-9 "Pengulangan Pembacaan UUT" lahir dari revisi 20 Mei 2026 yang belum masuk workbook Totalizer — lihat pertanyaan lab §3.',
    },
    'bagian': [
      {
        'kode': 'identitas_alat',
        'halaman': 1,
        'judul': 'Identitas Alat dan Data Customer',
        'field': [
          {
            'kode': 'equipment_id',
            'label': 'Nama Alat',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_alat',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'equipment.nama_alat',
            'label': 'Nama Alat',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_merk',
            'label': 'Merk',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_model',
            'label': 'Type',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_serial_number',
            'label': 'No. Seri',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.mode',
            'label': 'Mode',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'flowrate',
                'label': 'Flowrate',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.satuan',
            'label': 'Satuan Alat',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'LPM',
                'label': 'LPM',
              },
              {
                'nilai': 'm3/h',
                'label': 'm3/h',
              },
              {
                'nilai': 'usg/min',
                'label': 'usg/min',
              },
              {
                'nilai': 'm3/min',
                'label': 'm3/min',
              },
              {
                'nilai': 'kg/h',
                'label': 'kg/h',
              },
              {
                'nilai': 'kg/min',
                'label': 'kg/min',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.rentang_ukur',
            'label': 'Rentang Ukur',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.kapasitas',
            'label': 'Kapasitas Max.',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'Lpm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.resolusi',
            'label': 'Resolusi Alat',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'Lpm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.material_pipa',
            'label': 'Material Pipa',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.jenis_fluida',
            'label': 'Jenis Fluida',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.path_configuration',
            'label': 'Path Configuration',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'Z',
                'label': 'Z-Method',
              },
              {
                'nilai': 'V',
                'label': 'V-Method',
              },
              {
                'nilai': 'W',
                'label': 'W-Method',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.liner_material',
            'label': 'Liner — Material',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.flowmeter.liner_ketebalan_mm',
            'label': 'Liner — Ketebalan',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': 'mm',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_terima',
            'label': 'Tgl. Diterima',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_kalibrasi',
            'label': 'Tgl. Kalibrasi',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_awal',
            'label': 'Suhu Ruangan — awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_akhir',
            'label': 'Suhu Ruangan — akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_awal',
            'label': 'Kelembapan — awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_akhir',
            'label': 'Kelembapan — akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi',
            'label': 'Lokasi Kalibrasi',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'lab',
                'label': 'Inlab',
              },
              {
                'nilai': 'onsite',
                'label': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'room_id',
            'label': 'Ruangan (Inlab)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_ruangan',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'lab',
              ],
            },
          },
          {
            'kode': 'lokasi_nama',
            'label': 'Nama Tempat (Insitu)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'onsite',
              ],
            },
          },
          {
            'kode': 'thermohygro_standard_id',
            'label': 'Environmental Meter Used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_thermohygro',
            'satuan': null,
            'pilihan': [
              {
                'nilai': '1',
                'label': 'TH-1',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '2',
                'label': 'TH-2',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '3',
                'label': 'TH-3',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '4',
                'label': 'TH-4',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '5',
                'label': 'TH-5',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '6',
                'label': 'TH-6',
                'grup': 'Thermohygro lab',
              },
              {
                'nilai': '7',
                'label': 'TH-7',
                'grup': 'Thermohygro lab',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'pemilik',
        'halaman': 1,
        'judul': 'Data Customer',
        'field': [
          {
            'kode': 'pemilik_nama',
            'label': 'Nama Customer',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'pemilik_alamat',
            'label': 'Alamat Customer',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'nomor_order',
            'label': 'Order Number',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'usage_check',
        'halaman': 1,
        'judul': 'Standard Used',
        'baris': [
          {
            'label': 'Ultrasonic Flowmeter/Krohne/UFC300',
            'standard_id': null,
            'serial_number': null,
            'no_sertifikat': null,
            'tertelusur_ke': null,
            'terdaftar': false,
          },
          {
            'label': 'Temperature Calibrator/Yokogawa/CA 150 Handy Cal',
            'standard_id': 13,
            'serial_number': '23P1005',
            'no_sertifikat': '23P1005',
            'tertelusur_ke': 'LK-285-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Thermocouple Type K',
            'standard_id': 48,
            'serial_number': 'TC-01,02',
            'no_sertifikat': 'TC-01,02',
            'tertelusur_ke': 'LK-064-IDN',
            'terdaftar': true,
          },
          {
            'label': 'Digital Caliper/Tesa/Cal-IP67',
            'standard_id': null,
            'serial_number': null,
            'no_sertifikat': null,
            'tertelusur_ke': null,
            'terdaftar': false,
          },
          {
            'label': 'Ultrasonic Thickness Gauge/TM-8812',
            'standard_id': null,
            'serial_number': null,
            'no_sertifikat': null,
            'tertelusur_ke': null,
            'terdaftar': false,
          },
        ],
        'field': [
          {
            'kode': 'standar_dicek.*.dipakai',
            'label': 'Usage Check',
            'tipe': 'centang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'standar_dicek.*.keterangan',
            'label': 'Keterangan',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'pipa',
        'halaman': 1,
        'judul': 'Geometri Pipa',
        'field': <dynamic>[],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'pipa_diameter',
            'judul': 'Diameter Luar Pipa (Digital Caliper)',
            'satuan': 'mm',
            'judul_nilai': 'Diameter Luar',
            'judul_pengulangan': 'Pembacaan',
            'titik_bisa_diubah': false,
            'pita_cetak': 1,
            'offset_kunci': 5000,
            'simpan_ke': 'spesifikasi_alat.flowmeter.diameter_pipa_mm',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Diameter Luar',
                'satuan': 'mm',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'mm',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'pipa_ketebalan',
            'judul': 'Ketebalan Dinding Pipa (Ultrasonic Thickness Gauge)',
            'satuan': 'mm',
            'judul_nilai': 'Ketebalan',
            'judul_pengulangan': 'Pembacaan',
            'titik_bisa_diubah': false,
            'pita_cetak': 1,
            'offset_kunci': 5100,
            'simpan_ke': 'spesifikasi_alat.flowmeter.ketebalan_pipa_mm',
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Ketebalan',
                'satuan': 'mm',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'mm',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
        ],
      },
      {
        'kode': 'hasil',
        'halaman': 1,
        'judul': 'Measurement',
        'field': <dynamic>[],
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'flow_uut_pembacaan',
            'judul': 'Pembacaan UUT',
            'satuan': 'Lpm',
            'judul_nilai': 'Titik',
            'judul_pengulangan': 'Ulangan',
            'titik_bisa_diubah': true,
            'pita_cetak': 2,
            'offset_kunci': 0,
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1',
                'satuan': 'Lpm',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Titik 2',
                'satuan': 'Lpm',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Titik 3',
                'satuan': 'Lpm',
              },
            ],
            'kolom': [
              {
                'kode': 'durasi_1',
                'label': 'Durasi 1',
                'tipe': 'angka',
                'satuan': 'Lpm',
              },
              {
                'kode': 'durasi_2',
                'label': 'Durasi 2',
                'tipe': 'angka',
                'satuan': 'Lpm',
              },
              {
                'kode': 'durasi_3',
                'label': 'Durasi 3',
                'tipe': 'angka',
                'satuan': 'Lpm',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'flow_std_pembacaan',
            'judul': 'Pembacaan Standar (Krohne UFC300)',
            'satuan': 'Lpm',
            'judul_nilai': 'Titik',
            'judul_pengulangan': 'Pembacaan',
            'titik_bisa_diubah': true,
            'pita_cetak': 3,
            'offset_kunci': 1000,
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1',
                'satuan': 'Lpm',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Titik 2',
                'satuan': 'Lpm',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Titik 3',
                'satuan': 'Lpm',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'Lpm',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'flow_suhu_awal',
            'judul': 'Suhu Air — awal',
            'satuan': '°C',
            'judul_nilai': 'Titik',
            'judul_pengulangan': 'Pembacaan',
            'titik_bisa_diubah': true,
            'pita_cetak': 4,
            'offset_kunci': 2000,
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1',
                'satuan': 'Lpm',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Titik 2',
                'satuan': 'Lpm',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Titik 3',
                'satuan': 'Lpm',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': '°C',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'flow_suhu_akhir',
            'judul': 'Suhu Air — akhir',
            'satuan': '°C',
            'judul_nilai': 'Titik',
            'judul_pengulangan': 'Pembacaan',
            'titik_bisa_diubah': true,
            'pita_cetak': 4,
            'offset_kunci': 3000,
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1',
                'satuan': 'Lpm',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Titik 2',
                'satuan': 'Lpm',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Titik 3',
                'satuan': 'Lpm',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': '°C',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'flow_densitas_uut',
            'judul': 'Densitas Fluida UUT (wajib kalau satuan berbasis massa)',
            'satuan': 'kg/L',
            'judul_nilai': 'Titik',
            'judul_pengulangan': 'Pembacaan',
            'titik_bisa_diubah': true,
            'pita_cetak': 4,
            'offset_kunci': 4000,
            'baris': [
              {
                'nomor': 1,
                'titik_ukur': null,
                'label': 'Titik 1',
                'satuan': 'Lpm',
              },
              {
                'nomor': 2,
                'titik_ukur': null,
                'label': 'Titik 2',
                'satuan': 'Lpm',
              },
              {
                'nomor': 3,
                'titik_ukur': null,
                'label': 'Titik 3',
                'satuan': 'Lpm',
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Nilai',
                'tipe': 'angka',
                'satuan': 'kg/L',
              },
            ],
            'pengulangan': [
              1,
            ],
          },
        ],
      },
      {
        'kode': 'penutup',
        'halaman': 1,
        'judul': 'Catatan & Tanda Tangan',
        'field': [
          {
            'kode': 'catatan_teknisi',
            'label': 'Catatan',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'teknisi.nama',
            'label': 'Dikalibrasi Oleh',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'reviewer.nama',
            'label': 'Diperiksa Oleh',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
    ],
  };
}
