/// Bentuk lembar kerja contoh **instrumen analitik** — untuk sekarang baru
/// Conductivitymeter.
///
/// DIGENERATE `docs/skrip/gen-contoh-lembar-kerja.php` di repo API — jangan
/// disunting tangan.
///
/// ## Kenapa berkas ini baru ada sekarang, dan kenapa cuma berisi satu
///
/// Kedelapan contoh instrumen analitik lain (pH, Turbidimeter, Chlorine,
/// Refractometer, Spectro, Visco, DO, Gas Detector) masih tinggal DI DALAM
/// `lembar_kerja_service.dart` — bentuk lama, sebelum contoh dipisah per
/// kelompok pengukuran. Conductivity penghuni pertama berkas ini; sisanya
/// menyusul kalau ada yang memindahkan, dan tempatnya sudah disiapkan.
///
/// Yang bikin Conductivity dikerjakan duluan: dia satu-satunya profil analitik
/// yang **nggak punya bentuk mock sama sekali** sampai 9 September 2026, jadi
/// di mode mock dia diam-diam memajang lembar pH — tanpa error di mana pun.
/// Yang menemukannya `bentuk_mock_semua_profil_test.dart`, sapuan yang daftar
/// profilnya diambil dari registry server.
///
/// ## Bukan alat yang divonis PASS/FAIL
///
/// Catatan utang yang pertama ditulis sempat menyebut Conductivity "DIVONIS
/// PASS/FAIL"; itu KELIRU. `ConductivityProfile::punyaToleransi()` memulangkan
/// `false`, dan `docs/kontrak-api.md` maupun tabel vonis mock sama-sama sudah
/// menempatkannya di kelompok yang berhenti di `U95%`. Dicatat di sini supaya
/// keliru itu nggak dipungut ulang dari riwayat.
library;

/// Bentuk lembar kerja contoh **Conductivitymeter**.
///
/// Kode profil `conductivity_meter`, satuan `-`, kertas `SIDIK-FM-CAL-0510_Rev.5`.
Map<String, dynamic> contohBentukLembarKerjaConductivity({
  bool untukAdmin = false,
}) {
  return {
    'kode_dokumen': 'SIDIK-FM-CAL-0510_Rev.5',
    'kode_metode': 'SIDIK-IK-CAL-0507_Rev.6',
    'judul': 'Calibration Worksheet - Conductivity Meter',
    'jumlah_pengulangan': 5,
    'larutan_standar': [
      25.0,
      1412.0,
      111.0,
    ],
    'satuan': null,
    'satuan_campuran': true,
    'suhu_wajib': true,
    'satuan_suhu': '°C',
    'semua_kolom_opsional': true,
    'catatan_pengisian': 'Suhu larutan WAJIB diisi buat tiap titik yang pembacaannya diisi — nilai acuan larutan digeser ikut suhu, jadi titik tanpa suhu nggak bisa dihitung. Titik yang datanya belum cukup nggak ikut dihitung, dan sertifikatnya baru bisa terbit sesudah dilengkapi admin.',
    'bagian': [
      {
        'kode': 'identitas_alat',
        'halaman': 1,
        'judul': 'EQUIPMENT IDENTITY AND CUSTOMER DATA',
        'field': [
          {
            'kode': 'tanggal_terima',
            'label': 'Received Date',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_kalibrasi',
            'label': 'Calibration Date',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'equipment_id',
            'label': 'Equipment',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_alat',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'equipment.nama_alat',
            'label': '1. Name',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'equipment.range_resolusi',
            'label': '2. Range/Resolution',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_model',
            'label': '3. Type/Model',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_serial_number',
            'label': '4. Serial Number/LPI',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_merk',
            'label': '5. Merk/Manufacture',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'thermohygro_standard_id',
            'label': '6. Thermohygro used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_thermohygro',
            'satuan': null,
            'pilihan': [
              {
                'nilai': '1',
                'label': 'TH-1',
                'grup': 'Inlab',
              },
              {
                'nilai': '3',
                'label': 'TH-3',
                'grup': 'Inlab',
              },
              {
                'nilai': '4',
                'label': 'TH-4',
                'grup': 'Inlab',
              },
              {
                'nilai': '5',
                'label': 'TH-5',
                'grup': 'Inlab',
              },
              {
                'nilai': '2',
                'label': 'TH-2',
                'grup': 'Insitu',
              },
              {
                'nilai': '6',
                'label': 'TH-6',
                'grup': 'Insitu',
              },
              {
                'nilai': '7',
                'label': 'TH-7',
                'grup': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'pemilik',
        'halaman': 1,
        'judul': 'OWNER',
        'field': [
          {
            'kode': 'pemilik_nama',
            'label': '1. Name',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'pemilik_alamat',
            'label': '2. Address',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'usage_check',
        'halaman': 1,
        'judul': 'STANDARD',
        'baris': [
          {
            'label': 'Conductivity Std Solution 25 µS/cm',
            'label_cetak': 'Std Solution 84 µS',
            'standard_id': 23,
            'serial_number': 'LRAD7693',
            'no_sertifikat': 'LRAD7693',
            'tertelusur_ke': 'Merck KGaA',
            'terdaftar': true,
          },
          {
            'label': 'Conductivity Std Solution 1412 µS/cm',
            'label_cetak': 'Std Solution 1413 µS',
            'standard_id': 24,
            'serial_number': 'LRAD9052',
            'no_sertifikat': 'LRAD9052',
            'tertelusur_ke': 'Merck KGaA',
            'terdaftar': true,
          },
          {
            'label': 'Conductivity Std Solution 111 mS/cm',
            'label_cetak': 'Std Solution 5000 µS',
            'standard_id': 25,
            'serial_number': 'HC56824055',
            'no_sertifikat': 'HC56824055',
            'tertelusur_ke': 'Merck KGaA',
            'terdaftar': true,
          },
          {
            'label': 'PT100/SH1',
            'label_cetak': 'PRT PT100',
            'standard_id': 47,
            'serial_number': 'SH1/20',
            'no_sertifikat': 'SH1/20',
            'tertelusur_ke': 'SNSU-BSN',
            'terdaftar': true,
          },
          {
            'label': 'Termometer & Sensor Std.',
            'label_cetak': 'Victor 14+',
            'standard_id': 13,
            'serial_number': '23P1005',
            'no_sertifikat': '23P1005',
            'tertelusur_ke': 'LK-285-IDN',
            'terdaftar': true,
          },
        ],
        'field': [
          {
            'kode': 'standar_dicek.*.dipakai',
            'label': 'Usage Check',
            'tipe': 'centang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'standar_dicek.*.keterangan',
            'label': 'Keterangan',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'data_kalibrasi',
        'halaman': 1,
        'judul': 'CALIBRATION DATA',
        'field': [
          {
            'kode': 'lokasi',
            'label': '1. Location',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {
                'nilai': 'lab',
                'label': 'Inlab',
              },
              {
                'nilai': 'onsite',
                'label': 'Insitu',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi_nama',
            'label': 'Nama Tempat (Insitu)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'onsite',
              ],
            },
          },
          {
            'kode': 'room_id',
            'label': 'Ruangan (Inlab)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_ruangan',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': [
                'lab',
              ],
            },
          },
          {
            'kode': 'calibration_method_id',
            'label': '2. Calibration Methode',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_metode',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'hasil',
        'halaman': 1,
        'judul': 'CALIBRATION RESULT',
        'field': [
          {
            'kode': 'suhu_awal',
            'label': 'Env. Condition — First',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_awal',
            'label': 'Env. Condition — First',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_akhir',
            'label': 'Env. Condition — End',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_akhir',
            'label': 'Env. Condition — End',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
        'tabel': [
          {
            'tahap': 'sebelum_adjustment',
            'judul': 'Before adjustment Reading',
            'baris': [
              {
                'titik_ukur': 25.0,
                'label': '25',
                'satuan': 'µS/cm',
                'resolusi': 0.1,
                'desimal': 1,
                'eksklusif_dengan': null,
                'standard_id': 23,
                'standard_nama': 'Conductivity Std Solution 25 µS/cm',
              },
              {
                'titik_ukur': 1412.0,
                'label': '1412',
                'satuan': 'µS/cm',
                'resolusi': 1.0,
                'desimal': 0,
                'eksklusif_dengan': 1.412,
                'standard_id': 24,
                'standard_nama': 'Conductivity Std Solution 1412 µS/cm',
              },
              {
                'titik_ukur': 1.412,
                'label': '1.412',
                'satuan': 'mS/cm',
                'resolusi': 0.001,
                'desimal': 3,
                'eksklusif_dengan': 1412.0,
                'standard_id': 24,
                'standard_nama': 'Conductivity Std Solution 1412 µS/cm',
              },
              {
                'titik_ukur': 111.0,
                'label': '111',
                'satuan': 'mS/cm',
                'resolusi': 0.01,
                'desimal': 2,
                'eksklusif_dengan': null,
                'standard_id': 25,
                'standard_nama': 'Conductivity Std Solution 111 mS/cm',
              },
            ],
            'sumbu_pengulangan': 'baris',
            'slot_cetak': [
              {
                'label': '84',
                'varian': null,
                'titik_ukur': [
                  25.0,
                ],
                'satuan': 'µS/cm',
                'resolusi': 0.1,
                'desimal': 1,
              },
              {
                'label': '1413 µS',
                'varian': '1.413 mS',
                'titik_ukur': [
                  1412.0,
                  1.412,
                ],
                'satuan': 'µS/cm',
                'resolusi': 1.0,
                'desimal': 0,
              },
              {
                'label': '5000 µS',
                'varian': '5 mS',
                'titik_ukur': [
                  111.0,
                ],
                'satuan': 'mS/cm',
                'resolusi': 0.01,
                'desimal': 2,
              },
              {
                'label': '80000 µS',
                'varian': '80 mS',
                'titik_ukur': <dynamic>[],
                'satuan': null,
                'resolusi': null,
                'desimal': null,
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Reading',
                'tipe': 'angka',
                'satuan': null,
              },
              {
                'kode': 'suhu',
                'label': '°C',
                'tipe': 'angka',
                'satuan': '°C',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
              4,
              5,
            ],
          },
          {
            'tahap': 'sesudah_adjustment',
            'judul': 'After adjustment Reading',
            'baris': [
              {
                'titik_ukur': 25.0,
                'label': '25',
                'satuan': 'µS/cm',
                'resolusi': 0.1,
                'desimal': 1,
                'eksklusif_dengan': null,
                'standard_id': 23,
                'standard_nama': 'Conductivity Std Solution 25 µS/cm',
              },
              {
                'titik_ukur': 1412.0,
                'label': '1412',
                'satuan': 'µS/cm',
                'resolusi': 1.0,
                'desimal': 0,
                'eksklusif_dengan': 1.412,
                'standard_id': 24,
                'standard_nama': 'Conductivity Std Solution 1412 µS/cm',
              },
              {
                'titik_ukur': 1.412,
                'label': '1.412',
                'satuan': 'mS/cm',
                'resolusi': 0.001,
                'desimal': 3,
                'eksklusif_dengan': 1412.0,
                'standard_id': 24,
                'standard_nama': 'Conductivity Std Solution 1412 µS/cm',
              },
              {
                'titik_ukur': 111.0,
                'label': '111',
                'satuan': 'mS/cm',
                'resolusi': 0.01,
                'desimal': 2,
                'eksklusif_dengan': null,
                'standard_id': 25,
                'standard_nama': 'Conductivity Std Solution 111 mS/cm',
              },
            ],
            'sumbu_pengulangan': 'baris',
            'slot_cetak': [
              {
                'label': '84',
                'varian': null,
                'titik_ukur': [
                  25.0,
                ],
                'satuan': 'µS/cm',
                'resolusi': 0.1,
                'desimal': 1,
              },
              {
                'label': '1413 µS',
                'varian': '1.413 mS',
                'titik_ukur': [
                  1412.0,
                  1.412,
                ],
                'satuan': 'µS/cm',
                'resolusi': 1.0,
                'desimal': 0,
              },
              {
                'label': '5000 µS',
                'varian': '5 mS',
                'titik_ukur': [
                  111.0,
                ],
                'satuan': 'mS/cm',
                'resolusi': 0.01,
                'desimal': 2,
              },
              {
                'label': '80000 µS',
                'varian': '80 mS',
                'titik_ukur': <dynamic>[],
                'satuan': null,
                'resolusi': null,
                'desimal': null,
              },
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'Reading',
                'tipe': 'angka',
                'satuan': null,
              },
              {
                'kode': 'suhu',
                'label': '°C',
                'tipe': 'angka',
                'satuan': '°C',
              },
            ],
            'pengulangan': [
              1,
              2,
              3,
              4,
              5,
            ],
          },
        ],
      },
      {
        'kode': 'penutup',
        'halaman': 1,
        'judul': 'Catatan & Tanda Tangan',
        'field': [
          {
            'kode': 'catatan_teknisi',
            'label': 'Catatan',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'teknisi.nama',
            'label': 'Calibrated by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'reviewer.nama',
            'label': 'Checked by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': <dynamic>[],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
    ],
    'untuk': 'teknisi',
  };
}
