/// Bentuk lembar kerja contoh **Timbangan** (kelompok Massa, alat ke-21).
///
/// ## Kenapa berkas ini ada, dan kenapa isinya nggak diketik tangan
///
/// Isinya salinan APA ADANYA dari `TimbanganProfile::bentukLembarKerja()`
/// dengan alat contoh `TB-100` (kapasitas 100 kg, resolusi 0,02 kg) — sesi
/// `011-CAL-525` yang ter-seed di backend. Diambil dari server, bukan disusun
/// ulang di sini: bentuk yang diketik tangan bakal menyimpang diam-diam begitu
/// backendnya direvisi, dan test yang jalan di atas bentuk basi memberi rasa
/// aman yang salah.
///
/// ## Yang dijaga bentuk ini, dan nggak dijaga bentuk lain mana pun
///
/// Empat hal cuma ada di lembar ini, dan keempatnya pernah salah:
///
///  1. **Dua tabel yang baris titiknya BENTROK.** Accuracy memuat 50 kg &
///     100 kg; Repeatability memuat Middle 50 kg & Maximum 100 kg. Tanpa
///     `offset_kunci`, empat baris itu berbagi dua `TitikState` — angka yang
///     diketik di tabel satu muncul di tabel satunya lagi.
///  2. **Tabel yang isinya BUKAN titik ukur.** Repeatability menyatakan
///     `simpan_ke: spesifikasi_alat.keterulangan`; isinya besaran satu per
///     sesi, jadi nggak boleh masuk `measurements[]`.
///  3. **Kotak tambahan per baris.** `kolom_baris` berisi `nominal` bertipe
///     `daftar_angka` — susunan keping yang ditumpuk (`20+20+10`). Server yang
///     menjumlahkannya jadi `titik_ukur`.
///  4. **Kode field bersarang.** Empat blok (`scale_observation`,
///     `effect_of_tare`, `eksentrisitas`, `histeresis`) memakai awalan
///     `spesifikasi_alat.` dengan titik BERTINGKAT. Tanpa awalan itu HP
///     membacanya sebagai kolom turunan: read-only, dan nggak pernah terkirim.
///
/// Empat dropdown di blok identitas MENENTUKAN ANGKA, bukan hiasan —
/// `tipe_timbangan` memilih tabel anak timbangan (E2 vs F1), `varian_master`
/// memilih revisi rumusnya, `tipe_display` menentukan `a`, dan
/// `jenis_timbangan` menentukan nilai `e`. Pilihannya datang dari server
/// lengkap; jangan dipetakan ulang di sini.
library;

Map<String, dynamic> contohBentukLembarKerjaTimbangan({
  bool untukAdmin = false,
}) {
  final bentuk = <String, dynamic>{
    'profil': 'timbangan',
    'judul': 'KALIBRASI MASSA / TIMBANGAN',
    'kode_dokumen': null,
    'metode': 'NMI Monograph 4 (CSIRO 2010)',
    // Salinan `TimbanganProfile::bentukPindaiFoto()`. Ikut di sini, bukan
    // diserahkan ke bawaan `MockLembarKerjaService`: bawaan itu menyalakan
    // jalur cloud, dan lembar ini justru satu-satunya yang mematikan
    // dua-duanya. Alasannya ada di docblock metode itu — ringkasnya lab belum
    // pernah menerbitkan kertas lembar ini.
    'pindai_foto': {
      'kolom_suhu': false,
      'standar_di_baris': false,
      'didukung': false,
    },
    'alat_baru': {
      'kode_kategori': 'massa',
      'nama_alat_kemampuan': 'Timbangan (Elektronik, mekanik)',
    },
    'bagian': [
      {
        'kode': 'identitas_alat',
        'halaman': 1,
        'judul': 'IDENTITAS ALAT',
        'field': [
          {
            'kode': 'tanggal_terima',
            'label': 'Received Date',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tanggal_kalibrasi',
            'label': 'Calibration Date',
            'tipe': 'tanggal',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'equipment_id',
            'label': 'Equipment',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_alat',
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'equipment.nama_alat',
            'label': '1. Nama Alat',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_merk',
            'label': '2. Merk',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_model',
            'label': '3. Type',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'alat_serial_number',
            'label': '4. No. Seri',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.rentang_ukur',
            'label': '5. Rentang Ukur',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.kapasitas',
            'label': '6. Kapasitas Alat',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.resolusi',
            'label': '7. Resolusi Alat',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.nilai_e',
            'label': '8. Nilai e (boleh "-")',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.kelas',
            'label': '9. Kelas (I / II / III / IIII, boleh "-")',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tipe_display',
            'label': 'Tipe Display',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {'nilai': 'Digital', 'label': 'Digital'},
              {'nilai': 'Mekanik', 'label': 'Mekanik'},
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'tipe_timbangan',
            'label': 'Tipe Timbangan',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {'nilai': 'Non-Analytical', 'label': 'Non-Analytical'},
              {'nilai': 'Analytical', 'label': 'Analytical'},
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'jenis_timbangan',
            'label': 'Jenis Timbangan',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {'nilai': 'tak_bertingkat', 'label': 'Tak Bertingkat'},
              {
                'nilai': 'bertingkat_analog',
                'label': 'Bertingkat, tanpa alat penunjuk tambahan (analog)',
              },
              {
                'nilai': 'bertingkat_digital',
                'label': 'Bertingkat, dengan alat penunjuk tambahan (digital)',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'varian_master',
            'label': 'Metode Pembebanan',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {'nilai': 'kg', 'label': 'Langsung (kg)'},
              {'nilai': 'gram', 'label': 'Langsung (gram)'},
              {
                'nilai': 'substitusi',
                'label': 'Beban substitusi (kapasitas besar)',
              },
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'pemilik',
        'halaman': 1,
        'judul': 'IDENTITAS CUSTOMER',
        'field': [
          {
            'kode': 'pemilik_nama',
            'label': '1. Nama Customer',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'pemilik_alamat',
            'label': '2. Alamat Customer',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi',
            'label': 'Lokasi Kalibrasi',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {'nilai': 'lab', 'label': 'Inlab'},
              {'nilai': 'onsite', 'label': 'Insitu'},
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'lokasi_nama',
            'label': 'Nama Tempat (Insitu)',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': ['onsite'],
            },
          },
          {
            'kode': 'room_id',
            'label': 'Ruangan (Inlab)',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_ruangan',
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': {
              'kode': 'lokasi',
              'nilai': ['lab'],
            },
          },
          {
            'kode': 'calibration_method_id',
            'label': 'Calibration Method',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_metode',
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_awal',
            'label': 'Suhu Ruangan — Awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'suhu_akhir',
            'label': 'Suhu Ruangan — Akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '°C',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_awal',
            'label': 'Kelembaban — Awal',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'kelembaban_akhir',
            'label': 'Kelembaban — Akhir',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': '%RH',
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'thermohygro_standard_id',
            'label': 'Thermohygro Used',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': 'master_thermohygro',
            'satuan': null,
            'pilihan': [
              {'nilai': '1', 'label': 'TH-1', 'grup': 'Thermohygro lab'},
              {'nilai': '2', 'label': 'TH-2', 'grup': 'Thermohygro lab'},
              {'nilai': '3', 'label': 'TH-3', 'grup': 'Thermohygro lab'},
              {'nilai': '4', 'label': 'TH-4', 'grup': 'Thermohygro lab'},
              {'nilai': '5', 'label': 'TH-5', 'grup': 'Thermohygro lab'},
              {'nilai': '6', 'label': 'TH-6', 'grup': 'Thermohygro lab'},
              {'nilai': '7', 'label': 'TH-7', 'grup': 'Thermohygro lab'},
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'usage_check',
        'halaman': 1,
        'judul': 'STANDAR ANAK TIMBANGAN',
        'baris': [
          {
            'kode': 'AT1',
            'nama': 'Anak Timbangan E2',
            'nominal': '100 mg - 200 gr',
            'standard_id': 51,
            'terdaftar': true,
          },
          {
            'kode': 'AT2',
            'nama': 'Anak Timbangan F1',
            'nominal': '100 mg - 500 gr',
            'standard_id': 52,
            'terdaftar': true,
          },
          {
            'kode': 'AT3',
            'nama': 'Anak Timbangan F21',
            'nominal': '1000 gr',
            'standard_id': 53,
            'terdaftar': true,
          },
          {
            'kode': 'AT4',
            'nama': 'Anak Timbangan F22',
            'nominal': '2000 gr',
            'standard_id': 54,
            'terdaftar': true,
          },
          {
            'kode': 'AT5',
            'nama': 'Anak Timbangan F25',
            'nominal': '5000 gr',
            'standard_id': 55,
            'terdaftar': true,
          },
          {
            'kode': 'AT6',
            'nama': 'Anak Timbangan M2',
            'nominal': '20 kg',
            'standard_id': 56,
            'terdaftar': true,
          },
          {
            'kode': 'AT7',
            'nama': 'Anak Timbangan F1-10',
            'nominal': '10 kg',
            'standard_id': 57,
            'terdaftar': true,
          },
        ],
        'field': [
          {
            'kode': 'standar_dicek.*.dipakai',
            'label': 'Usage Check',
            'tipe': 'centang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'standar_dicek.*.keterangan',
            'label': 'Keterangan',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'scale_observation',
        'halaman': 1,
        'judul': '1. SCALE OBSERVATION',
        'field': [
          {
            'kode':
                'spesifikasi_alat.scale_observation.sebelum_adjustment.standar',
            'label': 'Before — Standar Weight',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.scale_observation.sebelum_adjustment.z1',
            'label': 'Before — z1',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.scale_observation.sebelum_adjustment.m1',
            'label': 'Before — m1',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.scale_observation.sebelum_adjustment.m2',
            'label': 'Before — m2',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.scale_observation.sebelum_adjustment.z2',
            'label': 'Before — z2',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode':
                'spesifikasi_alat.scale_observation.sesudah_adjustment.standar',
            'label': 'After — Standar Weight',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.scale_observation.sesudah_adjustment.z1',
            'label': 'After — z1',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.scale_observation.sesudah_adjustment.m1',
            'label': 'After — m1',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.scale_observation.sesudah_adjustment.m2',
            'label': 'After — m2',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.scale_observation.sesudah_adjustment.z2',
            'label': 'After — z2',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'effect_of_tare',
        'halaman': 1,
        'judul': '2. EFFECT OF TARE',
        'field': [
          {
            'kode': 'spesifikasi_alat.effect_of_tare.standar',
            'label': 'Standar Weight',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.effect_of_tare.m1',
            'label': 'm1',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.effect_of_tare.m2',
            'label': 'm2',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.effect_of_tare.bentuk_pan',
            'label': 'Bentuk Pan',
            'tipe': 'pilihan',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': [
              {'nilai': 'kotak', 'label': 'Kotak'},
              {'nilai': 'lingkaran', 'label': 'Lingkaran'},
            ],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.effect_of_tare.ukuran_pan',
            'label': 'Ukuran / Diameter Pan',
            'tipe': 'teks',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'akurasi',
        'halaman': 1,
        'judul': '3. ACCURACY',
        'tabel': [
          {
            'kolom_baris': [
              {
                'kode': 'nominal',
                'label': 'Nominal keping (pisahkan dengan +)',
                'tipe': 'daftar_angka',
                'wajib': false,
                'sumber': null,
                'satuan': 'kg',
                'pilihan': const [],
                'hanya_admin': false,
                'tampil_kalau': null,
              },
            ],
            'tahap': 'sesudah_adjustment',
            'grup': 'akurasi',
            'judul': 'Accuracy — pembebanan bertingkat',
            'satuan': 'kg',
            'judul_nilai': 'Nominal',
            'judul_pengulangan': 'Pembacaan',
            'pengulangan_arah': [
              {'ke': 1, 'label': 'z'},
              {'ke': 2, 'label': 'm'},
              {'ke': 3, 'label': 'm\''},
              {'ke': 4, 'label': 'z\''},
            ],
            'titik_bisa_diubah': true,
            'baris': [
              {'titik_ukur': 10, 'label': '10 kg', 'satuan': 'kg'},
              {'titik_ukur': 20, 'label': '20 kg', 'satuan': 'kg'},
              {'titik_ukur': 30, 'label': '30 kg', 'satuan': 'kg'},
              {'titik_ukur': 40, 'label': '40 kg', 'satuan': 'kg'},
              {'titik_ukur': 50, 'label': '50 kg', 'satuan': 'kg'},
              {'titik_ukur': 60, 'label': '60 kg', 'satuan': 'kg'},
              {'titik_ukur': 70, 'label': '70 kg', 'satuan': 'kg'},
              {'titik_ukur': 80, 'label': '80 kg', 'satuan': 'kg'},
              {'titik_ukur': 90, 'label': '90 kg', 'satuan': 'kg'},
              {'titik_ukur': 100, 'label': '100 kg', 'satuan': 'kg'},
            ],
            'kolom': [
              {
                'kode': 'pembacaan',
                'label': 'kg',
                'tipe': 'angka',
                'satuan': 'kg',
              },
            ],
            'pengulangan': [1, 2, 3, 4],
          },
        ],
        'field': const [],
      },
      {
        'kode': 'keterulangan',
        'halaman': 1,
        'judul': '4. REPEATABILITY',
        'tabel': [
          {
            'tahap': 'sesudah_adjustment',
            'grup': 'keterulangan',
            'judul': 'Repeatability — 10 pengulangan',
            'satuan': 'kg',
            'offset_kunci': 1000,
            'simpan_ke': 'spesifikasi_alat.keterulangan',
            'judul_nilai': 'Kapasitas',
            'judul_pengulangan': 'Pengulangan ke-',
            'titik_bisa_diubah': false,
            'baris': [
              {'titik_ukur': 50, 'label': 'Middle Capacity', 'satuan': 'kg'},
              {'titik_ukur': 100, 'label': 'Maximum Capacity', 'satuan': 'kg'},
            ],
            'kolom': [
              {
                'kode': 'zero',
                'label': 'Zero (zi)',
                'tipe': 'angka',
                'satuan': 'kg',
              },
              {
                'kode': 'pembacaan',
                'label': 'Reading (mi)',
                'tipe': 'angka',
                'satuan': 'kg',
              },
            ],
            'jumlah_pengulangan': 10,
            'pengulangan': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
          },
        ],
        'field': const [],
      },
      {
        'kode': 'eksentrisitas',
        'halaman': 1,
        'judul': '5. LOADING INFLUENCE ON EACH POSITION',
        'field': [
          {
            'kode': 'spesifikasi_alat.eksentrisitas.beban',
            'label': 'Beban yang dipakai',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.eksentrisitas.baca.center',
            'label': 'Center',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.eksentrisitas.baca.front',
            'label': 'Front',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.eksentrisitas.baca.back',
            'label': 'Back',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.eksentrisitas.baca.left',
            'label': 'Left',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.eksentrisitas.baca.right',
            'label': 'Right',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'histeresis',
        'halaman': 1,
        'judul': '6. HYSTERISIS',
        'field': [
          {
            'kode': 'spesifikasi_alat.histeresis.m',
            'label': 'M',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.histeresis.m_aksen',
            'label': 'M\'',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.histeresis.baca1.0',
            'label': 'Reading 1 — M(p1)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.histeresis.baca1.1',
            'label': 'Reading 1 — M+M\'',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.histeresis.baca1.2',
            'label': 'Reading 1 — M(q1)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.histeresis.baca1.3',
            'label': 'Reading 1 — Zero',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.histeresis.baca1.4',
            'label': 'Reading 1 — M+M\'',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.histeresis.baca1.5',
            'label': 'Reading 1 — M(q2)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.histeresis.baca1.6',
            'label': 'Reading 1 — Zero',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.histeresis.baca1.7',
            'label': 'Reading 1 — M(p2)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.histeresis.baca2.0',
            'label': 'Reading 2 — M(p1)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.histeresis.baca2.1',
            'label': 'Reading 2 — M+M\'',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.histeresis.baca2.2',
            'label': 'Reading 2 — M(q1)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.histeresis.baca2.3',
            'label': 'Reading 2 — Zero',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.histeresis.baca2.4',
            'label': 'Reading 2 — M+M\'',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.histeresis.baca2.5',
            'label': 'Reading 2 — M(q2)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.histeresis.baca2.6',
            'label': 'Reading 2 — Zero',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'spesifikasi_alat.histeresis.baca2.7',
            'label': 'Reading 2 — M(p2)',
            'tipe': 'angka',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
      {
        'kode': 'penutup',
        'halaman': 1,
        'judul': 'Catatan & Tanda Tangan',
        'field': [
          {
            'kode': 'catatan_teknisi',
            'label': 'Catatan',
            'tipe': 'teks_panjang',
            'wajib': false,
            'sumber': null,
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'teknisi.nama',
            'label': 'Calculated by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
          {
            'kode': 'reviewer.nama',
            'label': 'Signed by',
            'tipe': 'teks',
            'wajib': false,
            'sumber': 'otomatis',
            'satuan': null,
            'pilihan': const [],
            'hanya_admin': false,
            'tampil_kalau': null,
          },
        ],
      },
    ],
  };

  if (untukAdmin) {
    (bentuk['bagian'] as List).add(_bagianAdmin());
  }

  return bentuk;
}

/// Blok admin, dipisah supaya bentuk teknisi & bentuk admin nggak jadi dua
/// salinan yang harus dirawat berbarengan.
Map<String, dynamic> _bagianAdmin() => {
  'kode': 'administratif',
  'halaman': 1,
  'judul': 'Data Administratif (Admin)',
  'field': [
    {
      'kode': 'nomor_order',
      'label': 'Order Number',
      'tipe': 'teks',
      'wajib': false,
      'sumber': null,
      'satuan': null,
      'pilihan': const [],
      'hanya_admin': true,
      'tampil_kalau': null,
    },
    {
      'kode': 'certificate.nomor',
      'label': 'Certificate Number',
      'tipe': 'teks',
      'wajib': false,
      'sumber': 'otomatis',
      'satuan': null,
      'pilihan': const [],
      'hanya_admin': true,
      'tampil_kalau': null,
    },
    {
      'kode': 'lop',
      'label': 'Limit of Performance',
      'tipe': 'angka',
      'wajib': false,
      'sumber': 'otomatis',
      'satuan': null,
      'pilihan': const [],
      'hanya_admin': true,
      'tampil_kalau': null,
    },
    {
      'kode': 'histeresis_hasil',
      'label': 'Hysterisis',
      'tipe': 'angka',
      'wajib': false,
      'sumber': 'otomatis',
      'satuan': null,
      'pilihan': const [],
      'hanya_admin': true,
      'tampil_kalau': null,
    },
  ],
};
